### ISSUE TITLE
TBSync does not work with GMX 2-Factor Auth

### ISSUE THREAD

**Issue by makaanneo** [jobisoft/DAV-4-TbSync#102]
## Your environment

TbSync version: 1.7
Thunderbird version: 60.7.1

[x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TBSync is working with GMX new 2 Factor Auth functionality

## Actual behavior
could not authenticate against endpoint: https://carddav.gmx.net/.well-known/carddav

Error Log:

URL:
https://carddav.gmx.net/.well-known/carddav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:

## Steps to reproduce
Add new Account and Select GMX Europe.
Username: someemail@gmx.net
pw: Application specific pw

## Notes
Application Passwords work with other applications like:
imap.gmx.net
GMX Mediacenter app

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
=> no debug output created.

**Comment by jobisoft** [comment]
Any news?

**Comment by jobisoft** [comment]
@makaanneo : Status?

**Comment by jobisoft** [comment]
It works with calendar, but contacts fail. If you use manual setup and specify this caldav url

`https://kalender-bs-ddos.gmx.net/begenda/dav/users/`

but no carddav url, it works. As soon as you add the carddav url

`https://carddav.gmx.net/.well-known/carddav`

TbSync will complain about a bad password (reported by the carddav server). Closing this as I cannot do anything to fix it.

**Comment by gna582** [comment]
I got the same issue in thurnderbird, but the android app davx5 (open source: https://github.com/bitfireAT/davx5-ose) could add gmx's contact book with 2FA enabled.
In the settings, this is shown as the path it used to sync the contacts:
https://carddav.gmx.net/CardDavProxy/carddav/AddressBook/<10numbers>/Contact/

Sadly, using that path didn't work for me, it says there is no carddav server at that location. Also tried different subpaths, to no success.
