### ISSUE TITLE
Failure to find resources on Radicale

### ISSUE THREAD

**Issue by madduck** [jobisoft/DAV-4-TbSync#103]
## Your environment

TbSync version: 1.7.0.2
DAV-4-TbSync version: 0.15.0.2
Thunderbird version: 60.0.8

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TbSync should load the `/.well-known/carddav` URL from the server, follow the redirect, and use the terminal location.

## Actual behavior
TbSync runs `PROPFIND` on `/` only, and then reports that it could not find a CardDAV resource.

## Steps to reproduce
Just add the account, enter the URL, tell it to sync.

**Comment by jobisoft** [comment]
If you select the first option (Discovery Service) it should do exactly that. Can you retry?

**Comment by madduck** [comment]
Thank you @jobisoft for your quick response. I've now tried Discovery Service, but am running up against an issue I have with Radicale (https://github.com/Kozea/Radicale/issues/983).

Meanwhile, however, I wonder why I cannot set it up manually, e.g. entering `carddav.madduck.net/madduck@madduck.net/addressbook.vcf/` as the resource, and skipping discovery. If I try that, then I get:

> Could not find a CardDAV server.
> 
> Account: madduck.net
> 
> carddav.madduck.net/madduck@madduck.net/addressbook.vcf

in the debug log. Here's the request that goes out:

```
PROPFIND /madduck@madduck.net/addressbook.vcf HTTP/1.1
Host: carddav.madduck.net
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0 Lightning/6.2.8
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Length: 85
Content-Type: application/xml; charset=utf-8
Depth: 0
Prefer: return-minimal
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=

<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
```

and the response that comes back:

```
<?xml version="1.0"?>
<multistatus xmlns="DAV:" />
```

I don't know anything about DAV, but I do know that using the URL directly works fine with Thunderbird itself, with Sogo, with DAVx5 (Android), with `vdirsyncer`, and with `hdav`.

Should I file another issue about this? Or where should I be looking to figure this out?

**Comment by jobisoft** [comment]
> Should I file another issue about this? 

No, as this is not how TbSync works. The user should not have to know any of the internal URLs. Just the plain server url or the path to the actual CalDAV/carddav server in manual setup.

You can say: If it works with iPhone, than it should work with TbSync, if not, it is a bug. 

Take a look at the wiki to see some screenshots: TbSync is showing you all available resources and you can select which one you want to sync.

I have however tested against radicale and I think it worked. Could it be a server issue?

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/wiki/How-to-get-started

**Comment by jobisoft** [comment]
Maybe that helps:
https://github.com/Kozea/Radicale/issues/954#issuecomment-497425243

**Comment by jobisoft** [comment]
TbSync using the same method as Apple Calendar ...

**Comment by jobisoft** [comment]
Further findings: I tested again with radicale and for me the discovery service also did not work, but the manual setup. 

The urls to my resources look like so:
http://someserver.org:5232/jb/dc30c4e7-8451-1b72-2176-7644ebc05043/

and in the manual setup I entered
http://someserver.org:5232

For both caldav and carddav and got a list of all avail resources:
![image](https://user-images.githubusercontent.com/5830621/63581235-de7cd500-c596-11e9-8b0c-0b9a119ca602.png)

Hope this helps.

**Comment by madduck** [comment]
> You can say: If it works with iPhone, than it should work with TbSync, if not, it is a bug.

Actually, be careful here. Over the years, we've encountered many times that Apple's implementation of DAV (or other protocols) were buggy and non-standard. Also, iPhone currently is the only devices that doesn't reliably synchronise against Radicale, while Sogo, DAVx5 (Android), vdirsyncer, and hdav all work fine, although I do not use discovery with any of them, but the full URLs (see below).

Of course, this could be a problem with Radicale.
 
> Take a look at the wiki to see some screenshots: TbSync is showing you all available resources and you can select which one you want to sync.

Yeah, I've seen the Wiki, and I've tried everything. No matter what I enter into the configuration, dynamic, or manual, I never even get to the screen that shows the available resources.

> Further findings: I tested again with radicale and for me the discovery service also did not work, but the manual setup.
> 
> The urls to my resources look like so:
> http://someserver.org:5232/jb/dc30c4e7-8451-1b72-2176-7644ebc05043/
> 
> and in the manual setup I entered
> http://someserver.org:5232
> 
> For both caldav and carddav and got a list of all avail resources

Our CardDAV resources look like this: `https://carddav.example.org/user@example.com/addressbook.vcf/`

I have tried all of:

* `https://carddav.example.org/user@example.com/addressbook.vcf/`
* `https://carddav.example.org/user@example.com/`
* `https://carddav.example.org/.well-known/addressbook`
* `https://carddav.example.org/.well-known/contacts`
* `https://carddav.example.org/`

but all of these just get me the same error message, and no resources are shown.

![image](https://user-images.githubusercontent.com/195073/63644889-e67b7700-c746-11e9-87bc-da969ca60839.png)

DAVx5 on Android, when I give it the first URL, does show me the available resources, so it isn't that Radicale is completely broken. But TBSync is doing something different than all the other tools I'm using, and this is the first time I'm running into trouble.

**Comment by jobisoft** [comment]
You may set `extensions.tbsync.log.userdatalevel` to 9 and enable debug logging (under help in the account manager), restart (!) and retry to setup your account. Afterwards go to help again and create a debug report.

You may just look at the created report to see if it has hints for you, or just send it to me.

Alternativly, I would need a test account on this server, to investigate this isssue further.

**Comment by madduck** [comment]
Hello @jobisoft, I've set `extensions.tbsync.log.userdatalevel` to 9, enabled debug logging, then restarted Thunderbird (!), and then tried to set up the account. If I want to mail the debug log, a message is created with a 0-byte attachment.

The error log itself shows that the request

```
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
```

was met with

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
<title>500 Internal Server Error</title>
</head>
<body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@madduck.net to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at carddav.madduck.net Port 443</address>
</body>
</html>
```

The Apache logs reveal that there's a read error on the uwsgi socket:

```
2404:130:0:1000:80db:d0de:53cb:1693 - - [27/Aug/2019:03:35:51 +0200] "PROPFIND /.well-known/caldav HTTP/1.1" 401 4880 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0 Lightning/6.2.8"
2404:130:0:1000:80db:d0de:53cb:1693 - madduck@madduck.net [27/Aug/2019:03:35:51 +0200] "PROPFIND /.well-known/caldav HTTP/1.1" 303 101 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0 Lightning/6.2.8"
2404:130:0:1000:80db:d0de:53cb:1693 - - [27/Aug/2019:03:35:52 +0200] "GET /madduck@madduck.net/calendar.ics/ HTTP/1.1" 401 4880 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0 Lightning/6.2.8"
2404:130:0:1000:80db:d0de:53cb:1693 - madduck@madduck.net [27/Aug/2019:03:35:52 +0200] "GET /madduck@madduck.net/calendar.ics/ HTTP/1.1" 200 1721814 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0 Lightning/6.2.8"
2404:130:0:1000:80db:d0de:53cb:1693 - - [27/Aug/2019:03:35:58 +0200] "PROPFIND /.well-known/carddav HTTP/1.1" 401 955 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0 Lightning/6.2.8"

==> error.log <==
[Tue Aug 27 03:35:58.998057 2019] [:error] [pid 10970] [client 2404:130:0:1000:80db:d0de:53cb:1693:35585] uwsgi: read() client block failed !
```

The uWSGI server log doesn't say anything though:

```
[pid: 6696|app: 0|req: 3223/3271] 2404:130:0:1000:80db:d0de:53cb:1693 (madduck@madduck
.net) {56 vars in 894 bytes} [Tue Aug 27 03:35:51 2019] PROPFIND /.well-known/caldav =
> generated 0 bytes in 1 msecs (HTTP/1.1 303) 1 headers in 72 bytes (0 switches on cor
e 0)
[pid: 6696|app: 0|req: 3224/3272] 2404:130:0:1000:80db:d0de:53cb:1693 (madduck@madduck
.net) {52 vars in 853 bytes} [Tue Aug 27 03:35:52 2019] GET /madduck@madduck.net/calendar.ics/ => generated 1709529 bytes in 3786 msecs (HTTP/1.1 200) 4 headers in 163 bytes (10 switches on core 0)
[pid: 6696|app: 0|req: 3225/3273] 2404:130:0:1000:80db:d0de:53cb:1693 (madduck@madduck.net) {56 vars in 896 bytes} [Tue Aug 27 03:35:58 2019] PROPFIND /.well-known/carddav => generated 0 bytes in 1 msecs (HTTP/1.1 303) 1 headers in 75 bytes (1 switches on core 1)
```

I used to use TbSync just fine until it a 60+ version of Thunderbird came out that was no longer supported by the addon. Now that the TbSync addons were brought up to date, it no longer works. The Radicale server has not changed, nor has it been updated. And it works with all other clients in user over here.

I've created a test account on `carddav.madduck.net`: `testuser:UnshavedPolygraphSubscriptTarantulaRottenSeverity`. Please let me know when I can disable it again.

**Comment by jobisoft** [comment]
Hi Martin,

I spend an hour working with your server and i have to stop now. My findings:

1. Your server throws a 500 on https://carddav.madduck.net/.well-known/carddav, so something is wrong there on your servers discovery service.

2. Your carddav server is sitting at https://carddav.madduck.net and if I do manual setup and make a standard

```
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
```
with my testuser, I get back an empty multistatus response. From my debug log:

```
** Tue Aug 27 2019 09:21:04 GMT+0200 **
[URL Request #1] : https://carddav.madduck.net/

** Tue Aug 27 2019 09:21:04 GMT+0200 **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

** Tue Aug 27 2019 09:21:05 GMT+0200 **
[GET] : nsIAuthPrompt2

** Tue Aug 27 2019 09:21:05 GMT+0200 **
[RESPONSE] : 207 (Unknown) : <?xml version="1.0"?>
<multistatus xmlns="DAV:" />
```

Which means the server is responding but does not return anything. The error message reported by TbSync is indeed misleading, as the CardDAV server was found, but no resources. That has been fixed for TbSync 2.1.

I do not know, why your server is doing that. But there is nothing I can do as your server is not reporting your current-user-principal. Please check the official dav documentation on resource discovery:

http://sabre.io/dav/building-a-carddav-client/
On that page, search for "Ideally you will want to make sure" to jump to the Discovery section.

As reported in https://github.com/jobisoft/DAV-4-TbSync/issues/103#issuecomment-524239171 it does work with Radicale in generall. I am really sorry. I do not see an error on my side.

Regarding the following statement:

> I used to use TbSync just fine until it a 60+ version of Thunderbird came out that was no longer supported by the addon. Now that the TbSync addons were brought up to date, it no longer works. The Radicale server has not changed, nor has it been updated. And it works with all other clients in user over here.

What do you mean? Beta versions of Thunderbird? TB68 is not out yet but I do support it. Even TB69. I skipped TB61-67 (all Beta versions and not intended for productive use) due to the massive changes under the hood. In your initial report, you stated you used Thunderbird 60.8. Is that not the case? I have always supported TB60. I do not know what your statement is about.

**Comment by madduck** [comment]
Dear @jobisoft, thank you so much for your time. Have you got an IBAN or a Bitcoin address, then I'd love to make a donation to the project.

I also think Radicale is at fault. I've followed all docs down to the letter, and I cannot see anything wrong, but there must be. So I'll investigate more.

I have used TbSync in the past. Then it stopped working at some point, possibly when I updated to a beta. But now, even with the latest TbSync, I cannot get it to work with either TB 60.8, or TB 68.

Anyway, I'll look into Radicale more. Thank you for your time!

**Comment by jobisoft** [comment]
This is still a strange issue, as you reported:

> I have tried all of:
>
> * https://carddav.example.org/user@example.com/addressbook.vcf/
> * ...
> 
> DAVx5 on Android, when I give it the first URL, does show me the available resources, so it isn't that Radicale is completely broken.

All available resources or just the one you specified?

Thanks for considering a donation. If paypal is not an option, I can send you my IBAN by email. I tried to look it up on your homepage linked in your github profile (https://madduck.net/), but that gives me a forbidden. Maybe related to this issue?

**Comment by jobisoft** [comment]
This is fixed after you setup your server anew, right? Can we close this?
