### ISSUE TITLE
Workaround for Synology XML error

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/DAV-4-TbSync#104]
Using a standard HTTPS connection to a Synology CardDAV server sometimes results in incomplete XML responses, thus aborting any sync. This was only observed with HTTPS, not with HTTP.

User @patrick-hessinger finaly found a workaround, which allows to use HTTPS again:

The Synology DSM offers a Reverse Proxy-Functionality (Control Panel > Application Portal > Reverse Proxy). Create a Reverse Proxy Rule, that has localhost and the HTTP port (default 8008) of the CardDAV-Server as destination. 

![Screenshot Reverse Proxy](https://user-images.githubusercontent.com/10141151/64066791-78d7bb00-cc1e-11e9-93d8-490729ed8058.png)

The reverse proxy will wrap the result in HTTPS, so communication to the client is secure. With this config it does not drop the connection anymore. Whatever Synology's cardDAV Server does wrong, the Reverse Proxy fixes it.

Without full investigation, I would say this is an Synology and not an TbSync issue then. Hope this workaround helps others getting there from the help button in the message.

**Comment by patrick-hessinger** [comment]
I was asked to explain how to fill the blacked fields. I blacked the data out, as in may case these are reachable via internet. Basically you are quite free what to put there.

Source Hostname can any hostname or domain name that routes to your Synology NAS, this can also be a "*" for all hostnames your NAS uses.
For the port choose any free port on your NAS, it will tell you if another application uses it.
The hostname and port you enter there is the host and port you insert in TBSync to connect. 
In case you have the firewall active, you have to open the source port you specified at the proxy, the destination port (original cardDAV server port) can be blocked, as it only is used internally.

An example: Your Synology has the hostname mydiskstation and you know port 50001 is free.
You but mydiskstation as source host name and 50001 as source port.
In TB Sync you then use mydiskstation:50001/addressbooks/users/<username>/addressbook as a server address to connect via HTTPS.

The "source" is the connection connection parameters you want to be visible "outside" your NAS. This is the connection data TBSync and other clients will use to connect to the NAS. The reverse proxy will register this for itself and inspect the incoming traffic. It then matches hostname and port to know which is the real server/service itself has to connect to.

**Comment by Kauzig** [comment]
Hi. Thank you for sharing this solution. I tried to implement the workaround, but it doesn't fully work. When I try and open the new URL (from the reverse proxy) in a browser I can see the CardDAV XML, but when I use the URL in TBSync I get an error message that no CardDAV Server could be found. Do you have an idea what the problem could be?

**Comment by jobisoft** [comment]
Can you send me the url to your sever in private (email) and setup a test account?

**Comment by Kauzig** [comment]
> Can you send me the url to your sever in private (email) and setup a test account?

I have sent you an email.
