### ISSUE TITLE
Store the current-user-principal persistently

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#108]
As far as I can see from the logs, every time TBsync synchronizes an account, it asks for the HREF of the current user principal and uses the HREFs to obtain for the calendar-home-set and addressbook-home-set.  Since the address of the current-user-principle never changes, TBSync shall obtain it once, store it and as long as the user name is not changed, not retrieve it again.  This saves network resources.

In theory, there can be two different hrefs of the principle: one obtained for caldav (over PROPFIND /.well-known/caldav) and one obtained over carddav (using PROPFIND /.well-known/carddav).  In practice the principal urls are always the same.

In the ideal case, TBSync shall retrieve over both paths the principal-href.  If the principal-hrefs coincide, then a single call shall be made to obtain both calendar-home-set and addressbook-home-set.  If the principal-hrefs differ, both hrefs shall be stored and retrieving the calendar-home-set and addressbook-home-set shall be done with distinct calls.

**Comment by jobisoft** [comment]
Are these calls really a resource issue? I start at the beginning each time to catch redirects on (temporary and permanently), at least that was my thinking. Furthermore I separate caldav and carddav, because there are services using different servers (iCloud, gmx, ...) for each.

How many calls do we save? 1? 2?

**Comment by dilyanpalauzov** [comment]
With 10 000 CalDAV/CardDAV clients connecting to a single server, it is a resource issue.  Lets say hypothetically the server can handle 10 000 clients, if they save 2 calls, and 9 500 clients, if they do not save these two calls on each synchronization.

**Comment by dilyanpalauzov** [comment]
Also clients get results faster, when they request an update, since the update makes less calls.

**Comment by jobisoft** [comment]
Ok, understood. I see the need.

I will store the current-user-principal, which will save the following request:

```
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
```

But I will cont. to request the home-sets, as they might change, correct?

**Comment by jobisoft** [comment]
I have release a new version including this via my beta release channel. Wanna give it a spin?
https://tbsync.jobisoft.de

**Comment by dilyanpalauzov** [comment]
While I do not expect that the personal URL returned by calendar-home-set or addressbook-home-set will change, the amount of returned hrefs can change.  Lets say, today it answers with
```xml
<CAL:calendar-home-set>
  <href>/dav/calendars/user/aaa@milter.aegee.org/</href>
</CAL:calendar-home-set>
```
tomorrow it can return
```xml
<CAL:calendar-home-set>
  <href>/dav/calendars/user/aaa@milter.aegee.org/</href>
  <href>/dav/calendars/user/anonymous@milter.aegee.org/</href>
</CAL:calendar-home-set>
```

More interisting is the use case with calendar sharing, where one user grant access to one of its calendars to another user.  There are two approaches:
* with notifications, described at https://evertpot.com/webdav-caldav-carddav-sharing/
* with WebDAV ACLs, starting with the REPORT verb to locate the calendar-home-set of the searched user.  Like
```xml
curl -XREPORT -D- -H"Depth: 0" -u me:pw -H"Content-Type: application/xml" --data '<?xml version="1.0" encoding="UTF-8" ?>
  <D:principal-property-search xmlns:D="DAV:">
    <D:property-search>
      <D:prop><D:displayname/></D:prop>
      <D:match>sandra</D:match>
    </D:property-search>
    <D:prop><C:addressbook-home-set xmlns:C="urn:ietf:params:xml:ns:carddav"/><D:displayname/></D:prop>
  </D:principal-property-search>' https://server/dav/principals/
```
returning
```xml
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav">
  <D:response>
    <D:href>/dav/principals/user/sandra/</D:href>
    <D:propstat>
      <D:prop>
        <C:addressbook-home-set><D:href>/dav/addressbooks/user/sandra/</D:href></C:addressbook-home-set>
        <D:displayname>sandra</D:displayname>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
```

The returned home-set is then checked for callendars, the requeting user has access to.

I guess, the home-set (addressbook or calendar) of the user, or the addresses within them, returned as search result, shall be stored persistently, for the HREFs of the current principle, I have no strong opinion.  That is why I asked to store only the principal URL, which does not change.

**Comment by jobisoft** [comment]
I will store just the principal URL then.

**Comment by dilyanpalauzov** [comment]
I do understand you, but unfortunately I cannot orginize funding.

**Comment by dilyanpalauzov** [comment]
In the account options, the CalDAV and CardDAV .well-known URLs are shown (stub URLs in terms of RFC 6764).  The CUA stores the principal URL and obtains from principle properties, like the homesets.

Are the well-known URLs ever used again and if they are not used, what is the point to show them in the account configuration setup?

For the record, once DAV-4-TbSync utilizes the DNS discovery of RFC 6764 the obtained URLs will not be .well-known/carddav, but the url, where .well-known/carddav redirects to.

**Comment by dilyanpalauzov** [comment]
If the server decides at some moment to respond with “301Permanetly Moved” the requests to the Principal-URL, then DAV-4-TbSync shall update the principal-url it stored persistently. (Just in case this is not implemented.)

**Comment by jobisoft** [comment]
The principal URL is stored in an internal property and if using that principal caused an error, itis thrown away and we start from the beginning with the well-known urls (or whatever has been specified during account creation).

But updating the server urls, if they received a 301, is probably a good idee, I need to check, if I have access to that information (redirects happen internally). Could you create a new issue for that?
