### ISSUE TITLE
Long delay when starting thunderbird

### ISSUE THREAD

**Issue by diagprov** [jobisoft/DAV-4-TbSync#109]
## Your environment

TbSync version: v2.4
DAV-4-TBSync Version: v1.3
Thunderbird version: 68.0 64-bit Official build from Thunderbird.net
Zimbra Collaboration Server: 8.8.9 Open Source

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Thunderbird starts when run, asks for the master password for the software security device, then proceeds to sync email, calendar and contacts.

I have configured multiple calendars, a contacts address book and an email account.

## Actual behavior
After selecting the correct thunderbird profile, the UI does not actually appear for approximately 1-2 minutes. When it does, a further ~30 seconds are required in order to usably enter the master password. At this point all inboxes will have timed out their authentication for IMAP, so there's a further fight before the UI becomes usable.

Eventually, thunderbird can actually be used, but this makes starting thunderbird and using it extremely painful.

## Steps to reproduce

Install addon, configure account matching that of Zimbra server, restart thunderbird and attempt to use.

I've uninstalled the add-on, unfortunately. I hoped it would provide carddav sync but I have alternative ways to sync my address book.

## Workaround

Lightning can directly subscribe to caldav calendars and this works without the above mentioned issues.

**Comment by jobisoft** [comment]
A debug log would help, as it logs timestamps at we could see what module is doing the delay.

Install TbSync + DAV again, open the TbSync account manager, go to help pane and enable debug logging

Restart

After TB is "done", go to the help pane again and create a bug report.

I have not seen this before.

**Comment by jobisoft** [comment]
If you do not want to get this fixed, can I close this?

**Comment by dilyanpalauzov** [comment]
From this report it is not clear, whether the server is slow and forces the client to be slow, or only the client is slow.
