### ISSUE TITLE
JavaScript error even after TB restart

### ISSUE THREAD

**Issue by jurgenhaas** [jobisoft/DAV-4-TbSync#11]
Probably the same as #2 but since that's closed I thought it's best to start a new issue.

I'm still having this issue, even after restarting Tunderbird 60 several times.

The error is in sync.js at line 141:

```
if (cal && folder && folder.target) {
```

The variable cal is not defined.

**Comment by jobisoft** [comment]
You have Lightning installed, otherwise tbSync would not try to use the cal variable, but the Version you have installed is not working.

Can you send me a debug log? I can tell you more than.
https://github.com/jobisoft/TbSync/wiki/Found-a-bug%3F

**Comment by jurgenhaas** [comment]
Debug log is attached here: [debug.log](https://github.com/jobisoft/DAV-4-TbSync/files/2382588/debug.log)

Lightning was installed but disabled. I have now removed it and restarted TB and the error is still the same.

I have then downloaded the XPI here from GitHub and installed manually. The XPI is slightly smaller than the one from TB plugin store. But even then, the error is the same.

**Comment by jobisoft** [comment]
Sorry, you have to restart TB so the log also contains the start up sequence. That bug is strange....

**Comment by jobisoft** [comment]
Oh, you hit a bug indeed. Thanks for reporting this. Stay tuned.

**Comment by jurgenhaas** [comment]
Oh great, glad to hear that :-)

**Comment by jobisoft** [comment]
Please retry:
https://github.com/jobisoft/DAV-4-TbSync/releases/download/v0.8/DAV-4-TbSync.xpi

**Comment by jurgenhaas** [comment]
Confirmed, the JS error is gone.

The follow-up message is now confusing me as it tells me that Lightning is required in order to support calendars. Isn't TbSync a replacement for Lightning? And where can I get a Lightning version for TB 60 as the official one from the TB store is not compatibel with it?

**Comment by jobisoft** [comment]
No, that is a misunderstanding. Please read the README.
https://github.com/jobisoft/DAV-4-TbSync

If you still have questions, just ask.

You need lightning 6.2 for TB60, it should ship directly with Thunderbird.

**Comment by jurgenhaas** [comment]
Thanks @jobisoft for your support, much appreciated. I can't find lightning 6.2 thoughj, but that's a different issue then.

**Comment by jobisoft** [comment]
Rename to XPI
[lightning62.zip](https://github.com/jobisoft/DAV-4-TbSync/files/2382682/lightning62.zip)

The long way to get lightning back is to create a new profile in Thunderbird which should include lightning and then search that profile dir for {e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi. 

- copy that file somewhere
- launch TB using your original profile
- install xpi

**Comment by jurgenhaas** [comment]
Wow, thanks a lot. That works great.
