### ISSUE TITLE
Offer account setup without username and password

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#110]
Currently to setup an account the user has to enter hostname, username and password.

Permit setting up accounts only with username and without password.

**Comment by dilyanpalauzov** [comment]
No username and password is also necessary to provide Kerberos authentication.
```xml
$ echo abc |kinit aaa@AEGEE.ORG
Password for aaa@AEGEE.ORG: 
$ klist 
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: aaa@AEGEE.ORG

Valid starting       Expires              Service principal
09/18/2019 11:35:27  09/19/2019 11:35:27  krbtgt/AEGEE.ORG@AEGEE.ORG

$curl --version
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.3 libidn2/2.0.3 libpsl/0.20.2 (+libicu/63.1) libssh2/1.8.2 
nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli **GSS-API** HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL **SPNEGO** SSL TLS-SRP UnixSockets


$ curl -u: --negotiate  -HDepth:1 -XPROPFIND -HContent-Type:application/xml \
--data "<?xml version='1.0' encoding='UTF-8' ?>
<d:propfind xmlns:d='DAV:' xmlns:cal='urn:ietf:params:xml:ns:caldav' xmlns:CARD='urn:ietf:params:xml:ns:carddav'>
  <d:prop><d:displayname /><CARD:addressbook-description /></d:prop>
</d:propfind>" \
https://mail.aegee.org/dav/addressbooks/user/aaa/

<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav">
  <d:response>
    <d:href>/dav/addressbooks/user/aaa/</d:href>
    <d:propstat>
      <d:prop><d:displayname><![CDATA[#addressbooks]]></d:displayname></d:prop>
    <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop><CARD:addressbook-description/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/dav/addressbooks/user/aaa/Default/</d:href>
    <d:propstat>
      <d:prop><d:displayname><![CDATA[personal]]></d:displayname></d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop><CARD:addressbook-description/></d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/dav/addressbooks/public/</d:href>
    <d:propstat>
      <d:prop><d:displayname><![CDATA[AEGEE-wide public add
ress book]]></d:displayname><CARD:addressbook-description><![CDATA[Contact mail@aegee.org if you want to take care of filling data here, either manually or automatically.]]></CARD:addressbook-description></d:prop>
      <d:status>HTTP/1.1 200 OK</d:status></d:propstat>
  </d:response>
</d:multistatus>
```
works.  Without authentication it fails:
```
$ kdestroy && klist
klist: No credentials cache found (filename: /tmp/krb5cc_1000)

curl -D- -u: --negotiate  -HDepth:1 -XPROPFIND -HContent-Type:application/xml \
--data "<?xml version='1.0' encoding='UTF-8' ?>
<d:propfind xmlns:d='DAV:' xmlns:cal='urn:ietf:params:xml:ns:caldav' xmlns:CARD='urn:ietf:params:xml:ns:carddav'>
  <d:prop><d:displayname /><CARD:addressbook-description /></d:prop>
</d:propfind>" \
https://mail.aegee.org/dav/addressbooks/user/aaa/

HTTP/2 401 
server: nginx
date: Wed, 18 Sep 2019 11:43:09 GMT
content-type: text/html; charset=utf-8
content-length: 448
vary: Accept-Encoding
www-authenticate: Basic realm="AEGEE.ORG"
www-authenticate: Negotiate

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>401 Unauthorized</title><
/head><body><h1>Unauthorized</h1><p>Must authenticate to access the specified target</p><hr><address>Cyrus-HTTP/3.0.11-91-geb3fa3e0d Cyrus-SASL/2.
1.27 OpenSSL/1.1 Zlib/1.2.11 Brotli/1.0.7 LibXML/2.9.9 SQLite/3.29.0 LibiCal/3.0 ICU4C/63.1 Jansson/2.12 Server at 127.0.0.3 Port 80</address></body></html>
```

This test requires also a version of Cyrus-Sasl, that works.  For me this means without the commit 238380260fe623212c0f21d63e763b7a849540d1 “Call gss_acquire_cred() before gss_init_sec_context() in”.

**Comment by jobisoft** [comment]
How does this work? I can understand "no password", which I can probably impl.

But "no username"? The user does need to provide some sort of credentials, does he not? 

How das Kerberos authentication work? 
Does it work with your test server (aaa/abc)? What do I have to do to trigger it?

**Comment by dilyanpalauzov** [comment]
Anoymous authentication is supposed to work without sending an Authorization header.

I think of two forms: 
* user enters anonymous@domain as user name and any password is accetped.  The server does not have to insist on obtaining password from the user before continuing.  This is not standard (for HTTP, as opposed to SASL ANONYMOUS mechanism) and not discussed here further.
* user enters hostname.  The CUA perform all actions, without receiving 401 unauthorized and without sending X-EnforceAuthentication.  Currently this does not fully work with my test server.

With Kerberos in mind, the a further login form is
* user enters hostname, but no username and password.  The CUA performs all actions without receivings 401 unauthorized and by sending valid Authorization.  How can the CUA know, if the user wants to authenticate or not?  If the CUA/the operating system has a kerberos5 ticket for the domain, then the ticket is used by the CUA and it sends Authorization:.  Otherwise the login is anonymous.

I cannot explain here how Kerberos (Signle Sign On even for not HTTP) authentication works, it is really too long to go into the details.  Check other sources, like:
* https://en.wikipedia.org/wiki/Kerberos_(protocol)
* https://web.mit.edu/kerberos/#what_is

The example above with curl demostrates how it can be used in practice: obtain a ticket with kinit, use SPNEGO/Negotiate, destroy the ticket.

Kerberos authentication with username (e.g. abc@aegee.org) does work with mail.aegee.org for HTTP/WebDAV.

Kerberos authentication without username exists also in theory, there are two forms of it: anonymous ticket with realm (domain) and anonymous ticket without domain.  I use MIT Kerberos, and it issues only anonymous authentication without realm, so I have not utilized it.

**Comment by dilyanpalauzov** [comment]
Let me clarify, that for a domain the tickets are obtained from a server listed in SRV _kerberos._tpc.domain.  The record SRV _kerberos._tcp.aegee.org exists and SRV _kerberos._tcp.milter.aegee.org does not exists.  That is why the Kerberos authentication for user aaa@aegee.org does work.  For user aaa@milter.aegee.org Kerberos authentication will also work, if the software obtaining the kerberos tickets is told to use upd/tcp:mail.aegee.org:88 for this.

**Comment by dilyanpalauzov** [comment]
As I wrote, currently my server does not offer anonymous access.  Coming soon…

**Comment by jobisoft** [comment]
ahhhhhhhhhhhhhhhh!

**Comment by jobisoft** [comment]
1. You said that anonymous access works with evolution. How did you test that, if your own servers do not support that? How can I test that now?

2. For the future: Do NOT request something, that is not implemented, so it cannot be tested. You do realize, that I spend a LOT of time on your requests?

3. How can the server/client differ between anonymous access and kerberos access? I have no knowlege about kerberos and just searched the web on how to set that up under windows but failed. Can you test it? When you create a kerberos ticket (outside of TB), should Thunderbird pick that up during negotiate and authenticate using that, if no username is specified? But than we would be back to "Kerberos users cannot access resources for unauthenticated users", or not?

**Comment by jobisoft** [comment]
3b. Wait, do I need a username, but no password for kerberos? That would of course eliminate the "Kerberos users cannot access resources for unauthenticated users" problem. I now removed the user/password restriction altogether.

Are you able to test Kerberos with that setup? Would you consider this issue done?

**Comment by dilyanpalauzov** [comment]
1. In the past anonymous access has worked on the server, then it was implemented and tested with Evolution.  Then I did reorganizations and now it does not work.

2. If the client sends Authorization headers, as consequence of using the Kerberos authentication scheme, then from server’s perspective this is not anymous access.  The harder question is, how can a client know, if it shall use Kerberos authenticataion or anonymous authentication.

Windows setup with Firefox:

Visit https://mail.aegee.org/dav/calendars/user/aaa .  Without entering username nothing happens.

Install [MIT Kerberos for Windows 4.1](https://web.mit.edu/kerberos/dist/), get a ticket for aaa@aegee.org .

Change in Firefox about:config `network.auth.use-sspi` to false and `network.negotiate-auth.trusted-uris` to https://mail.aegee.org .  I restarted Firefox afterwards, but this might not be necessary.

Visit again https://mail.aegee.org/dav/calendars/user/aaa .  The browser asks for username and password, I click on “Cancel”, the right content is displayed, as the browser uses Authorization: Negotiate.

So if the client has Kerberos ticket and the negotiate-auth.trusted-uris is in effect, then the CUA shall not ask the user for username.

Testing under Thunderbird, I set sspi to false and trusted-uri to https://mail.aegee.org .  When I try to set up account for host mail.aegee.org, the log says \<unauthenticated\> and therefore current-user-principle cannof be found.

**Comment by jobisoft** [comment]
Brilant step by step guide!

If you do the same changes to Thunderbird (`network.auth.use-sspi` and `network.negotiate-auth.trusted-uris`) and use the latest beta which supports username but no password, it works!

But the found resources look different:
![image](https://user-images.githubusercontent.com/5830621/65413097-e9729180-ddf0-11e9-8f8e-9790d6ad3232.png)

He is sending a negotiate header.

Is this as expected?

**Comment by dilyanpalauzov** [comment]
This works for me, if I enter anything as username and password, let’s say user q, password q.  If I leave the username and passwords fields emtly, then no resources are found.

For user aaa@aegee.org, which is not the user aaa@milter.aegee.org, the found resources by TbSync are right and the HTML output at https://mail.aegee.org/dav/calendars/user/aaa is incomplete.

**Comment by dilyanpalauzov** [comment]
For the record, Firefox recognizes also https://aegee.org in trusted-uris for the mail.aegee.org host, so the host of the WebDAV server must not be identical with the host in the trusted-uris configuration.

**Comment by jobisoft** [comment]
Isn't the ticket bound to a username, as there could be more than one? Multiple users? So i would have assumed, that you must enter a valid username, so Thunderbird can use the correct ticket. But it looks like, only one user per domain is allowed and as soon as he sees a request for a host he has a tickt for, he ignores the username (and the password).

If you do not enter a username, you are running as anonymous. So that is expected.

Is there anything, that still needs to be done? If you want to connect to multiple-kerberos-users-accounts, I think that needs changes in core.

Close?

**Comment by dilyanpalauzov** [comment]
Kerberos is a Signle-Sign-On system.  When the user logins on the station, the user gets a ticket granting ticket and whenever it accesses different services, the user magically obtains more tickets for each service and host.  There is also cross-realm authentication, with which I have no experience, but it allows to obtain a ticket for other domain, without entering a password, based on the ticket granting ticket.

Moreover, a user can explicitly obtain several tickets, and set one of them as default.  My understanding is, that at any moment only one ticket is default and all other explicitly obtained tickets are irrelevant, at least during connecton establishment which for stateless HTTP means always irrelevant.

That said, the ticket is bound to the system and session, where the user is logged.  I have no idea how this works with multiple users.  In theory there are no multiple users.  If one user has rights to access resources for another user, then the access is granted based on the the requested resource and provided ticket.  The server just checks, if the access rights are sufficient, without using a this user/different user concept.

DAV-4-TbSync is supposed to permit one username to read resources of many users based on Basic authentication, without insisting to have several accounts, and storing to which non-own collections the user has subscribed.  Let's do not discuss this here.

It is not expected, when no username is entered, to run as anonymous.  It is expected, when Kerberos is used, that no usernames are entered and users still authenticate.

I do not see a use case to connect multiple kerberos user accounts to the same system.

However, I tried to setup IMAP account with Kerberos (SASL GSSAPI) in Thunderbird.  And Thunderbird insists of having a valid username, as otherwise the authentication fails.  I asked at https://bugzilla.mozilla.org/show_bug.cgi?id=1583145 why for IMAP with GSSAPI username is required.

**Comment by jobisoft** [comment]
> I do not see a use case to connect multiple kerberos user accounts to the same system.

So no further acction.

> It is not expected, when no username is entered, to run as anonymous. It is expected, when Kerberos is used, that no usernames are entered and users still authenticate.

Ok, I would not have expected that answer from you, based on your other requests for anonymous access.

The thing is, this is caused by your server  - again - for not sending a `WWW-Authenticate` header if no `Authorization` header is send. Remember that discussion? I really do not want to go thru that again. 

What we did, we mitigated that with the `X-EnforceAuthentication` header, which is send by TbSync, if a username is provided, which cleary indicates the which to authenticate. Your server will then send the WWW-Auth header with BASIC and NEGOTIATION and Thunderbird than picks the correct one.

If no username is send, that header is not send, thus your server is running in anonymous mode and does not send the WWW-Auth header und thus TbSync is not able to do Keberos auth.

I do not want to bother with this any longer, as it starts to make me angry.

**Comment by dilyanpalauzov** [comment]
CalDAV/CardDAV over https://milter.aegee.org works now without username and password and DAV-4-TbSync shall allow this behaviour.

**Comment by jobisoft** [comment]
I think I did everything you asked for and TbSync allows accounts without username. You do not return home sets.

**Comment by jobisoft** [comment]
Did you find the error, why you do not send homesets? I do get the principal, but they do not return a homeset.

**Comment by dilyanpalauzov** [comment]
DAV-4-TbSync works as expected. At the time I wrote my previous comment, milter.aegee.org has returned homesets, but mail.aegee.org has not. Now they both work fine.
