### ISSUE TITLE
Invitation problem with "shared/readonly" calendars

### ISSUE THREAD

**Issue by johndoe7000** [jobisoft/DAV-4-TbSync#112]
## Your environment

TbSync version: 2.4
DAV-4-TbSync version: 1.3
Thunderbird version: 68.x

[x] Yes, I have installed the latest available (stable) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Invitation works as expected.

## Actual behavior
Thunderbird/Lightning throws error 80004005.

## Steps to reproduce
Currently the provider does not recognize if a calendar is readonly or falsely lets me decide to make it readonly or not.
On the other side cardDAV addressbooks are correctly recognized when they are readonly.

Let me explain in a real world example...
- User A is CEO.
- User B is secretary.
- User A gives "readonly" rights to his personal calendar to User B who should know when he is busy or away on business.
- User B synchronizes her calendars via TbSync and the readonly calendar from User A appears as read/write.
- User B activates the personal calendar from User A.
- User A invites User B via his personal calendar to a meeting.
- User B wants to accept the invitation into her own personal calendar but Thunderbird refuce this with Error: "Processing message failed. Status: 80004005".

What happend?
I think Thunderbird/Lightning realizes that the "corresponding" calendar is already here and refuses to send a REPLY mail and simply wants to update the calendar which fails because the calender is readonly.

To solve this problem I've set the "shared" calendar from User A in Thunderbird of User B as readonly via TbSync/CalDAV provider.
After this change accepting the invitation worked as expected.

I use a Kolab Groupware server with Thunderbird which allows any user to shared their calendars with others.

**Comment by jobisoft** [comment]
The provider reads the ACL attributes of the resources. If you have no write permission, it should set a calendar as readonly and should not allow you to change that via the TbSync Manager. It is however possible to change the readonly state via Lightning directly. 

You say, the TbSync Manager allows you to switch a calendar, you only have read permissions for, to read/write access?

**Comment by johndoe7000** [comment]
No, TbSync Manager shows all calendars as read/write but two of them are shared readonly with me from a different user.

**Comment by johndoe7000** [comment]
Edit:
I have changed my report to be more clear...
- User B synchronizes her calendars via TbSync and the readonly calendar from User A appears as read/write.

**Comment by jobisoft** [comment]
I would assume, your server is sending a wrong ACL information, otherwise TbSync would see that. Can you set

```
extensions.tbsync.log.userdatalevel = 9
```
in the advanced Thunderbird configuration and enable debug logging under Help in the TbSync Account Manager?

After you did that, restart Thunderbird and than disable and re-enable the account in question in the TbSync Account Manager. Do not actually sync anything. Then go to Help again and send me a debug report. The only thing this report will contain is the found reosurces and their ACL,, no private data, as you did not sync anything.

**Comment by johndoe7000** [comment]
Bug report is send.

**Comment by johndoe7000** [comment]
Forgot to mention in the bug report mail...
Calendar "Urlaub" is also readonly, but detected as read/write.

**Comment by jobisoft** [comment]
Both calendars are marked as full write access. Nothing I can do.
