### ISSUE TITLE
Cannot connect IceWarp server

### ISSUE THREAD

**Issue by sotoli** [jobisoft/DAV-4-TbSync#113]
## Your environment

TbSync version: 2.4
DAV-4-TbSync version: 1.3
Thunderbird version: 68.1.0. (32bit)

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Trying to connect IceWarp mail server I got the following message:
Could not find any resources on the server. Account km.it@domain.com

Used data: 
Account name: km.it@domain.com
user: km.it@domain.com
CALDAV server address:    xx.xx.xx.xx:32000/webdav
CardDAV server address:   xx.xx.xx.xx:32000/webdav

Alternative SoGo connector works fine with the following data
http://xx.xx.xx.xx:32000/webdav/km.it@domain.com/Contacts

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Can I have test account on that server?

**Comment by jobisoft** [comment]
Did you send me a test account? Otherwise I am going to close this soon.
