### ISSUE TITLE
Shared address books are not discovered with SOGo

### ISSUE THREAD

**Issue by erwint** [jobisoft/DAV-4-TbSync#114]
## Your environment

TbSync version: current Beta
DAV-4-TbSync version: current Beta
SOGo 4.0.8
Thunderbird version: 60

[x] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
The discovery finds not only the personal address book and GAL, but also addressbooks shared from other users

## Actual behavior
Only personal and GAL are found

## Steps to reproduce
- Share Address Book from User A with User B
- Add Account for User B
-> No Shared Address Book from A is discovered

The problem is a missing READ privilege advertised by SOGo, just a WRITE, BIND (and some other I don't remember) are provided. The fix is to assume that a WRITE privilege implies a READ privilege in sync.js like this:

```
diff --git a/content/sync.js b/content/sync.js
index 61012ed..0ac8dc6 100644
--- a/content/sync.js
+++ b/content/sync.js
@@ -179,6 +179,8 @@ dav.sync = {
                                     if (privilegNode.getElementsByTagNameNS(dav.ns.d, "bind").length > 0) acl |= 0x4;
                                     if (privilegNode.getElementsByTagNameNS(dav.ns.d, "unbind").length > 0) acl |= 0x8;
                                 }
+                            } else if (privilegNode.getElementsByTagNameNS(dav.ns.d, "write").length > 0) {
+                                acl = 0xF;
                             }
                         }
```
I verified this fixed the problem and works.

**Comment by jobisoft** [comment]
Do you know, where this ACL stuff is defined? Who is wrong? Me or SOGo?

**Comment by jobisoft** [comment]
Accepted. Releassed on my beta release channel.
https://tbsync.jobisoft.de

However only for TB68. TB60 only gets security updates.

Can you test it?

**Comment by dilyanpalauzov** [comment]
It is defined in RFC 3744.  In particular it states:
>[3.12.  Aggregation of Predefined Privileges](https://tools.ietf.org/html/rfc3744#section-3.12)
>
>DAV:write MUST NOT contain DAV:read, DAV:read-acl, or DAV:read-current-user-privilege-set.
>
>DAV:write MUST contain DAV:bind, DAV:unbind, DAV:write-properties and DAV:write-content.

So write privilege does not imply read privilege.

**Comment by erwint** [comment]
I tested the beta and it works now. Thanks!

**Comment by jobisoft** [comment]
Ok, that means SOGo is wrong. I include the fix as a temp workaround, but you need to file a bug at SOGo to get that fixed.

**Comment by erwint** [comment]
Reported to SOGo as [Bug #0004822](https://sogo.nu/bugs/view.php?id=4822)

**Comment by jobisoft** [comment]
Thanks.
