### ISSUE TITLE
Update principal URL on 301 answer

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#115]
If the server decides change the current-user-principle to return 301 MOVED PERMANENTLY, the CUA shall memorize this information and not ask again the old URL.

**Comment by jobisoft** [comment]
Added to beta release channel. PLease keep it mind, that simply syncing will not trigger this, as the stored principal is used. You must disable and reenable your account to trigger the 301 update logic

**Comment by dilyanpalauzov** [comment]
It is not feasible to require disabling and re-enabling an account to update the principal url on 301 moved permanently answer.

Imagine anonymois access is offered over HTTPS and some hundred users subscribe to it.  For performance reason the protocol is switched to HTTP and requesring the old principal-url will return the new one.  Obviously, none of the hundred users is going to disable and re-enable its account.

The opposite is also true.  If the change is made from http to https, the clients will not skip to http request and just act over https.

**Comment by jobisoft** [comment]
I understood the issue wrong. Didn't you talk about the redirect of well-known urls in the other issue? The server URLs? Somehow I assumed that without reading this issue.

That is what I have implemented. When the server sends a redirect on the server URLs, those redirects are now updating the stored server urls. Like 

```
/.well-know/caldav -> /remote.php/dav
```
But since we now have the principal shortcut, those server URLs are not used (expect the stored principal url no longer works). That is why I said you need to disable and re-enable your account, so that TbSync is requesting the original server url again and can see the redirect.

It does also do an https update. You can actually SEE the updated urls in the server settings tab.

Looking at the principal now.

**Comment by jobisoft** [comment]
The principal is already updated on every request.

Did you not test this before?

Can I close this?

**Comment by dilyanpalauzov** [comment]
At https://github.com/jobisoft/DAV-4-TbSync/issues/108#issuecomment-532745946 I wrote that I have not tested this.  To be able to test it, I need to see either the complete traffic from DAV-4-TbSync, which includes the headers, and goes therefore beyound what is stored in debug.log. Or I need to see what is stored as Principal URL.

How can I see what is stored as principal-url?

**Comment by jobisoft** [comment]
You can always see the full traffic using the developer console, including all headers and data send/received.

You can see all interhnal props in your profile folder.There is a tbsync subfolder with account68 and folder68.json. The principal is stored in accounts68.

However, I changed the behaviour for principal 301 this morning. If I get a 301, I throw the principal away and start from the beginning on next sync, as the correct principal should be announced via the PROPFIND. There is an issue with principal being relative (usually) and a 301 being absolute. It would have involved to many (error prone) checks to get that right.

It would be stupid, ff the server sends a redirect on the principal he is currently anouncing.

This is done for me

**Comment by dilyanpalauzov** [comment]
I gave this a try.  For the account aaa@milter.aegee.org the principal URL in accounts68.json is HTTPS://mail.aegee.org/dav/principals/user/aaa@milter/ .  I changed it to HTTP://mail.aegee.org/dav/principals/user/aaa@milter/ by effectively altering the variable https to false.

```
$ curl -D- -XPROPFIND http://mail.aegee.org/dav/principals/user/aaa@milter.aegee.org/
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sun, 22 Sep 2019 19:21:56 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://mail.aegee.org/dav/principals/user/aaa@milter.aegee.org/

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I expect that TbSync will see the 301 and update the principal url accordingly (hence set https to true). Instead it says Network Error.

**Comment by jobisoft** [comment]
Please do not mess with TbSyncs internal configuration! Instruct your server to do a 301.

**Comment by dilyanpalauzov** [comment]
So with the most current software, stopping TB, replacing https; true with false, starting TB, doing account synchronization once, does not set the secure bit in the UI.  Doing the account synchronization a second time sets the secure bit in the UI.  The tick shall be set when the account synchronization is performed once.

**Comment by jobisoft** [comment]
FYI: While working on the discovery stuff I had the case, that I got one http and one https server, which does not work with the single https bit. So I removed that altogether and the host name now includes the scheme.

That made follow redirects a lot easier, principals are now also followed again directly, without throwing it away on redirect and starting from scratch.

But it may still happen, that what you observed will remain - even "worse". If you modify (in the raw config, which you should not do) the stored HOST, but TbSync has also a stored PRINCIPAL, it will not use the HOST altogether and thus will never see a redirect from http back to https.

If you modify the principal, the current developer version will update the stored principal back to https directly after it got the redirect, but will again not start from scratch and thus will not use the HOST and will not see a redirect there and thus will not update it.

But this only happens, when you modify the raw config, which you should not do. 

The current restructuring is massiv and I need a bit more time before I can release something on the beta release channel for you to try.

**Comment by jobisoft** [comment]
Can you pay around with redirects with the new beta?
