### ISSUE TITLE
Inconsistencies between German and English text

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#116]
dav.strings:status.malformed-xml is in English “Could not parse XML. Check event log for details.” and in German “Antwort enthält fehlerhaftes XML, Sync abgebrochen. Prüfen Sie bitte das Ereignisprotokoll für weitere Details.”  The meaning is different because of “Sync abgebrochen”.

**Comment by dilyanpalauzov** [comment]
What mean “partially” in “status.info.restored=Due to partially missing write permissions, some actions were rejected by the server and reversed locally”?  How can the write permission be partially missing?

**Comment by jobisoft** [comment]
1. German translation is better. The sync stops. If you like, you can send a PR
2. This accounts for create, delete and mod rights. I did not want to create individual errors, so I went for this partial thing. But maybe one could simply write "no rights for the requested action"
