### ISSUE TITLE
Add support for webcal links

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/DAV-4-TbSync#12]
Hi,

I'm using a nextcloud server and I have a couple of ical subscriptions:
For that I
- log into nextcloud via the web frontend
- go to calendar
- click "New subscription"
- paste the link to an .ics file (e.g. from https://www.schulferien.org/deutschland/ical/)

This webcal subscription is then exported via nextcloud.

Unfortunately, TbSync does not see such (read-only) webcal links and only offers to add CalDAV calendars.
It would be great, if TbSync would support them as well.

**Comment by jobisoft** [comment]
I do not have a nextcloud server to test this. Can I have an account on your server wich has some of those ical subscriptions?

If you want to send credentials, send me an email.

Did not know about this, thanks for reporting.

**Comment by jobisoft** [comment]
added in 0.8.22

**Comment by mbiebl** [comment]
Just curious, when will that .xpi be available via https://addons.thunderbird.net/de/thunderbird/addon/dav-4-tbsync/ ?

**Comment by guillermin** [comment]
I also have iCal subscriptions in my NextCloud calendar and they are not appearing in the list of calendars in TbSync settings. I'm on version 1.24, so supposedly this should work according to this issue. Any ideas why it is not or what I can do to debug it?
