### ISSUE TITLE
Cannot establish a secure connection over HTTP://

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#121]
I set up account over insecure HTTP and set in DAV-4-TbSync to use insecure HTTP.  The server is milter.aegee.org, username is aaa@milter.aegee.org, password is abc .  At the time I setup this, the server speaks clear HTTP.  Then I tell the server to 301 forward all HTTP to HTTPs traffic, and go in DAV-4-TbSync. When I do account refresh, the event log shows:

Could not establish a secure connection.  Are you using a self-signed certificate...

URL
http://milter.aegee.org/.well-known/caldav (PROPFIND)

To the extend that the log does propfind on HTTP://, the error message cannot show UNKNOWN_SSL_ERROR.  It is not expected to get a certificate.

**Comment by jobisoft** [comment]
Looks like a regression after switching from the old network code to the new one (and probably related to the new code around actually storing 301 redirects). It does not happen in current stable. Looking into it.

**Comment by jobisoft** [comment]
I think I fixed it. Is it working for you in the latest beta?

**Comment by jobisoft** [comment]
Is this fixed i latest beta?

**Comment by jobisoft** [comment]
I just released a new beta. Can you verify and close this issue please?

**Comment by dilyanpalauzov** [comment]
I create a HTTP only account, aaa@milter.aegee.org . Then I tell the server to serve all the traffic under HTTPS and to send redirects from HTTP to HTTPS.  DAV-4-TbSync does follow what the server asks, but it does not update the CalDAV and CardDAV entry URLs in the account configuration.

Moreover the CUA asks the user to confirm the new destinations of the URLs.  The user shall not be asked for it, as the user has not entered them in the setup and if the server decides to change the URLs, I do not see what choice shall the use have.

Once the account is switched to HTTPS only, I tell the server to redirect all traffic to HTTP with 301.  Here, DAV-4-TbSync says SSL error.  I do not think there is SSL error. https://milter.aegee.org redirects to http://milter.aegee.org with 301+Location and fetchig http://milter.aegee.org/whatever cannot cause SSL error.  In the console I see the HTTPS calls and the 301 answer, but not the HTTP calls.

**Comment by jobisoft** [comment]
> I create a HTTP only account, aaa@milter.aegee.org . Then I tell the server to serve all the traffic under HTTPS and to send redirects from HTTP to HTTPS. DAV-4-TbSync does follow what the server asks, but it does not update the CalDAV and CardDAV entry URLs in the account configuration.

This will never happen, as we introduced the principal shortcut. So if TbSync has a principal to use, he will not connect to the main server urls, will not see the redirect and will not update it. The principal used is however updated (but not shown to the user).

I might add the principal used to the UI.

I hope I have fixed the other issue. TbSync should not ask you to  confirm the new URLs. I never actually implemented that, how did that look? Was it some sort of system message?

Happy testing and thanks for finding all of this.

**Comment by jobisoft** [comment]
Forgot to say: New Beta is out.

**Comment by jobisoft** [comment]
Same here. Latest beta now only stores/updates permanently redirected urls.

Would be happy if you could test it.

**Comment by dilyanpalauzov** [comment]
I set up over HTTPS the account aaa@milter.aegee.org . Then I tell the server to redirect all traffic from HTTPS to HTTP with 301.  Then I tell TbSync to synchronize the account.

TbSync calls PROPFIND HTTPS://milter.aegee.org/dav/principals/user/aaa@milter.aegee.org . The developer console shows under errors “MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING”.

Then I tell TbSync to synchronize once again the account and this time it works, without showing errors.

**Comment by dilyanpalauzov** [comment]
PS: After showing MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING, the console does not show any answer from the server.

**Comment by jobisoft** [comment]
In general we have to ask, how much time we want to spend on https -> http redirects, which are a security issue and not in the interest of the user. In general, I do not want my connection falling back from https to http without me getting a prompt. With Basic Auth, my password would be out in the open in clear text. 

If I have setup the connection via https, it should not be possible at all that TbSync is sending any unsecured requests.

Thinking about this, I will actually deny any such redirects in the next beta.

The original issue (of this issue) was a redirect from http to https. Is that working for you?

**Comment by dilyanpalauzov** [comment]
The use case for the HTTPS→HTTP transition is a CalDAV server offering anonymous access (either without username, or with “anonymous” as username and any password).  If the server is overloaded over HTTPS then redirectiong the traffic to HTTP is not a security issue (since the password is not secret).

Switching HTTP → HTTPS does work.

**Comment by jobisoft** [comment]
That is a corner case, which sort of eliminates itself: If you do not consider the data you send for anonymous access as important so it can be send via http, there is no need to send it over https in the first place, which will remove the need to redirect from https to http. If you DO want to send it over https - for whatever reason - falling back to http is not an option.

**Comment by dilyanpalauzov** [comment]
I described a use case, where switching HTTPS→HTTP makes sense.  It is not possible to foresee in the beginning, whether serving data over HTTPS will overload the server.

Such a logic in the client (no fallback to HTTP on 301 redierct) forces servers to stick to HTTP, even if they could (all the time) serve the same data over HTTPS.

**Comment by jobisoft** [comment]
Overload is not a reason to fallback to http!

**Comment by jobisoft** [comment]
Beta now rejects such redirects.
