### ISSUE TITLE
Feature Request: Add ability to create new calendars and addressbooks from within DAV-4-TbSync

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#123]
When new addressbooks are created, ask the user for displayname and addressbook-description properties.

When new calendars are created, ask the user for displayname, calendar-description, colour, default timezone, transparency and supported components.

**Comment by dilyanpalauzov** [comment]
When the user has several home-sets with write permission, ask the user in which homeset the new collection shall be created.  Ideally display the displayname of the home-set and not its address.

**Comment by dilyanpalauzov** [comment]
Add ability to delete collections on the server.

**Comment by jobisoft** [comment]
Not on my agenda.
