### ISSUE TITLE
Feature Request: Add editor for webdav properties

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#124]
For each addressbook discovered, where the user has the editing right on properties, let the user change the displayname and addressbook-description.

For each caeldnar discovered, where the user can edit the properties, let the user modify the displayname, calendar-description, colour, default timezone, transparency  properties and show to the user the supported components.

**Comment by dilyanpalauzov** [comment]
Add also ability to edit the properties of the principal-url: displayname, caldav:calendar-user-address-set and caldav:calendar-user-type.

**Comment by jobisoft** [comment]
Not on my agenda.
