### ISSUE TITLE
Feature Request: Integrate the WebDAV account in the email account

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#125]
The [Sieve addon for Thunderbird](https://addons.thunderbird.net/de/thunderbird/addon/sieve/), which is not yet ported to TB68, shows a separate line in the Email account registration and reuses its interface/windows.  A user finds then the smtp, imap and sieve settings on the same place.

Do the same for CalDAV/CardDAV.  For each email account, show a separate line on the left pane in the email registrations, saying WebDAV, and offer there to utilize webdav reusing the credentials for the email account,

As I do not use Exchange I cannot say if this makes sense to be implemented in TbSync.  For WebDAV it makes sense.

**Comment by jobisoft** [comment]
Anything related to the general account options dialog is postponed until TbSync has been integrated into Thunderbird.
