### ISSUE TITLE
Feature Request: Inject DAV-4-TbSync in the email account setup

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#126]
When an email account is set up in TB, the user has to enter its displayname, username and password and later to set up any aliases manually.

Inject DAV-4-TbSync in this process.  Hide the display name when asking for email address.  On entering emailaddress, obtain the display name of the current-user-principal for that email address and propose it as display name for the email account, if it is different from the email address and from the local part of the email address.

Obtain the CALDAV:calendar-user-address-set property of the principal and set that addresses as aliases for the email account.  Offer two-way synchronization between TB-mailaliases and the  CALDAV:calendar-user-address-set  property.

**Comment by jobisoft** [comment]
Not on my agenda.

The other way around is planed: If you setup an email account through the email setup wizard, it will check if caldav/carddav is avail as well and will set them up in Tbsync. But no ETA.
