### ISSUE TITLE
mark calendars without write permissions as read-only

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/DAV-4-TbSync#13]
For calendars which don't have a write permission (like the generated Contact Birthdays calendar in nextcloud), tbsync should set the read-only flag like in the attached picture.
This avoids accidentally adding or modifying events in this calendar which would only trigger an error.

![bildschirmfoto von 2018-09-17 08-31-26](https://user-images.githubusercontent.com/3609611/45608743-e104af80-ba54-11e8-8bdd-a262c274b401.png)

**Comment by mbiebl** [comment]
https://tools.ietf.org/html/rfc3744#section-3 has more background info on this topic

**Comment by mbiebl** [comment]
Running the following command:
```
curl -X PROPFIND -u john.bieling -H "Content-Type: text/xml" -H "Depth: 1" \
  --data '<?xml version="1.0" encoding="utf-8" ?><D:propfind xmlns:D="DAV:"><D:prop><D:current-user-privilege-set/></D:prop></D:propfind>' \
  https://$host/remote.php/dav/calendars/john.bieling/ | xmllint --format -
```
should give you an xml dump. The relevant part
```
  <d:response>
    <d:href>/remote.php/dav/calendars/john.bieling/contact_birthdays/</d:href>
    <d:propstat>
      <d:prop>
        <d:current-user-privilege-set>
          <d:privilege>
            <d:write-properties/>
          </d:privilege>
          <d:privilege>
            <d:read/>
          </d:privilege>
          <d:privilege>
            <d:read-acl/>
          </d:privilege>
          <d:privilege>
            <d:read-current-user-privilege-set/>
          </d:privilege>
          <d:privilege>
            <cal:read-free-busy/>
          </d:privilege>
        </d:current-user-privilege-set>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```
Notice how the write privilege is missing
```

**Comment by jobisoft** [comment]
is it sufficient to check for dav:read to know if it is readonly, and if that is not present, I can assume write access, or do I need to check for dav:write / dav:all ?

**Comment by mbiebl** [comment]
I *think* dav:read doesn't mean that the calendar is read-only, but that you have read permissions.
I *think* you should check for the absence of the write/all permissions instead.
At least this is how I read https://tools.ietf.org/html/rfc3744#section-3.1

**Comment by jobisoft** [comment]
roger. working on
https://github.com/jobisoft/DAV-4-TbSync/issues/57

which needs this issue fixed as well.

**Comment by jobisoft** [comment]
based on the found privileges, I would detirmine the access mode as follows:

all : RW
read + write : RW
read + write-content + bind + unbind : RW (write_properties is missing, but Tbsync does not need that for RW access)
read : RO

Mostly based on https://tools.ietf.org/html/rfc3744#section-3.12

Does that sound ok?

**Comment by jobisoft** [comment]
Released in current beta, please test and tell me what you think.
[tbsync.jobisoft.de](tbsync.jobisoft.de)

**Comment by jobisoft** [comment]
If you update, he might run into an error, because he has no acl information (yet), simply disable and re-enable the account.

**Comment by mbiebl** [comment]
Tried with the beta installer and a fresh TB account.
I get a "Service unavailable" failure:
```
URL:
https://biebl.mobi/remote.php/dav/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
```

**Comment by jobisoft** [comment]
https://github.com/jobisoft/DAV-4-TbSync/issues/41

**Comment by mbiebl** [comment]
Hm, seems I can reproduce the issue with a NC 13 instance, which is not supposed to be affected. Will report back once I know more.

**Comment by jobisoft** [comment]
Did it work by activating that cookie option? It works for me with your test server. Can I close this as fixed?

**Comment by mbiebl** [comment]
yupp, setting that cookie option helped. For some reason I thought NC 13 was not affected, and this was introduced in NC 14.
Thanks!
