### ISSUE TITLE
TBSync does not sync Reminders after uptdate on iOS13.1

### ISSUE THREAD

**Issue by MHoeller** [jobisoft/DAV-4-TbSync#139]
## Your environment

TbSync version: 1.7.0.2
Thunderbird version: 60.8.0

## Expected behavior
Sync of Reminders 

## Actual behavior
folders[unhandledFolders[t][i]] is undefined
dav.sync.folderList<@chrome://dav4tbsync/content/sync.js:267:17
TaskImpl_run@resource://gre/modules/Task.jsm:326:42

## Steps to reproduce
just sync 

I tried with thunderbird 68.* and updated the addons but the same result. I assume that the intrerface has changed

**Comment by jobisoft** [comment]
It looks like a WONTFIX, as Apple simply decoupled the old CalDAV Reminders calendar from the Reminders App.

It seems you may still use the Reminders CalDAV calendar with TbSync and sync stuff, which is actually still stored in the Calendar - but the Reminders App is not using that calendar anymore, but some other database.
