### ISSUE TITLE
Do not offer synchronization of collections, containing only VJOURNAL components

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#141]
A CalDAV collection can contain different types of resources: VEVENT, VJOURNAL, VTASK.  Since there is no support for memos (VJOURNAL) in Thunderbird, DAV-4-TbSync shall not offer syncronizations of collections that contain only VJOURNAL components.

In the account aaa@aegee.org (pw abc), there is such a collection: T5, and DAV-4-TbSync offers to synchronize it.

**Comment by jobisoft** [comment]
What request do have to make to see the collection type? Currently I do not seem to get that.

**Comment by dilyanpalauzov** [comment]
To obtain the components supported by a collection, one has to read the [CALDAV:supported-calendar-component-set](https://tools.ietf.org/html/rfc4791#section-5.2.3) property of the CalDAV collection.

The value of the property may change over time.

**Comment by meichthys** [comment]
This may be a little off-topic, but if we can read collection types, it would be helpful to only setup a tasklist/calendar if an associated calendar/tasklist does not exist on the server. Currently when setting up a DAV account in TBSync a tasklist and calendar are both created in TB regardless if there is an associated calendar/tasklist on the server.

**Comment by jobisoft** [comment]
Is this fixing it for you? (Thunderbird 102!)

TbSync 3.3: [TbSync-beta.zip](https://github.com/jobisoft/DAV-4-TbSync/files/9624999/TbSync-beta.zip)
Dav 2.4: [DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/9624996/DAV-4-TbSync.zip)

**Comment by dilyanpalauzov** [comment]
I think it is much more important to offer plugins for TB 102, rather than working on this.  I have now TB 102.  Once the switch for TBSync/DAV-4-TBSync to TB 102 is over, I can test.

In any case this can be tested with: username aaa@bapha.be , secret abc , server k.bapha.be  (or just baphe.be but it will not return 401 when no username is provided).  The CUA shall detects the CalDAV collections.  This one https://bapha.be/dav/calendars/user/aaa@bapha.be/a8fd634e-68cd-4bda-bf5a-02998939448c contains events, tasks and journals.

**Comment by jobisoft** [comment]
@dilyanpalauzov : The version I posted are for TB102.

**Comment by jobisoft** [comment]
Ok, closing this.
