### ISSUE TITLE
Instead of throwing [415]: Continue syncing after a single contact violated the standard

### ISSUE THREAD

**Issue by blausand** [jobisoft/DAV-4-TbSync#146]
## Your environment

TbSync version: 1.7.0.2
DAV-4-TbSync version: 0.15.0.2
Thunderbird version: 60.9.0 (32bit)

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When a VCARD doesn't comply with the standard, i get a warning, but the rest of the synchronisation will process fine.
When a VCARD doesn't comply with the standard, and the DAV-4-TbSync fails to process that single contact, i get an error, but the rest of the synchronisation will process fine.
## Actual behavior
The non-conform co-existance of Sabre- and ownCloud-Tags in PRODID RUINS the whole workflow, *********!

BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:2.1
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.5.0//EN
(…)
 <s:message>Validation error in vCard: PRODID MUST NOT appear more than once in a VCARD component</s:message>

## Steps to reproduce
I don't know whether Sabre came after ownCloud or vice versa, i even don't know if ownCloud just has Sabre inside. All i know is at the moment the Addressbook lives on my ownCloud server.

I think there should be at least a means to EDIT the problematic line out of this ********* world.

**Comment by jobisoft** [comment]
Can I have access to such an address book to reproduce that here?

**Comment by jobisoft** [comment]
By the way, you can export your address book from your owncloud web interface, manipulate the exported file and import it into a new address book (via web interface).

**Comment by blausand** [comment]
Ok mine has >600 contacts.
I know there are ways to waste a sunday. but in the end, i'm trying to convince the people out there to cut it with Google and Co. If i had all of them on the phone teaching workarouonds, we're getting exactly nowhere. This really great initiative of yours has to receive some energy, man :)

**Comment by blausand** [comment]
** WAIT OH WOW. Editing a contact seems to heal it. This time, the error occurred withiin a nother contact **
So here's the complete blackened contact that causes the error now.
Just add a nother one after it to see it won't be synchronized.

Request:
BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:2.1
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.5.0//EN
N:****;Michael;;;
FN:Michael ****
TEL;TYPE=HOME;TYPE=VOICE:022125******
TEL;TYPE=CELL;TYPE=VOICE:+49 177 8*****
TEL;TYPE=PAGER:+49 177 8******
EMAIL;TYPE=PREF;TYPE=INTERNET:michael****@gmx.de
EMAIL;TYPE=INTERNET:info@michael********.de
BDAY:1979-03-**
UID:e9ebce38-81be-47db-825b-36fe57f57db6
REV:2016-06-30T00:58:53+00:00
CATEGORIES:JazzEinladung
END:VCARD

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
  <s:message>Validation error in vCard: PRODID MUST NOT appear more than once in a VCARD component</s:message>
</d:error>

**Comment by jobisoft** [comment]
What I meant with access: credentials to your server. I usually do not create test environments myself (because I have no time) - and those contacts look invalid (multiple different version tags) - which makes this a non standard request.

Can you create a test environment for me, so I can simply connect to your server and reproduce the issue, so I can fix it, without spending time on actually creating such faulty contacts?

**Comment by blausand** [comment]
I edited all the contacts in the abook-4.mab in my profile folder.
unless...
Now the TbSync error log complains about some component using quoted printable in the note field:
<s:message>Validation error in vCard: ENCODING=QUOTED-PRINTABLE is not valid for this document type.</s:message>
This is the case for so many contacts, and i will not string operate this out just to find out that all my notes are corrupted afterwards.

**Comment by jobisoft** [comment]
To be precise: It is not TbSync who is complaining. It is your server. Your server send those corrupt contacts (vCards) and rejects them, when TbSync wants to sync local changes back to your server.

Your server is not eating the soup it is serving.

At least this is what I can derive from what you have posted so far.

A golden rule in CardDAV communication is: Do not alter users data. So I store the entire vCard I got from your server and just change/merge the field that has been changed locally.

Now as I said before, I can only help, if I get access to your server to an address book which shows that behavior.

There is still a chance that TbSync is doing something wrong, but is is hard to tell without access.

**Comment by blausand** [comment]
Yeah, at some point i replaced my old NAS running DAViCal with a fanless linux machine running owncloud's sabre. It never seemed to be a major problem for some years now, tough - until i changed from the SoGo connector to your favorable solution.
I've decided to risk it and just replaced ;ENCODING=QUOTED-PRINTABLE" by "" in my abook.mab and could run through a final sync before the mandatory deactivation for upgrading to TB68.
The web interface of owncloud is a design catastrophy as it wouldn't allow for a'books filtered in/out and would display "no contacts" before the WHOLE addressbook has been downloaded as part of the HTML page /o\.
(Just restoring AddOns, i recall my decision to delay my upgrade until at least /half/ of the important AddOns would be available.)

**Comment by jobisoft** [comment]
Uff, I really hope, everything will work. Please try to get a true vCard export/backup from your server.

What is so strange, is that your contacts have version 3 and version 2 headers. Which means it is a gamble how your server is interpreting your data, which I think is the core to this issue.
