### ISSUE TITLE
Add xpi to GitHub release

### ISSUE THREAD

**Issue by cfoellmann** [jobisoft/DAV-4-TbSync#147]
I just tried for the first time to use TbSync + this extension here.
Problem is/was that in the addons directory the DAV-4-TbSync version is 1.3 which did get installed but was not registered by the current TbSync install.

I did know that xpi is just a zip so I created my own installer to get to 1.4 but you could add the xpi file to the GitHub release.

**Comment by jobisoft** [comment]
You hit a bad timing. I just uploaded the latest versions to ATN and they are still pending review. These pending versions are indeed not compatible with the current versions, as they use a newer API version.

You can either use the beta versions (where you always get the latest version) or use the ATN versions. I do not support Manually building Xpi from source. 

Does that answer your question?

**Comment by jobisoft** [comment]
Or did ATN serve any of the pending versions already, which would be a bug? What versions do you have now?

**Comment by cfoellmann** [comment]
Yes, bad timing indeed.

TbSync was 2.5 and DAV-4-TbSync was only 1.3
Plus your beta channel was at 1.3.27 which didnt work either.

**Comment by jobisoft** [comment]
TbSync 2.5 is a bug, should not have been avail.

You need 
- TbSync 2.4 + DAV 1.3 from ATN
- TbSync + DAV from the beta channel

TbSync 2.5 + DAV 1.4 will be avail from ATN in a few days, but if you install 2.4 + 1.3, they will auto update.

Sorry for your inconvenience.

**Comment by cfoellmann** [comment]
Not your fault.
I am not using it myself. I have some customers I have set up with a combination of bad addons that just stopped working with Thunderbird 68.

I now have a working version TbSync 2.5 + DAV 1.4 on my test install.
I will test 2.4 + 1.3 and see.

Isn't 2.4 auto updating to 2.5?

**Comment by jobisoft** [comment]
The new versions have hit ATN.

2.4 will autoupdate to 2.5

I have a new procedure to prevent such missshaps in the future.

**Comment by cfoellmann** [comment]
thx
