### ISSUE TITLE
Contacts from TbSync marked as "Plain Text preferred"

### ISSUE THREAD

**Issue by FaBay89** [jobisoft/DAV-4-TbSync#148]
Nextcloud - Version: 16.0.1.1
Thunderbird - Version: 68.1.1
Provider für CalDAV & CardDAV - Version 1.4
TbSync - Version 2.5

## Expected behavior
Default setting in Contact is "unknown" for setting
"Prefers to receive messages formatted as"

## Actual behavior
Default setting in Contact is "plain text" for setting
"Prefers to receive messages formatted as"

Problem that follows: Every email to adress thats in contacts will be sent in plain text instead of HTML.

Maybe a TB issue, but not relevant in TB because TB saves the field correctly if you save a contact from frontend.

## Steps to reproduce
Add Nextcloud and sync Contacts

**Comment by FaBay89** [comment]
Duplicate of #43 
Maybe TbSync could provide a workaround for people coming from sogo connector?

**Comment by jobisoft** [comment]
I do not see how Tbync could fix that, as it is in your data/server. Maybe you eed to do what is described here:
https://github.com/jobisoft/DAV-4-TbSync/issues/43#issuecomment-443416490

**Comment by FaBay89** [comment]
Not so easy because the data is saved in blobs. The workaround in tbsync could be a checkbox in options (similar to the Contact Group workaround): if checked, delete this line in vcard data.
I think with TB 68 there will be more people coming from sogo to tbsync. And with good reason, tbsync is awesome :D 👍 

Here is how we fixed it: 
1. go to nextcloud - contacts - export contacts
2. open file with editor and replace lines "X-MOZILLA-HTML: FALSE" with nothing
3. delete all contacts in nextcloud
4. import file

**Comment by actdiux** [comment]
Thanks people - found this 4th July 2022
> 
> Here is how we fixed it:
> 
>     1. go to nextcloud - contacts - export contacts
> 
>     2. open file with editor and replace lines "X-MOZILLA-HTML: FALSE" with nothing
> 
>     3. delete all contacts in nextcloud
> 
>     4. import file

Adding on 

In Thunderbird I also had to uncheck the Contacts in TbSync .. let it sync - so it effectively clears out the bad contacts, and then check and sync again. If I only did the steps in Nextcloud and resync in TB, it did not fix _the every one gets text only email_ problem with my contacts in Thunderbird.
