### ISSUE TITLE
no endpoints detected

### ISSUE THREAD

**Issue by bjo81** [jobisoft/DAV-4-TbSync#149]
## Your environment

TbSync version: 2.4.19
DAV-4-TbSync version: 1.3.27
Thunderbird version: 68.1.2

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Actual behavior
No endpoints are found, no connection is logged by the webserver. Event Log shows only something related to timezone of the EAS-Adapter

## Steps to reproduce
Try to add a Nextcoud Instance (which worked before).

**Comment by jobisoft** [comment]
what is the url you are using?

**Comment by bjo81** [comment]
Just cloud.mydomain.org, according to the debug log it's translated to "https://cloud.mydomain.org/.well-known/carddav" which works in e.g. Firefox.

**Comment by jobisoft** [comment]
can i have a test account on your server? credentials via email.

**Comment by bjo81** [comment]
Sure, credentials sent.

**Comment by dilyanpalauzov** [comment]
For WebDAV `curl -XPROPFIND https://cloud.mydomain.org/.well-known/carddav` must return a 301 redirect.

Firefox calls the HTTP GET method, so it is irrelevant if it works with it.

**Comment by jobisoft** [comment]
I was able to get it to work with the test account on his server he send me, so at the moment I do not know, why it does not work for him. Maybe an update issue with the removed https setting...

@bjo81 : Did setting up the account anew help?

**Comment by bjo81** [comment]
Using a clean profile helped, no idea why it's broken in the current profile. Configuring manual endpoints fails in the profile, too.

**Comment by jobisoft** [comment]
Sorry to hear that. I used automatic configuration and it woked like a charm. That doesn't work for you?

**Comment by jobisoft** [comment]
Can I close this?

**Comment by bjo81** [comment]
yep.
