### ISSUE TITLE
Alternative methods to retrieve shared resources

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/DAV-4-TbSync#150]
@dilyanpalauzov : May I ask for your advice here?

I know you somewhere said something about different methods to retrieve shared resources and that TbSync is not doing any of the methods you suggested, but I no longer find it.

TbSync is currently discovering shared resources by asking for `group-membership` as outlined here: https://github.com/jobisoft/DAV-4-TbSync/issues/75#issuecomment-462689386

But that seems not to work with SOGo, as I get a 403 if I want to access the returned principals.

Could you advice, what other methods are available to get access to shared resources and what TbSync should implement? Valid for both CalDAV and CardDAV?

**Comment by dilyanpalauzov** [comment]
The discussion is at https://github.com/jobisoft/DAV-4-TbSync/issues/127#issuecomment-535884682 .

* Use DAV:princapal-property-search to discover the home-sets of anothe user
* Use  WebDAV notifications: https://evertpot.com/webdav-caldav-carddav-sharing/

If principals A and B belong to the same group, then collection B/C has not to be shared by B with A, even if collection B/D is shared with A.

403 means likely that the requester can determine if another user exists, but may not read its data. (Or broken server implementation, this is very abstractly presented symptom).

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.
