### ISSUE TITLE
Add support for HomeAddress2 field

### ISSUE THREAD

**Issue by IBBoard** [jobisoft/DAV-4-TbSync#151]
## Your environment

TbSync version: 2.5
DAV-4-TbSync version: 1.4
Thunderbird version: 68.1.0

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Syncing multi-line addresses syncs down the entire address from NextCloud (both "Address" and "Extended Address" lines, as well as county and postcode, etc). This matches the second (unlabelled) address line in normal Thunderbird address books.

![Default Thunderbird contacts (unsynced)](https://user-images.githubusercontent.com/388582/66717963-713b3280-edd6-11e9-85df-c4b71318ef11.png)
(Editing a "normal" address entry)

## Actual behavior
Sync only retrieves [first line (Address) and county/postcode/etc](https://github.com/jobisoft/DAV-4-TbSync/blob/d7654fe92215c444aa17aab6f0c4630e91557b97/content/includes/tools.js#L473-L477)

![Synced contacts](https://user-images.githubusercontent.com/388582/66717973-7e582180-edd6-11e9-93ab-50c2f532797a.png)
(Editing a synced address entry)

## Steps to reproduce

1. Add an address book entry that uses the additional line of address (what the [Thunderbird API](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIAbCard) appears to call "homeAddress2" and "workAddress2"), e.g.
    * House name/apartment:
        * Address: Holly Cottage
        * Extended address: 42 Some Street
        * City: My Town
        * State or province: My County
        * Postcode: AB1 23CD
    * Village and town:
        * Address: 42 Some Street
        * Extended address: My Village
        * City: Nearby Town
        * State or province: My County
        * Postcode: EF1 23GH
1. Sync the address book
1. View or edit the address
1. Check for second line of address - "village or town" will miss "My Village", "House name/apartment" will miss street name and house number.

**Comment by jobisoft** [comment]
Thanks for reporting this. Probably fixed in latest beta.
https://tbsync.jobisoft.de

Before installing beta, disable all your tbsync accounts and re-enable them after all beta modules have been installed.

**Comment by IBBoard** [comment]
That seems to work for me. It pulls down the extra field on first sync and populates it, and I've edited and checked that it shows on the server after an update-sync (edit in TbSync, view in NextCloud).

Thanks.

**Comment by jobisoft** [comment]
Perfect. Will land in stable soon. But I suggest to stay on beta.
