### ISSUE TITLE
Simplify account setup

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#160]
To make the account setup easier, in the server field write „https://* so that the user does not have to type this, and handle “http://”, “https://” (case insensitive) and empty server field in the same way

To make the accont setup easier, once the user enters username and password and completes the account setup, DAV-4-TbSync shall:
* obtain the collections from the server
* obtain the content of the collections

without requiring further interaction from the user.  There is no point to ask the user to explictly request synchronization of the collections and their content, since DAV-4-TbSync knows that the user wants to synchronize them eventually and requiring that explicit steps complicates the usage.

**Comment by jobisoft** [comment]
The user does not have to write http://, it is the default if not given.

I want the user to be able to edit the options before connecting. I will not autoconnect.

**Comment by dilyanpalauzov** [comment]
The user has to write http://, as the user does not know that this is the default.  The default shall be https:// anyway.

What option can the user edit before connecting and how much per cent of the users approximately edit the options before the first connect?

**Comment by jobisoft** [comment]
Sorry, the default is https://.

Options are on the options page.

**Comment by dilyanpalauzov** [comment]
Users do not know that there is a default and therefore have to type manually `https://`, unless it is already present in the field, when the dialog is opened.

Apperently, proprietary protocols and implementations manage to require less configuration overhead during the setup, compared to open source software like Thunderbird/DAV4-TbSync.  The increased overhead unfortunately reduces the willingness to accept or deploy at scale IETF protocols or open source software.  This gives benefits to proprietary software.

What I am asking for is to assume some reasonable default (store offline calendar entries and take any option for the contact groups) and perform the synchronization automatically.  Understanding the handling of contact groups is very complicated matter to explain at scale for large amount of users, so users just do not put any efforts in understanding it.  Asking users to read TB bugs is also too much.  It is also not clear in advance if (e.g. for read only data) the user will have ever to deal with contact groups, so enforcing a decision on how contact groups shall be handled, is too much.

All in all, this additional confirmation adds always administrative burden, gives advantages to proprietary software, and the difference in the behaviour is just nuances.

**Comment by jobisoft** [comment]
I cannot make it nice for everybody and that is why I leave it as it is. With your help we have reduced the overhead alot and setup is now really easy. No standard user is typing https or http, they do not know any of that stuff. A server address is mostly "my.server.com" for the usual user. And if they do *think* they have to add https then they can do that. 

The groups option was once hidden in a system pref and (advanced) users complained that it would be better to have it in the gui. That is why it is there. I will not remove it again. It is not my fault that we actually need that option.

Also, the entire gui is probably going away, so I will not spend and more time on it.

**Comment by dilyanpalauzov** [comment]
I do not say that the setting for Groups shall be hidden, I ask for not forcing the users to decide on it before completing the configuration.  The rationale is that most users cannot decide on it, so it makes no sense to force them take any decision, before making progress.

How will this decision be made, once the entire GUI disappears?

**Comment by jobisoft** [comment]
> How will this decision be made, once the entire GUI disappears?

I have no idea. I hope the option wil not be needed anymore by then.

**Comment by dilyanpalauzov** [comment]
I sum up the discussion: the users have currently to choose options, which they might not understand, in order to complete the setup.  This is intentional and therefore will not be changed.  But in the future, this decisions will probably not be needed (for some reasons) and will therefore users will not have to do it.

**Comment by jobisoft** [comment]
Don‘t make this bigger as it is please. The setup process is completed but the user may alter the default configuration before connecting to the server.

I hope the option is no longer needed because the underlying issue in Thunderbird gets fixed someday.
