### ISSUE TITLE
XML: switch from xmlns:d="DAV:" to xmlns='DAV:'

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#161]
For the sake of minimizing network triffic, use :DAV as default namespace in xml.

So `<d:propfind xmlns:d="DAV:">` changes to `<propfind xmlns='DAV:'>` and all other `d:` prefixes disappear.

**Comment by jobisoft** [comment]
I will not do that. It will req changes in millions of places and I will probably mess this up and break the addon.
