### ISSUE TITLE
HTTP 500 error after upgrading to Owncloud 10.3

### ISSUE THREAD

**Issue by thomaslschmidt** [jobisoft/DAV-4-TbSync#162]
## Your environment

TbSync version: 2.5
DAV-4-TbSync version: 1.4
Thunderbird version: 68.1.2

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TbSync used to sync with CalDav calendar hosted on owncloud server.

## Actual behavior
Upon synchronization, TbSync reports an HTTP 500 error with error message:

URL:
https://(....)/remote.php/dav/principals/users/thomas/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><cs:calendar-proxy-write-for /><cs:calendar-proxy-read-for /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>TypeError</s:exception>
  <s:message>explode() expects parameter 2 to be string, null given</s:message>
</d:error>

## Steps to reproduce
Sync worked fine until upgrade to owncloud 10.3. However, the issue might be due to TbSync because both my Outlook-Plugin as well as my Android app still sync correctly with the new owncloud version.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
**explode() expects parameter 2 to be string, null given**

that is clearly an error in your server. It might be that TbSync is doing different requests, so it triggers that error, while outlook is not.

But the error reported is an error in your server.

Please file a bug there.
