### ISSUE TITLE
Carddav with owncloud 10.3 is not working

### ISSUE THREAD

**Issue by FKBOX** [jobisoft/DAV-4-TbSync#164]
Win7

TbSync version: 2.6
DAV-4-TbSync version:
extesion provider_fur_caldav_carddav-1.5-tb.xpi
Thunderbird version: 68.2.0 (32-Bit)
worked fine before, I don't really know, may be since owncloud 10.3 I got those fault:

URL:
https://server.de/owncloud/remote.php/dav/addressbooks/users/Tom/friends (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>TypeError</s:exception>
  <s:message>explode() expects parameter 2 to be string, null given</s:message>
</d:error>

no debug log!? I tried but record is empty!

**Comment by jobisoft** [comment]
same as #162 

please file a bug at owncloud.

**Comment by FKBOX** [comment]
Hello!

Owncloud community does not care those bugs!

Kind Regards 
Frank

**Comment by FKBOX** [comment]
Caldavsyncronizer for outlook, ios, davdroid have no problems with ownCloud 10.3!


Kind Regard
Frank

**Comment by jobisoft** [comment]
But I am not sending an invalid request. The request triggers a php error (or something) because they use the explode() method with wrong parameters.

I cannot fix this. Standards are standards for a reason: interoperability.

What do you expect me to do?

**Comment by FKBOX** [comment]
Hello! 

I expect nothing. The question for me was, why do the other apps get data?!
Post it to owncloud community is for the trash can. The developers tell always this addons are not a basic part of owncloud, and the rest of members is only jabber!

I don’t know how to get to the developers of calender and contacts app.
So I wait for future. I need the synchroniser and I don’t want to use outlook!

Best Regards 
Frank

Von meinem iPad gesendet

**Comment by Selvatik77** [comment]
Hello,
i only applied the first change and it worked fine for me.
Thanks

**Comment by FKBOX** [comment]
Problem solved on owncloud 10.3.0 and it returned with update to 10.3.1?!

**Comment by jobisoft** [comment]
Sorry to hear that. Re-apply the fix and make some noise at owncloud?

**Comment by FKBOX** [comment]
Problem solved:
gksudo gedit /var/www/owncloud/lib/composer/sabre/dav/lib/CardDAV/Plugin.php
Ctrl-F list($part) = explode(';', $contentType);
Change to:
list($part) = explode(';', $contentType ?: '');
save
and it works - Thanks to the person on github who find out!

**Comment by ecgcoop** [comment]
Hi.
I´m using Nextcloud 17.0.0, Thunderbird 68.2.2, TbSync 2.7 and Provider for CalDAV & CardDAV 1.5.
After changing (in Thunderbird adanced config editor) "network.cookie.same-site.enable" to false, I can initialy connect to my Nextcloud contacts but, when I close Thunderbird and try to sync again I receive a "HttpRequest: Invalid URL <https://drive.redpes.pt/remote.php/dav/principals/users/#####/>" (the "#####" is my Nextcloud username) error...
Could be the same error reported here? I can´t find the above mencioned "Plugin.php" file in my instance.
Thanks,
Manuel

**Comment by jobisoft** [comment]
hi @ecgcoop This issue is an ownloud issue, not a nextcloud and @FKBOX has presented a solution already. 

Please file a new issue. However: Please do not use "network.cookie.same-site.enable" with TB68. It is not needed.
