### ISSUE TITLE
Access to "additional" google calendars

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/DAV-4-TbSync#169]
TbSync now supports Google Calendars and Addressbooks. 

However, it can only see the calendars, which are selected for sync, which can be managed here:
https://calendar.google.com/calendar/syncselect

**Comment by franz-xaver-hallhuber** [comment]
Make sure to be logged in ONLY with the Google account in question, as the interface does not let you switch between several accounts.

**Comment by jhhcs** [comment]
Hey there, I am not quite sure what the _"solution inside"_ label means; is there a workaround or even a solution for this issue? Cheers!

**Comment by jobisoft** [comment]
It means, that the solution to this issue is explained in this issue. First post.

**Comment by jhhcs** [comment]
Thank you for explaining this so patiently. I came from #364 and must have switched off my brain right after.

**Comment by oliver303** [comment]
Maybe, you should explain the solution in the wiki, so anybody can solve this issue with shared calendars more quickly.
