### ISSUE TITLE
Yahoo carddav is not working

### ISSUE THREAD

**Issue by monperrus** [jobisoft/DAV-4-TbSync#17]
I'm trying to to connect Yahoo's carddav at <https://carddav.address.yahoo.com/dav/>.

FYI, this gives an error `AbortError`.

**Comment by jobisoft** [comment]
The AbortError bug has been fixed in the latest release:
https://github.com/jobisoft/DAV-4-TbSync/releases/download/v0.8/DAV-4-TbSync.xpi

However I think it will still not work with Yahoo, because they do their own stuff and do not follow the sabre/dav spec. Can you give it a try?

**Comment by monperrus** [comment]
Yahoo works with the latest release! Thanks a lot.

**Comment by monperrus** [comment]
Yahoo Carddav does not work anymore with the latest release 0.8.30.

It keeps asking for the password.

**Comment by jobisoft** [comment]
Version 0.8.30 exists in multiple versions (my bad). Can you please try this one:
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

And restart Thunderbird afterwards. Still bad?

**Comment by monperrus** [comment]
Thanks for your fast answer.

Reinstalled, restarted. Still not working.

**Comment by jobisoft** [comment]
Can I have a debug log of a failed attempt? Can I apply for a yahoo account for free?



Am 18.11.18 um 16:14 schrieb Martin Monperrus

**Comment by monperrus** [comment]
> Can I apply for a yahoo account for free?

Yes! It will be easier for you to debug. The cardav URL is https://carddav.address.yahoo.com/dav/

**Comment by jobisoft** [comment]
Can you please check, that you can still log on with the last official version? 0.8.29?
https://addons.thunderbird.net/thunderbird/downloads/latest/dav-4-tbsync/addon-986258-latest.xpi

My fresh account does not work with 0.8.29 and
https://carddav.address.yahoo.com/dav/

Can you tell me, with which version it does work?
https://addons.thunderbird.net/de/thunderbird/addon/dav-4-tbsync/versions/

**Comment by jobisoft** [comment]
This is all very strange. I followed these instructions:
https://www.davdroid.com/tested-with/yahoo-mail/

- I simplified my password (no special chars)
- I enabled that option "Allow apps that use less secure sign in" (to allow Basic Auth and not only OAuth)
- I connected to caldav.calendar.yahoo.com/dav which worked with 0.8.30 and gave me my calendar

I was not able to my contacts by connecting to 
- https://carddav.calendar.yahoo.com/dav/ (from above URL)
- https://carddav.address.yahoo.com/dav/ (from you)

Did not work with .29 or with .30.

Furthermore the above URL states, CardDAV has been dropped?

**Comment by monperrus** [comment]
> https://www.davdroid.com/tested-with/yahoo-mail/

The URL is this doc is broken and the info is inaccurate: CardDav is still supported.

I was able to connect to carddav.address.yahoo.com/dav up to a couple of days (I don't have the exact date when it stopped working, maybe for .29). It still work with another client.

**Comment by monperrus** [comment]
> Can you please check, that you can still log on with the last official version? 0.8.29?
With this version, TB does not ask for a password but the error in the UI is "status.400"

**Comment by jobisoft** [comment]
OK, retry (0.8.31)
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

For the URL it worked for me with just "carddav.address.yahoo.com".

**Comment by jobisoft** [comment]
v0.9 is out

**Comment by monperrus** [comment]
Thanks for your progress.

Does not work here with TbSync 0.7.20 + DAV 0.8.33


Where can I download 0.9?

**Comment by monperrus** [comment]
Here it is:
```
** Mon Nov 19 2018 19:41:08 GMT+0100 (CET) **
[setSyncState] : State: send.getfolders, Account: yahoo

** Mon Nov 19 2018 19:41:08 GMT+0100 (CET) **
[URL] : https://carddav.address.yahoo.com/dav

** Mon Nov 19 2018 19:41:08 GMT+0100 (CET) **
[HEADERS] : {"Depth":"0","Prefer":"return-minimal"}

** Mon Nov 19 2018 19:41:08 GMT+0100 (CET) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

** Mon Nov 19 2018 19:41:09 GMT+0100 (CET) **
[RESPONSE] : 401 : <?xml version="1.0" encoding="UTF-8" standalone="yes"?><yahoo:error xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xml:lang="en-US" yahoo:uri="http://yahoo.com"><yahoo:description>Not Authorized - Either YT cookies or a valid OAuth token must be passed for authorization</yahoo:description><yahoo:detail>Not Authorized - Either YT cookies or a valid OAuth token must be passed for authorization</yahoo:detail></yahoo:error>

** Mon Nov 19 2018 19:41:09 GMT+0100 (CET) **
[setSyncState] : State: accountdone, Account: yahoo

```

Seems like Yahoo does not accept basic auth for me. ("Allow apps that use less secure sign in" is on, I've double-checked.)

**Comment by jobisoft** [comment]
There is one last thing we have to check: Is Thunderbird actually authenticating your request. For that you have to open the error console.

    Tools -> Developer Tools -> Error Console

And there activate all "Net" options:

![image](https://user-images.githubusercontent.com/5830621/48731265-f658ae80-ec3c-11e8-9360-900d3bace6c5.png)

 With the console being open, retry the sync and you should see the console being populated with entries like this:

![image](https://user-images.githubusercontent.com/5830621/48731417-4172c180-ec3d-11e8-9976-ed65677ed1ee.png)

Open these entries (for example the 401 ones) and check the request headers for an Authorization entry. 

![image](https://user-images.githubusercontent.com/5830621/48731704-f86f3d00-ec3d-11e8-9660-79a6b09a44d0.png)

Is there a BASIC one? DO NOT POST THAT HERE (your password can be recovered from the BASIC string)

**Comment by monperrus** [comment]
It works on a fresh profile... There is some bad state somewhere in `.thunderbird`. I'll try to find where.

**Comment by monperrus** [comment]
Removed extensions and folder TbSync, but kept the whole profile. Reinstalled extensions, reconfigured TbSync.

It works again! Thanks :+1:

**Comment by jobisoft** [comment]
If you run into this again, I released a new beta, which has more debug output regarding the authentication process and also has a special Yahoo fix (Yahoo is not announcing that it supports BASIC auth, it is not sending a WWW-Authentication header at all).

https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi
(that link always points to the latest beta...)

**Comment by jobisoft** [comment]
I released a new beta:
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

This has special handling for icloud, yahoo and gmx. Would you give it a try? Remove all your yahoo accounts in Tbsync and create a new one with the latest beta. Just use "yahoo.com" as server url.

I would like to improve how users can setup their accounts from service providers (icloud, gmx, yahoo, posteo, mailbox, ...) so that they just select their provider with out having to enter any url at all. Would you help me by discussing a few ideas?

**Comment by monperrus** [comment]
> This has special handling for icloud, yahoo and gmx. Would you give it a try? Remove all your
> yahoo accounts in Tbsync and create a new one with the latest beta. Just use "yahoo.com" as server
> url.
Just did it. It works for me with only writing 'yahoo.com' in server url.

**Comment by monperrus** [comment]
> Would you help me by discussing a few ideas?
Of course. Let's move it to a dedicated issue?

**Comment by jobisoft** [comment]
And you get both: calendars and contacts in a single account? This should not have been possible before, right?

**Comment by jobisoft** [comment]
@monperrus : I just retried Yahoo and I learned that I now have to create an app specific password for TbSync in Yahoo to be able to cont. to use Yahoo with TbSync. Do not know, if this is news for you.

**Comment by monperrus** [comment]
Thanks for the update.
