### ISSUE TITLE
Feature Request: configurable names for calendar/addressbooks

### ISSUE THREAD

**Issue by yabow** [jobisoft/DAV-4-TbSync#170]
Hi.
It would be very helpful if there were the possibility to change the generic names of the calendars or address books. For example, when working with group shares in nextcloud, confusing names like "Account(Calendar(Group))" are created. If you could influence this name it would be very helpful.
Otherwise the renaming works of course, which can become very time-consuming with a large number of calendars and/or users/installations.

Very good software. I appreciate this work very much.

**Comment by jobisoft** [comment]
You can simply rename them in Lightning or in the Thunderbird Addressbook (not in the TbSync UI though)

**Comment by jobisoft** [comment]
oh, you know that already. I did not read the second part. How would you like the default names to be constructed?

**Comment by yabow** [comment]
Is it not possible to reformat the default name with regular expressions? So that I can always define "calendarname" as name out of the default string "account(calendarname(group))?" 

Maybe this can also be done automatically afterwards. Unfortunately I can't.

**Comment by jobisoft** [comment]
First of all the (group) name you refer to is not added by me. The current formatting is

`%account_name% (%calendar_name%)`

If the calendar name (as stored on your server) includes a group name, that this will be part of %calendarname% and I will not be able to split that up.

Would a feature, where the above format string would be editable in a thunderbird pref still be helpful? I would need funding to cover like 1h of work.

**Comment by yabow** [comment]
Yes, the (group) comes directly from nextcloud, I find already annoying...

Yes, a small script or addon would also help me at this point. So that I can automatically adjust the calendar names over the whole Thunderbird profile.

How much funding is needed for one hour of work?

**Comment by jobisoft** [comment]
50 EUR would be nice, for 100 EUR I would try to add support for regular expressions, so you could get rid of that group thing.

**Comment by dilyanpalauzov** [comment]
Why not edit the dav:displayname once (name of the calendar/ab delivered by WebDAV) and then anytime any client obtains the collection, the displayed name will be the same?  Some webdav software allows different names per user, whiile the administrator sets the inittial name.  So effecttively I think it will be best, if forany coollection the name is set once over webdav (which is unavoidaable) and then all user agents usee this information.
