### ISSUE TITLE
@ vs %40 in the URLs

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#177]
When I setup a CalDAV account for host milter.aegee.org Thunderbird calls:

PROPFIND https://milter.aegee.org/dav/calendars/user/aaa@milter.aegee.org/901652d4-101e-4357-980b-c0b315a15014/ asking for <d:propfind xmlns:d="DAV:"><d:prop><d:resourcetype /><d:displayname /></d:prop></d:propfind>

and then

PROPFIND https://milter.aegee.org/dav/calendars/user/aaa%40milter.aegee.org/901652d4-101e-4357-980b-c0b315a15014/ asking for <D:propfind xmlns:D="DAV:" xmlns:CS="http://calendarserver.org/ns/" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:resourcetype/><D:owner/><D:current-user-principal/><D:supported-report-set/><C:supported-calendar-component-set/><CS:getctag/></D:prop></D:propfind>

Why does the first PROPFIND  use aaa@milter, and the second uses aaa%40milter in the URL?

Both requests obtain the resourcetype.  Why is not resourcetype requested only once?  Why are both requests not compressed into one?

**Comment by jobisoft** [comment]
I guess the first one is a request to your carddav server and the second one to your caldav server. Maybe they actually returned differntl urls during discovery. You might learn this by inspecting the log.

TbSync is treating these two (CalDAV & CardDAV) individually to get the addressbooks and calendars. I do not have the resources to change that behaviour.

**Comment by dilyanpalauzov** [comment]
Both URLs are about  CalDAV collection, so no CardDAV here.  I do not see anything relevant in the logs, I checked them before writing here.

**Comment by jobisoft** [comment]
Found it, both requests are generated in different parts of the code. The first call is independent (and unauthenticated) of any actual sync, it is a dump request to your server during the create calendar function to get a 401 response from which I can extract the Auth Realm, which I need to pre-add the password to the password manager so that lightning will not ask again (lightning stores a password per calendar, not per account).

Stupid as hell, but I have to do it.

**Comment by dilyanpalauzov** [comment]
Why for CardDAV both requests use @ in the URL, but for CalDAV one request has %40, while the other uses @?

**Comment by dilyanpalauzov** [comment]
As far as I remember the standards, @ and %40 are not the same and the server can handle them differently.

**Comment by dilyanpalauzov** [comment]
The auth realm shall be extracted when obtaining the principal url properties.  If the request fails, then the realm is returned and the request can be repeated.  If the peincipal properties can be obtained wirhout password, later things will work also without password.

**Comment by jobisoft** [comment]
> The auth realm shall be extracted when obtaining the principal url properties. If the request fails, then the realm is returned and the request can be repeated. If the peincipal properties can be obtained wirhout password, later things will work also without password.

That is true but I still need to do it. If you do not like the way I do it than I kindly ask you to stop using my software.

**Comment by jobisoft** [comment]
I do not know how to reproduce your issue described in the very first post. If I setup the account like this:
![grafik](https://user-images.githubusercontent.com/5830621/69666887-4c043a00-108d-11ea-8c11-a0d338608014.png)

Your server returns valid data for the username "aaa@milter.aegee.org" so TbSync assumes the user name includes the domain.
![grafik](https://user-images.githubusercontent.com/5830621/69667059-92f22f80-108d-11ea-9455-06ef49b882a0.png)

If I then connect the account, all urls only use "aaa".
![grafik](https://user-images.githubusercontent.com/5830621/69667160-c1700a80-108d-11ea-9753-6491bb2f6c54.png)

If I then try to enable a calendar, it dies with a 403. 
![grafik](https://user-images.githubusercontent.com/5830621/69667418-46f3ba80-108e-11ea-8070-9f0365e2e4ab.png)

I have to change the username manually to "aaa" and than it works.

However, I was not able to recreate requests including th domain.

**Comment by dilyanpalauzov** [comment]
Having anonymous@milter.aegee.org as user, I tweak the server to return two home sets -/dav/calendars/user/aaa@milter.aegee.org/ and /dav/calendars/user/aaa .  The second home set contains  nothing. The first home set returns one calendar collection.  The events from the latter are shown in Lightning.

If the server returns only one home set with @milter, then the Lightning does not show the events from the calendar of the collection in the returned home set.

I tweaked now for host k.bapha.be without user name to return two homesets, one of it called user/aaa and containing no collections.  Then Lightning shows the events from the TLS calendar.

I leave the server now in a state where for milter.aegee.org it returns just one homeset and for k.bapha.be it returns two home sets.  Even if the milter homeset contains calendars containing data, these are not shown in Lightning.  Any idea why?

**Comment by dilyanpalauzov** [comment]
> The events from the latter are shown in Lightning.

I mean the events from /dav/calendars/user/aaa@milter.aegee.org/ are shown.

**Comment by jobisoft** [comment]
In calDAVCalendar (lightning code) there is this:
```      
      // If there are multiple home sets, we need to match the email addresses for scheduling.
      // If there is only one, assume its the right one.
      // TODO with multiple address sets, we should just use the ACL manager.
      if (homeSets && (homeSets.length == 1 || homeSets.some(homeSetMatches))) {
        let cuaSets = caldavXPath(
          multistatus,
          "/D:multistatus/D:response/D:propstat/D:prop/C:calendar-user-address-set/D:href/text()"
        );
        if (cuaSets) {
          for (let addr of cuaSets) {
            if (addr.match(/^mailto:/i)) {
              self.mCalendarUserAddress = addr;
            }
          }
        }

        let inboxPath = caldavXPathFirst(
          multistatus,
          "/D:multistatus/D:response/D:propstat/D:prop/C:schedule-inbox-URL/D:href/text()"
        );
        if (!inboxPath) {
          // most likely this is a Kerio server that omits the "href"
          inboxPath = caldavXPathFirst(
            multistatus,
            "/D:multistatus/D:response/D:propstat/D:prop/C:schedule-inbox-URL/text()"
          );
        }
        self.mInboxUrl = createBoxUrl(inboxPath);
...
```

Basically bla bla but this is code only executed if multiple homesets are present. The Call to createBoxUrl eventually dies because in your case inboxPath is null and that is not being checked for. I manually added this check and the events do show up (in my local build).

I do not know, if this is an error in lightning or of your server for not returning an inbox url. You do return an outbox url:

```
ensureDecodedPath: /dav/calendars/user/anonymous@milter.aegee.org/Outbox/
```

**Comment by dilyanpalauzov** [comment]
It is intentional that the anonymous user has no CalDAV-INBOX, as it does not make sense for anonymous user.

**Comment by jobisoft** [comment]
You are talking to the wrong guy. I just tracked the reason down for you.

**Comment by jobisoft** [comment]
FYI: That looks like the real reason for your mozilla bug. You should actually invalidate it yourself and create a new on, because the information in the first post and the title should be straight to the point. Again, do not mention TbSync as this is not a TbSync issue.

**Comment by jobisoft** [comment]
Also with the anonymous@milter.aegee.org account I was at no point able to observe the usage of %40 in any url. I tend to close this issue.

**Comment by dilyanpalauzov** [comment]
So it does run now.

I reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1599602 .

I run Thunderbird 68.2.2 under Linux, maybe this is the reason why the displayed URL for PROPFIND on calendars (but not on addressbooks) contains sometimes %40. For me this is not a problem, but Apples' servers sometimes return %40 , but they mean @ and then the CUA has to know what the server meant on subsequent requests.
