### ISSUE TITLE
TBSync 0.7.16 need DAV-4-TBSync 0.8.23

### ISSUE THREAD

**Issue by jpfox** [jobisoft/DAV-4-TbSync#18]
Hi,

First, thanks for your tools.

Thunderbird has upgraded TBSync to last 0.7.16 version. But TBSync alerts that it needs DAV-4-TBSync 0.8.23 but Thunderbird Addons only propose v 0.8.14

https://addons.thunderbird.net/en-US/thunderbird/addon/dav-4-tbsync/versions/

Have you uploaded last DAV-4-TBSync version on Thunderbird Addons ?

Thanks for your help

**Comment by jobisoft** [comment]
Sorry, the Mozilla update for DAV is beeing delayed (I do not know why)

You can find the latest version on github:
https://github.com/jobisoft/DAV-4-TbSync/releases

John

**Comment by jpfox** [comment]
Thank you John !
(I let issue opened until Thunderbird propose this version)

**Comment by jpfox** [comment]
0.8.26 is online !
