### ISSUE TITLE
After TB 68 Update: Using lists name as receiver and autocomplete for contact lists is broken

### ISSUE THREAD

**Issue by mcdikki** [jobisoft/DAV-4-TbSync#186]
## Your environment

TbSync version: 2.9
DAV-4-TbSync version: 1.6
Thunderbird version: 68.3.1

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Having a carddav addressbook containing contact lists, thunderbird should autocomplete the list name when typed into a receiver form.
Using the lists name as receiver should send the mail to all contacts in the list.

## Actual behavior
Thunderbird does not autocomplete list names typed into the receivers form, nor does it send mails to all contacts in a list when the lists name was used as receiver.
Instead, it throws an error that the mail address is invalid and not of the form `user@host`.
The list name was typed in the form `list name` where `list name` is one word.

Using contact lists form local addressbooks, this works as expected.
Using TbSync & DAV-4-TbSync pre TB68, this worked as expected.
Typing in the lists name in the form `list name <list name>` works.

## Steps to reproduce
Create a contact list and add some (at least 2) contacts to it.
Create a new mail and try to enter the lists name into the `To` or any other receiver form.
Wait if thunderbird shows an autocomplete drop down containg the list.
Complete the lists name and try to send the mail.

## Additional informations
* All list names where single words without whitespaces or none letter characters.
* All lists contained a nickname and a description.
* Every contact in the lists contained exactly one email address

**Comment by jobisoft** [comment]
Fixed in beta, can you verify?
https://tbsync.jobisoft.de

**Comment by mcdikki** [comment]
Seems to be fixed for me.
Thanks a lot.
