### ISSUE TITLE
Sync of Google Calendar causes "Reminders" pop-up for past recurring events. Dismiss does not work.

### ISSUE THREAD

**Issue by mothe-at** [jobisoft/DAV-4-TbSync#188]
## Your environment

TbSync version: 2.10
DAV-4-TbSync version: 1.7
Thunderbird version: 68.4.2 on MacOS 10.15.2

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

TbSync and DAV-4-TbSync versions have a release date of Jan/26 2020 - it's today.

## Expected behavior
I use my corporate account on Google (with OAuth) to sync my contacts and calendar to Thunderbird. Basically, the sync works fine, all contacts and calendar entries are synced.

## Actual behavior
After each sync, TB pops up the "Reminders" windows with a list of all **past recurring** events (regular meetings, etc.). There are no one-time events in the list, just recurring events.
When I click "Dismiss" on an item or "Dismiss all" on the bottom of the pop-up, nothing happens.
When I open my calendar via the Gmail web frontend, there are no unconfirmed reminders.

## Steps to reproduce
Sync a Google calendar with recurring events.

I am not sure if this is a TbSync, a DAV-4-TbSync or a Thunderbird issue. Sorry if I have used the wrong project for the issue!

And, thank you so much for your effort on this tool! It is amazing and really helpful!!

**Comment by jobisoft** [comment]
I am trying to reproduce the issue. I can see, that past recurring events created in google and synced for the first time in TB will pop up the reminder. If I ack those, that info gets synced to google and I no longer get a reminder for those. Even if I remove the entire account and set it up again.

Can you confirm this? I do not have a coorporate account however, just a normal google account.

**Comment by mothe-at** [comment]
Hi John!
Thank you for having a look at this!
No, this is not the behaviour I see. Right after the sync I see the pop-up with the old reminders. Clicking on "Dismiss" on them does nothing. If I have a regular (not past recurring) event, the Dismiss button works fine, this event disappears from the list and does not pop up again.

<img width="792" alt="Screenshot 2020-01-27 at 13 57 20" src="https://user-images.githubusercontent.com/19708050/73176669-45d21e80-410d-11ea-9c0b-82b25d5a5e57.png">

**Comment by endorphiner** [comment]
I am having exact the same issue on my Mac. Do you have any thoughts on how to get rid of those old reminders? :)
Thanks

**Comment by jobisoft** [comment]
Private or Coorp google account?

@endorphiner 
@mothe-at 
To identify, if this is a bug in Thunderbird (for MacOS?) please open the settings of the google calendar in lightning and copy the url. Then disable your google account in TbSync and then setup your google calendar as a plain CalDAV calender in lightning using the URL you just copied.

Any change in behaviour?

**Comment by endorphiner** [comment]
I have tried your workaround and getting same behavior for dismissing events. I do not get the old events for my personal account but do get those for corp account and they are not getting dismissed. I also tried to install beta TBSync and even disabled it during your workaround test so might be related to Google setup/Lightning issue?
Thanks

**Comment by jobisoft** [comment]
Just to understand what you did: You did the manual setup as descibed here: https://github.com/jobisoft/DAV-4-TbSync/issues/188#issuecomment-579366898

?

**Comment by endorphiner** [comment]
Yep, I've tried your solution and also tried a beta release before doing plain CalDAV.

**Comment by jobisoft** [comment]
If the issue is still there without TbSync being involved, it is an issue with lightning itself and Google.

Your first option now is to search the web if Thunderbird has on option do disable old alarms in the advanced settings.

If that fails, you may try to create a bug report at Mozilla (without mentioning TbSync, as this will just derail your report): https://bugzilla.mozilla.org/home

Google itself is deaf, they will not repsond.

There is nothing I can do. Sorry.

**Comment by endorphiner** [comment]
I totally get your point man and agree with Google being deaf :)
I'll try to search the web and file a bug with mozilla if won't find anything. Will also post here if I find a solution.
Thanks again!

**Comment by endorphiner** [comment]
@mothe-at 
Found a workaround. Turns out if I uncheck the "Show missed reminders" under Preferences>Calendar>Reminders, I don't have this issue. I don't need to be seeing missed reminders so problem is (essentially) solved.

Not sure if that works for you but you can try it :)

**Comment by Geobert** [comment]
Hi, 

I'm also hit by this bug, and can't find the "Preferences" menu to use the workaround, where is it?

**Comment by evilbaschdi** [comment]
Did someone already find another solution than completely disabling missed reminders?

**Comment by cbndr** [comment]
I'm having the same issue. It started occurring a few days ago (new Thunderbird version).

I don't think the issue is inherent to Google Corp accounts. I'm using CalDAV/CardDAV via the "Provider for CalDAV & CardDAV" add-on.

"Show missed reminders" off and the issue disappeared. Turned it back on and the issue re-appeared.

**Comment by paketep** [comment]
Me too, using "Provider for CalDAV & CardDAV" as well.

**Comment by boroli** [comment]
I've the same problem with reoccurring events in my google calendar which I integrated directly via CalDav. So, it's definitely not an issue with DAV-4-TbSync, and maybe then not even restricted to google calendars.

Anyway, as this is the most promising bug report I came up with, when I searched for that problem, I thought I share also the link to an thunderbird upstream bug report, which describes the same issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1718901

And another long outstanding one:
https://bugzilla.mozilla.org/show_bug.cgi?id=1093864

**Comment by Bugeater327** [comment]
This seems to be a common issue. Clearly there is a workaround but it does have side effects that not everyone is willing to accept. Is there anyone actually working to resolve this issue? It can be VERY ANNOYING! Also it seems to come and go with random releases.
Big kudos to whoever can finally find the root cause and fix it!

**Comment by Soleone** [comment]
I'm also encountering a similar issue with alerts that don't go away.
