### ISSUE TITLE
Lighning does not show nextcloud server cal entries

### ISSUE THREAD

**Issue by rainer042** [jobisoft/DAV-4-TbSync#19]
Nextcloud 13.0.6
TbSync: 0.7.16
sabre/DAV: 0.8.26
Lightning: 6.2
Thunderbird: 60.0 on Linux x86_64, OpenSuSE Leap 15

Hello,
I tried TbSync and Sabre/Dav with two servers. The first server is sogo. Here everything worked out of the box. The second server is a nextcloud  server and here using the dav url I also was able to add this nextcloud server to thunderbird via TbSync. In the settings dialog of TbSync I now see all my calendars and I can sync all my calendars (including the nextcloud ones), the only problem is that in lightning I do not see a single event in any of the calendars on nextcloud. I can enter a new event one of my nextcloud calendars and also run a "sync now" which just seems to work without any visible errors, but the new event is not synced to the nextcloud.

Both servers use the very same username/password. Just to be sure I deleted the sogo server from TbSync but still no event from my nextcloud server is shown even after another sync. The calendars locations  URL look just identical to how it was before where I simply used lightning to access this calendar without TbSync, no difference.

Any ideas?

Thanks
Rainer

**Comment by jobisoft** [comment]
That is a known issue with nextcloud and lightning, this is independent of TbSync. 

Fix inside:
https://github.com/nextcloud/server/issues/10134#issuecomment-411322692

**Comment by jobisoft** [comment]
if it works, close this please

**Comment by rainer042** [comment]
Yes this fixes the problem. Works now.

Thanks a lot.
