### ISSUE TITLE
Unknown error HTTP 500

### ISSUE THREAD

**Issue by c4sGH** [jobisoft/DAV-4-TbSync#20]
Thunderbird 60.0
TbSync 07.16.5
sabre/dav (CalDav & CardDav) provider for TbSync 08.26

Task: Synchronization between OwnCloud-Calendar and Thunderbird (2-way).

All credentials (server, lohin-name, login-password) for Owncloud are correct, but TbSync delivers **fail message unknown error HTTP ... 500** (pls. see attached screenshot). Doesn't matter whether we try it with the short Owncloud-Server-URL or the complete URL of the Owncloud-Calendar.

**However, synchronization works correctly !**

Does anyone have an idea what the reason(s) is/are ?

Thanks in advance for feeback ! Michael
![ashampoo_snap_2018 10 09_15h18m44s_006_](https://user-images.githubusercontent.com/14122842/46672325-69e7b480-cbd7-11e8-81c7-fbb800a8a56b.png)

**Comment by jobisoft** [comment]
Can you send me the debug log (via email) of such a "failed" attempt? More info about sending debug log can be found at the "Hilfe" tab.

**Comment by jobisoft** [comment]
and just to make sure: retry with just released v0.8.28 of sabre/dav provider

**Comment by ihackurmind** [comment]
Same issue here with aruba provider. I've just sent a debug log. Hope it can help
