### ISSUE TITLE
Error: Could not find libresolv in any of libresolv.9.so,libresolv.so, bug in version 1.9?

### ISSUE THREAD

**Issue by VasiliyArkhipov2** [jobisoft/DAV-4-TbSync#202]
## Your environment

OS: Linuxmint 19.3 (based on Ubuntu 18.04)
TbSync version: 2.11
DAV-4-TbSync version: 1.9
Thunderbird version: 68.4.1

## Expected behavior
All calendars are synced properly.

## Actual behavior
Tbsync ends up with the error:

`** Sun Mar 01 2020 10:37:14 GMT+0100 (Central European Standard Time) **
[EventLog] : JavaScriptError
Error: Could not find libresolv in any of libresolv.9.so,libresolv.so Exception: Error: couldn't open library libresolv.so: libresolv.so: cannot open shared object file: No such file or directory
postMessage@resource://gre/modules/PromiseWorker.jsm:349:17`

## Steps to reproduce
After reverting to version 1.7 sync works as expected. Reinstalling version 1.9 ends up with the above mentioned error.

**Comment by jobisoft** [comment]
That looks like a dependency issue wich needs to be solved by your distro. I am just using standard API calls and do not load libraries.

This is the changeset:
https://github.com/jobisoft/DAV-4-TbSync/compare/v1.7...v1.9

You can see that I am using more promises (await ...)

I really have no idea here.

**Comment by VasiliyArkhipov2** [comment]
I tested this behaviour on two notebooks.  I should have mentioned that both user have mailbox.org accounts. As I saw in the changeset there was a change of how DNS resolves mbo accounts.

**Comment by VasiliyArkhipov2** [comment]
[use dns lookup for service providers]([url]https://github.com/jobisoft/DAV-4-TbSync/commit/7cf8956bfec1a7b8bf3c49d67fae6ae1dc56215c(url))

**Comment by jobisoft** [comment]
both linux mint?

**Comment by jobisoft** [comment]
Can you update to TB 68.5?

**Comment by VasiliyArkhipov2** [comment]
Yes, both linux mint 19.3. Currently there is no update for TB68.5 available. Later that day I try to reconstruct that in Virtualbox as I don't want to mess up the production environment.

**Comment by VasiliyArkhipov2** [comment]
Your first clue was correct. The package libc6-dev was missing in the Cinnamon version. After installing it, everthings works as expected.

**Comment by jobisoft** [comment]
I am glad it works for you now. If you find the time, could you report this to the package maintainer to update the dependency list? So others do not run into this again?

**Comment by jbierkens** [comment]
After a brief communication with @jobisoft, it turns out that manually installing the package libc6-dev on Ubuntu resolves an error message I was getting ("status.service-provider-setup-failed").

@jobisoft : which package maintainer should install the libc6-dev dependency, should this be installed with the thunderbird package?
