### ISSUE TITLE
Tasks from CalDAV don't get "done" status updated automatically

### ISSUE THREAD

**Issue by nekr0z** [jobisoft/DAV-4-TbSync#203]
## Your environment

TbSync version: 2.11
DAV-4-TbSync version: 1.9
Thunderbird version: 68.5.0

## Expected behavior
After I mark a task "done" elsewhere and it gets marked "done" on the server, it is shown as "done" in Thunderbird after the next synchronization.   

## Actual behavior
The task stays "not done". However, if I mark it "done" in Thunderbird, a popup appears that says the task has been changed on server, with options to either update it from server or push the local changes anyway. Selecting the first option triggers the synchronization of the task in question, after which the task gets correctly marked as "done" in Thunderbird - the synchronization that should have been done automatically.

## Steps to reproduce
1. Have a CalDAV calendar set up for read/write sync with TbSync + Thunderbird, as well as with any other software to any other device (for example, DAVx5 + OpenTasks on Android, I'll use "Another" to refer to it on further steps).
2. Create a task in the calendar in either Thunderbird or Another.
3. Sync the calendar with the new task to the server.
3. Sync the other device with the server. Observe both devices having the same task with all the same features (as intended).
3. Mark the task as "done" in Another.
4. Sync Another with the server.
5. Sync Thunderbird with the server. Observe Thunderbird still showing the task as pending, as opposed to expected "done".
6. Mark the task "done" in Thunderbird. Observe the popup with two options, select "update from the server".

**Comment by jobisoft** [comment]
After you have set up your Calendars with TbSync, can you please disable TbSync? The calendars itself will remain as they are managed by lightning directly. Can you check if your observations remain? If so, it is a bug in Lighning, not TbSync.

**Comment by nekr0z** [comment]
Done more testing; the issue is invalid, actual cause being some particularities in my setup. Really sorry for bothering you. Thank you for the awesome work you're doing!
