### ISSUE TITLE
CardDAV: Synchronizing does not delete (some?) address book fields

### ISSUE THREAD

**Issue by doeringudh** [jobisoft/DAV-4-TbSync#206]
## Your environment
MacOS 10.13.6
Cyrus IMAP 2.5.15 (FreeBSD 12.1-RELEASE-p3)
DAVx5 2.6.5 (Android 7.0)
Contacts 3.1.07.80 (Android 7.0)

TbSync version: 2.11
DAV-4-TbSync version: 1.10
Thunderbird version: 68.6.0

## Expected behavior
When deleting address book fields on another device associated with my CardDAV server (Cyrus IMAP), on my Macs, when syncronizing via DAV-4-TbSync, I would expect that data is not only added to an address book record, but also deleted where necessary.

## Actual behavior
The address book fields that have been deleted on the other device remain intact and visible in DAV-4-TbSync's local address book copy.

## Steps to reproduce
On my Android phone, in the standard contacts app I deleted all work related fields from an address record in the CardDAV address book because the person is no longer with the company. Some fields with private data remain. After syncing with DAVx5, my Android tablet picks up the new record contents correctly, but DAV-4-TbSync on MacOS fails to delete the respective fields in its local Thunderbird address book copy. So I have to deleted them manually on all my Macs.

**Comment by jobisoft** [comment]
Did you enable auto sync (in minutes) in the TbSync Account Manager, so that TbSync will check your server for changes? Or did you hit the sync button manually? I would need a test account on your server to look into that in more details.

**Comment by doeringudh** [comment]
Hi John,

thank you for the quick response!

On 25.03.20 15:47, John Bieling wrote:
> Did you enable auto sync (in minutes) in the TbSync Account Manager, so
> that TbSync will check your server for changes? Or did you hit the sync
> button manually?

Both. 60 Minutes, and for my tests I used the sync button in order to
save time.

I am in the middle of severing ties with Google services and instead
doing calendars and contacts on my own server (plain vanilla Cyrus IMAP
w/o any Web GUI cruft like Kolab).

Took quite a while until CalDAV and CardDAV software on Android could be
considered mature enough for this step. But now, to my surprise, there
are problems on the PC side of the equation.

As to the issue stated in the bug ticket: I haven't mentioned it
explicitly, but adding data to a record works. It then shows up in the
Thunderbird address book. So CardDAV synchronization isn't broken per
se. Just deleting entire fields in a record doesn't seem to propagate
into the local Thunderbird copy of the address book.

Also, when I subsequently delete the left-over fields manually in
Thunderbird, as described, and then sync this change back to the CardDAV
server, my other Macs (identical setups) still don't delete the
respective fields, even though the address book record has now been
generated by Thunderbird, that is, your TbSync module probably. No
change though for the Android clients, since they picked up the
deletions already before.

> I would need a test account on your server to look into
> that in more details.

I created an account for you:

CardDAV URL:
  https://c01.escapebox.net/dav/addressbooks/user/jbieling/Default
CalDAV URL:
  https://c01.escapebox.net/dav/calendars/user/jbieling/Default
User: jbieling
Password: thiQuajyaj7

The x.509 certificate for this domain is signed by my own CA, since this
system is only for my personal use. If you need to install its public
cert in order to pacify Thunderbird, please let me know.

I verified that the account actually works by successfully connecting to
it via DAVx5 on Android.

Best regards,

   Uwe
-- 
Uwe Doering
gemini@geminix.org

**Comment by jobisoft** [comment]
I was able to connect to your server, but I deleted your last comment, as it included credentials and this issue is public.

Is there a web interface to your server, so I can make changes to contacts outside of TbSync?

**Comment by doeringudh** [comment]
On 25.03.20 19:45, John Bieling wrote:
> I was able to connect to your server, but I deleted your last comment,
> as it included credentials and this issue is public.

Thank you. I noticed this afterwards, too. I wasn't aware that my email
replies would end up as public comments on GitHub.

> Is there a web interface to your server, so I can make changes to
> contacts outside of TbSync?

No. As I mentioned, no Web GUI. Only a plain Cyrus IMAP server plus
proper client software on my various devices. I proxy "/dav" through my
Apache web server in order to have everthing on only one HTTPS port, but
this doesn't count as web interface, of course.

It means, however, that I was wrong in my earlier email in that the
X.509 certificate for this service is not signed by my own CA but
instead by Let's Encrypt. So no SSL problems to be expected.

**Comment by jobisoft** [comment]
Cannot confirm this here. What properties exactly did you remove?

I created a dummy contact with all "work" details defined and then removed them on a different client and that was catched by TbSync.

Please enable debug logging to the highest details (under help in the tbsync account manager), restart TB and than remove some details on the remote client and than sync in tbsync. The log should than contain what tbsync "sees" from these changes. After that sync has finished create a debug report under help which will send the log to me.

**Comment by doeringudh** [comment]
I did as you requested. To the record that led me to filing this bug report, on my Android phone I added back the original work phone number and work email address. Both showed up in Thunderbird with their proper "factory" symbol. Then I

- restarted Thunderbird
- switched on the highest debugging level
- removed both work fields on the Android phone again
- sync'ed the phone
- sync'ed Thunderbird

Now in the respective Thunderbird address book the work phone number is gone, but the email address is still there. And its type was changed to "other" ("@" symbol). I tried this procedure twice, with exactly the same outcome.

However, when I wanted to send the bug report, I got the message:

Could not find any useful debug messages. Please activate debug mode, restart Thunderbird and repeat all the steps needed to trigger the erroneous behavior.

Could this be a Mac thing? Wrong path perhaps, or no permissions? Because when I clicked onto the "view debug log" button the log got opened in an extra Thunderbird tab. So it is definitely there.

To cut things short, I sent the log manually to the email address you have on your GitHub home page.

**Comment by jobisoft** [comment]
You switched the order of "enable debug logging" and "restart TB" (see my comment vs your comment). The send log button only works if T'B has beeb restarted with enabled logging.

Looking at your report ...

**Comment by doeringudh** [comment]
You are right. Sorry about this. Shall I repeat the procedure, or wouldn't it produce any more data than what I sent you already?

**Comment by jobisoft** [comment]
I only miss the startup sequence with version information but you provided those info here, so it is fine. Just wanted to explain, why the button did not work for you.

But you could verify with further tests, if it is only the email field, which shows that behaviour.

**Comment by doeringudh** [comment]
Okay. On my phone  I added back all the original fields:

- Organization
- Title
- Work email
- Work phone
- Work address
- Notes

Sync'ed and verified that they showed up correctly in the Thunderbird address book.

Deleted the fields again on my phone.

Sync'ed, and this is what was left of the deleted fields in the Thunderbird address book:

- Organization
- Title
- Work email -> other email
- Work address
- Notes

So this appears to be a superset of my earlier two-field test outcome. Also, is doesn't really seem to be connected to work related fields, since the "notes" field wasn't deleted, either. It's perhaps more a coincident that it happened to me mostly with work related fields because these were the fields I deleted in this case. Might have happened to various other fields, too, had I deleted them.

**Comment by jobisoft** [comment]
This is a nightmare. The deleteProperty() method for the addressbook (which I use) no longer works. Currently testing older versions of TB to find out when this bug was introduced.

**Comment by doeringudh** [comment]
I sympathize with you. Being a software developer myself, this issue indeed started to look to me like a more generic problem in some underlying code, and perhaps even in Thunderbird itself.

To take some pressure off myself, I have by now switched to generic Lightning CalDAV and the CardBook add-on on my main PCs. CardBook is unaffected because it brings its own address book storage mechanism. However, other add-ons that integrate with TB's address book, like gContactSync, which I used in the past, might now be in trouble, too.

For the time being, I will keep my rarely used "spare" Mac configured with TbSync, as a test bed. I still prefer the more TB integrated approach of TbSync. Good luck with sorting this out with the TB developers!

**Comment by jobisoft** [comment]
I think i fixed it. You would help me alot, if you could switch to my beta release channel and give it a spin. This needs to go out fast, as it affects every user, but you know what to look for so you are the ideal tester.

You find all the relevant information about the beta release channel here:
https://tbsync.jobisoft.de

It is just a matter of removing the stable version and installing the beta version.

**Comment by jobisoft** [comment]
FYI: I replaced deleteProperty() by setProperty("") and fixed a few more other places, which I learned about while investigating this issue.

* https://github.com/jobisoft/DAV-4-TbSync/commit/ffd2243db1fecc7e1605a34a89f28801b752e918
* https://github.com/jobisoft/DAV-4-TbSync/commit/67cf88dad460920c729eb037fc65b12c073b41e2

**Comment by doeringudh** [comment]
The issue I reported seems to be fixed now. The three fields I added for a test (work phone, work email, notes) appeared and, on deletion, disappeared again in the TB address book. And there are no zero lenght fields in the VCARD file on my CardDAV server. That is, setting them to the empty string indeed removes the fields from the VCARD.

However, the other left-over fields from my earlier test (organization, title and work address) are still visible in the TB address book, even though they are not in the VCARD file on the CardDAV server. As far as I understand CardDAV, the fields in a VCARD have no individual time stamp or change flag. Only the entire VCARD has a time stamp and a UID.

So any update of the VCARD ought to remove superfluous fields in the address book. Is there perhaps an additional problem in DAV-4-TbSync with the delta building between the CardDAV VCARD and the one in the address book? This should be sorted out, too.

**Comment by jobisoft** [comment]
Could you disconnect your account in TbSync and re-connect it, to start "fresh"? It could be that due to the other errors there where some leftover cached data somewhere.

**Comment by jobisoft** [comment]
STOP NO. Let me see if I can add code to correct such a situation. To late?

**Comment by doeringudh** [comment]
No, haven't done anything, yet.

**Comment by jobisoft** [comment]
These leftover fields are only in TB. 
What happens if you sync TB to your server? Do these fields re-appear on your other devices?
What happens if you remove them on the other devices again? Is TB ceaning up as well?

**Comment by doeringudh** [comment]
I added a notes field in TB in order to enforce an update, and the data from the superfluous fields was indeed reintroduced into the VCARD. I then deleted these fields again on my phone, and after sync'ing they were gone in TB as well.

This means, however, that the address book was in a corrupted state before, and that this by now might be true for lots of other users, too. Which unfortunately means that, once you've released the fixed version, you may want to advise users to untick the CardDAV resource (automatically deletes the address book) and then tick it again in order to reimport the data. That's what I did now, because I couldn't be sure whether there wouldn't be other subtle corruptions left in the address book.

**Comment by jobisoft** [comment]
Thanks for the detailed description. I think I can detect and fix this state.
