### ISSUE TITLE
All calendar entries in lightning dissapear when offline from internet

### ISSUE THREAD

**Issue by saxofooon** [jobisoft/DAV-4-TbSync#208]
Windows 10, Provider for CalDav 1.9

TbSync version: 2.11
Thunderbird version: 68.5

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Calendar entries are visible when offline. Perhaps it's better they can't be edited until synchronization is available, but they should be visible.

## Actual behavior
Calendar entries are not visible when offline.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I can only confirm this, if "offline support" is disabled for the google calendar - and in that case it is expected behaviour.

If offline support is enabled, the calendar gets an exclamation mark, if internat is down and you cannot make changes, but the last state is still shown.

Can you confirm?

**Comment by saxofooon** [comment]
>If offline support is enabled, the calendar gets an exclamation mark, if internat is down and you cannot make changes, but the last state is still shown.
Seems to work now, updated to provider CalDAV & CardDAV 1.10 and thunderbird 68.6.
You can even make changes offline.
The exclamation mark appears only after restart.
I cannot switch "offline support" off because the whole option tab is inactive (greyed out).
Thanks

**Comment by jobisoft** [comment]
Nice.

For the record: If you disable the account in TbSync, all options are changeable.
