### ISSUE TITLE
Mac Thunderbird Hangs after about 15-20 seconds of opening TB

### ISSUE THREAD

**Issue by josaladino2** [jobisoft/DAV-4-TbSync#209]
## Your environment

TbSync version: 2.11
DAV-4-TbSync version: 1.11
Thunderbird version: 68.6.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...
I expect to be able to move around Thunderbird without it hanging.
## Actual behavior
...
The problem is that after about 10-15 seconds of opening up Thunderbird, I get the beach ball and TB hangs.  When I delete my address book which is connected via tbsync, the hanging goes away.  I like the tbsync version of the addressbook (contacts) but the hanging make TB unusable.  Any ideas?  I am connecting to icloud and I have a mac running El Capitan latest version.  Thanks
Joe
joe@bram.net
## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Can you enable debug log (at help in the tbsync account manager) to the higest level, restart TB and send me a bug report? Maybe I cans ee in the log, why it hangs. 

You could also create a fresh test profile in Thunderbird where you only install TbSync and see if it happens there as well. This would eliminate interactions with other add-ons and old leftover/corrupted things in your current profile.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
