### ISSUE TITLE
can not sync calendar with ownCloud calendar 1.6.4

### ISSUE THREAD

**Issue by taich001** [jobisoft/DAV-4-TbSync#214]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.12
Thunderbird version: 68.8

ownCloud 10.4.1.3
Calendar 1.6.4

## Expected behavior
calendar sync

## Actual behavior
calendars get deactivated right after I added them. I can not activate then and I dont get any error.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by taich001** [comment]
![Picture0001](https://user-images.githubusercontent.com/9916454/81924725-c72bbf00-95df-11ea-96ad-a7b72b2b9d35.png)
![Picture0002](https://user-images.githubusercontent.com/9916454/81924733-ca26af80-95df-11ea-8d4e-2cbe1abb025e.jpg)

Here are  some screenshots..

**Comment by jobisoft** [comment]
I sadly have no idea.
