### ISSUE TITLE
Remote CalDAV changes not synchronized

### ISSUE THREAD

**Issue by tobiscode** [jobisoft/DAV-4-TbSync#215]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.12
Thunderbird version: 68.8.0 (32-bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

I have three devices that access the same Posteo remote calendar: 2 using Thunderbird, TbSync and the CalDAV provider, and one smartphone using Davx5. If I add or modify entries on one device, the changes should propagate to all other devices.

## Actual behavior

TbSync only uploads its changes, and does not download remote changes. Davx5 on the smartphone downloads the updates correctly, and the web calendar shows the correctly updated calendar as well.

If I delete and then re-add the remote calendar, it is correctly downloaded.

If an event was modified by machine A, and then I modify it as well on machine B (because the change didn't propagate), and hit "save", only then does it say that there were remote changes, and it gives me the option to override the remote changes, or discard them and reload the element from the server.

## Steps to reproduce
1. Add an event in Thunderbird / TbSync
2. Make sure it's uploaded by waiting for automatic synchronization, or forcing it through the TbSync account manager.
3. On the other TbSync device, those changes are not downloaded (even with forced synchronization, or Thunderbird restart - only deleting and readding the calendar helps).

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Thanks a lot for looking into it, and I'm happy to provide more information. 

Cheers

**Comment by dilyanpalauzov** [comment]
TBSync only tells the Calendar component of Thunderbird the addresses of the CalDAV calendars and is in charge of refreshing the list of calendars.

CalDAV is a pull protocol: the client (Thunderbird) has to ask periodically the server, whther there are changes.

You shall tell the Calendar component in. TB to refresh a calendar.  It is in charge for the content within the calendars.

**Comment by dilyanpalauzov** [comment]
Note that DAVx⁵  uses for conflicts implicitly [the server always wins](https://www.davx5.com/manual/technical_information.html#conflict-handling) strategy, while Thunderbird asks you who shall win in case of conflicts

**Comment by tobiscode** [comment]
> TBSync only tells the Calendar component of Thunderbird the addresses of the CalDAV calendars and is in charge of refreshing the list of calendars.

Thanks. I guess I'll raise this as a Thunderbird bug then.
