### ISSUE TITLE
Nextcloud Calendar / Contacts fails: "PasswordLoginForbidden"

### ISSUE THREAD

**Issue by necrevistonnezr** [jobisoft/DAV-4-TbSync#216]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.11.1
Thunderbird version: 68.8.1

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Connection to Nextcloud Calendar / Contracts, save password with Thunderbird password manager

## Actual behavior

- TbSync asks me to update the credentials for my Nextcoud Account
- I receive an error in the event log: 
```
URL:
https://[MYDOMAIN]/.well-known/carddav (PROPFIND)
Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden</s:exception>
  <s:message/>
  <o:hint xmlns:o="o:">password login forbidden</o:hint>
</d:error>
```
Happens with both an app password or the main Nextcloud Password.

Before using the stable version of TbSync, it would connect but not save my password, even if I ticked the box to use the password manager to save the password.
## Steps to reproduce
see above.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by necrevistonnezr** [comment]
To add: I am able to access the Nextcloud calendar via iOS (also using app passwords) and add appointments that show up on the Nextcloud web calendar.

**Comment by jobisoft** [comment]
I have no answer for you. Your server reports, that password logon is not allowed. I have no idea, why it works with iOS. I close the issue just to sort out the issue list after the long off-time. You may still answer.
