### ISSUE TITLE
NS_ERROR_NET_TIMEOUT with nextcloud behind reverse proxy

### ISSUE THREAD

**Issue by Mer0me** [jobisoft/DAV-4-TbSync#218]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.12
Thunderbird version: 68.8.0 (64 bits)

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Sync calendars & contacts from nextcloud behind a reverse proxy

## Actual behavior
Error NS_ERROR_NET_TIMEOUT throws when creating account in TBSync (in manual mode). The URL given to the plugin for caldav and cardav is https://next.my-server.com/remote.php/dav
The same URL used in a browser will resolve and after requesting credentials will display "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client." 
Apache Logs shows 401 error when Thunderbird tries to connect (200 OK when connecting from a browser)
If the client is on the LAN and access the server directly (without reverse proxy), it works.

## Steps to reproduce
Create an account in TBSync / Provider for Caldav / Cardav and connect to a nextcloud server behind a reverse proxy.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I sadly have no idea.
