### ISSUE TITLE
Owncloud account error

### ISSUE THREAD

**Issue by el95149** [jobisoft/DAV-4-TbSync#22]
Hello there.
Using:
Thunderbird 60.0
TbSync: 0.7.16.6
DAV-4-TbSync: 0.8.28

and trying to add an Owncloud 10 account (installed on a server on my LAN), I get the following error:

![selection_2018-10-16_08 47 54](https://user-images.githubusercontent.com/3635192/46995215-5f21a800-d120-11e8-95bc-689665cfb3f1.png)

I've also tried using the full URL, ending in: 
https://.......:4443/owncloud/remote.php/dav/addressbooks/users/....../default

Error log:
`** Tue Oct 16 2018 08:54:15 GMT+0300 (EEST) **
[setSyncState] : State: send.getfolders, Account: owncloud2

** Tue Oct 16 2018 08:54:15 GMT+0300 (EEST) **
[URL] : https://..........:4443/owncloud/remote.php/dav

** Tue Oct 16 2018 08:54:15 GMT+0300 (EEST) **
[HEADERS] : {"Depth":"0","Prefer":"return-minimal"}

** Tue Oct 16 2018 08:54:15 GMT+0300 (EEST) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

** Tue Oct 16 2018 08:54:15 GMT+0300 (EEST) **
[RESPONSE] : 500 : <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en_GB" >
	<head data-requesttoken="">
		<meta charset="utf-8">
		<title>
		ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
					<meta name="apple-itunes-app" content="app-id=543672169">
				<meta name="theme-color" content="#1d2d44">
		<link rel="icon" href="/owncloud/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/owncloud/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/owncloud/core/img/favicon-mask.svg" color="#1d2d44">
					<link rel="stylesheet" href="/owncloud/core/vendor/select2/select2.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/styles.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/inputs.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/header.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/icons.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/fonts.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/apps.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/global.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/fixes.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/multiselect.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/mobile.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/jquery-ui-fixes.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/tooltip.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/share.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/apps/files_versions/css/versions.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
					<link rel="stylesheet" href="/owncloud/core/css/jquery.ocdialog.css?v=df39a9ff05c4b3c23acf59ad7fdefa22">
									<script src="/owncloud/core/vendor/jquery/dist/jquery.min.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/jquery-migrate/jquery-migrate.min.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/underscore/underscore.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/moment/min/moment-with-locales.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/handlebars/handlebars.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/blueimp-md5/js/md5.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/bootstrap/js/tooltip.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/backbone/backbone.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/es6-promise/dist/es6-promise.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/davclient.js/lib/client.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/clipboard/dist/clipboard.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/bowser/src/bowser.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/jquery.ocdialog.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/oc-dialogs.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/js.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/l10n.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/l10n/en_GB.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/octemplate.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/eventsource.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/config.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/search/js/search.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/oc-requesttoken.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/apps.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/mimetype.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/mimetypelist.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/snapjs/dist/latest/snap.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/vendor/select2/select2.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/oc-backbone.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/placeholder.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/jquery.avatar.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/apps/encryption/l10n/en_GB.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/apps/encryption/js/encryption.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/shareconfigmodel.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharemodel.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharescollection.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/shareitemmodel.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialogresharerinfoview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialoglinklistview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialoglinkshareview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialogmailview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialoglinksocialview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialogexpirationview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialogshareelistview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/sharedialogview.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/share.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/files/fileinfo.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					<script src="/owncloud/core/js/files/client.js?v=df39a9ff05c4b3c23acf59ad7fdefa22"></script>
					</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
		<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									ownCloud								</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<span class="error error-wide">
	<h2><strong>Internal Server Error</strong></h2>
		<p>The server encountered an internal error and was unable to complete your request.</p>
		<p>Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.</p>
		<p>More details can be found in the <a target="_blank" rel="noreferrer" href="https://doc.owncloud.org/server/10.0/go.php?to=admin-logfiles">server log</a>.</p>
	<br>

	<h2><strong>Technical details</strong></h2>
	<ul>
		<li>Remote Address: .............</li>
		<li>Request ID: yCVPUSK8X5HJgXfqNrmK</li>
			</ul>

	</span>
				<div class="push"></div>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://owncloud.org" target="_blank" rel="noreferrer">ownCloud</a> &ndash; A safe home for all your data			</p>
		</footer>
	</body>
</html>

** Tue Oct 16 2018 08:54:15 GMT+0300 (EEST) **
[setSyncState] : State: accountdone, Account: owncloud2`

Any ideas as to what could be causing this?
Thaks in  advance.

**Comment by el95149** [comment]
Following up, here's an excerpt from owncloud's log, hinting about the error:

`  "url": "\/owncloud\/remote.php\/dav",
  "message": "Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Invalid url \\\"null\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Util.php(809): OCP\\\\Util::getFullDomain('null')`

**Comment by jobisoft** [comment]
It should work with just the base url without /remote.php/.... If that is not working, the discovery service on your server is not configured correctly. You may try /remote.php/carddav/

John

**Comment by el95149** [comment]
Resolved, using '/remote.php/carddav'.

Thanks a bunch!

**Comment by jobisoft** [comment]
But than tbsync cannot help you in setting up your calendars (caldav), you should get your discovery service (.well-known redirects) fixed.

**Comment by el95149** [comment]
Will  do, at some point, for the moment I'm using Kontact's calendar (I'm on Kubuntu, it's only KMail I don't want to use, no threaded/conversation view there).

Since we're at it, I'm now trying to connect from my laptop as well, but I get a 'self signed certificate' error (which is real, since I've generated it myself). Funny thing is, it didn't happen on my desktop. Do you want me to create a separate issue for that, for tracking/history purposes?

**Comment by jobisoft** [comment]
Just install your certificate as trusted. There are instructions in the tbsync wiki,
