### ISSUE TITLE
Allow response Href to be null

### ISSUE THREAD

**Issue by yoyoyonas** [jobisoft/DAV-4-TbSync#222]
Including a Href header in every response is not mandatory and not every DAV server sends one (e.g. [SOGo](https://sogo.nu/) doesn't).

Currently DAV4TbSync breaks

```
responseHref is null
hrefMatch@chrome://dav4tbsync/content/includes/tools.js:291:16
getNodesTextContentFromMultiResponse@chrome://dav4tbsync/content/includes/tools.js:315:44
folderList@chrome://dav4tbsync/content/includes/sync.js:215:33
```
when trying to sync to such server.

I fixed it for me by replacing
https://github.com/jobisoft/DAV-4-TbSync/blob/28e71b385d31cf2a8b489332582194a06996c706/content/includes/tools.js#L285
by `if (_requestHref === null || _responseHref === null)`.

**Comment by jobisoft** [comment]
Can you send a PR?
