### ISSUE TITLE
Sync with CardDAV-server problem since Update to TB 78

### ISSUE THREAD

**Issue by ronald-at** [jobisoft/DAV-4-TbSync#223]
## Your environment

TbSync version: 2.16
DAV-4-TbSync version: 1.16
Thunderbird version: 78.0.1

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I've configured mit CardDAV Server in TbSync. I'm using Baikal 0.6.1 as server. After I've enabled the account the synchronization starts. When I've used the system with Thunderbird 68, TbSync 2.12 and DAV-4-TbSync 1.12 everything went fine.
The sencond issue is the detection of changes in the address book. When I add a contact to a synchronized address book, TBSync automatically detected the change and started the synchronization in my old installation with TB 68.

## Actual behavior
After syncrhonizing 362 of 368 contacts, the error "found is null" (addItem@chrome://tbsync/content/modules/addressbook.js:527:9) is displayed.
When I add a contact in TB78 the status in the TBSync Account Manager stays at OK. Even if I press the button for immediate synchronzation, the contact is not uploaded to the server.

## Steps to reproduce
I think the synchronization error has something to do with the data stored in this contacts.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I will send you the debug logging via email, but I cannot provide the logfile with the contact information, so I just enabled the error log.

**Comment by ronald-at** [comment]
I've found out, that the problem is related to lists in the address book. I was able to reproduce the problem with a test account with one contact which I've added to a contact list in Thunderbird 68. When I try to synchronize to this account with Thunderbird 78.0.1, the same error is show. I've already sent you the full log, since only test data is included in that account.

**Comment by jobisoft** [comment]
Thanks for the report. I will look into it.

**Comment by ronald-at** [comment]
I had a closer look to the problem. The main issue is, that when a new maillist is created in TB (with the call to this._directory.addMailList), the UID from _tempListDirectory is not preserverd, instead a new one is created. So the call to getItemFromProperty fails, because the UID is not matching.
`chrome://tbsync/content/modules/addressbook.js, line 507, async addItem(abItem, pretagChangelogWithByServerEntry)
        
        this._directory.addMailList(abItem._tempListDirectory);
        
        // the list has been added and we can now get the corresponding card via its UID
        let found = await this.getItemFromProperty("UID", abItem.UID);`

This is the code, where the new UID is created:
`resource:///modules/AddrBookDirectory.jsm, line 1031, addMailList(list)

      let newList = new AddrBookMailingList(
      newUID(),
      this,
      this._getNextListId(),
      list.dirName || "",
      list.listNickName || "",
      list.description || ""
    );`

The next problem, which I found is, that in the observer the newly created mailing list with the different UID, does have an empty changelog status which doesn't end with "_by_server", so it is supposed to be a newly created list by the user. The changelogstatus isn't copied, when the mailing list is added to TB.
This is the code where the item should be considered as added by the server

`chrome://tbsync/content/modules/addressbook.js, line 940, addressbookObserver: observe: async function (aSubject, aTopic, aData) {

            let itemStatus = abItem.changelogStatus;
            if (itemStatus && itemStatus.endsWith("_by_server")) {
              //we caused this, ignore
              abItem.changelogStatus = "";
              return;
            }
`

I don't have an idea, how to fix this problems, but I hope my analysis may help you.

**Comment by jobisoft** [comment]
That helps, but I will need a while to get to it. Thanks for your analysis!

**Comment by dazz2017** [comment]
Hi, I too was having this issue and eventually found that (in my case) that "autosaved"email addresses in my mail provider contacts list (I use Fastmail) were causing the problem. When I deleted this group from my Fastmail contact page, TB would sync without any errors. I don't actually know how/when this autosave group was created so I can't re-create and confirm the problem but thought I'd mention it anyway.

TB 78.3.1 (64-bit)
TBSync 2.16
Provider for CalDAV & CardDAV 1.19

**Comment by jobisoft** [comment]
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.
