### ISSUE TITLE
Bizarre Addressbook labels

### ISSUE THREAD

**Issue by exapplerep** [jobisoft/DAV-4-TbSync#225]
## Your environment
Windows 10, TBird 78.1.1
TbSync version:
DAV-4-TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Addressbook labels should appear properly when editing a contact.

## Actual behavior
Technobabble labels appear in place of expected labels. See attached screenshot.

## Steps to reproduce
Just open the Addressbook and edit any Google entry. Local Addressbook (like "collected addresses") doesn't display the issue.
![strange addressbook screen](https://user-images.githubusercontent.com/54422972/89736595-b8f70e80-da27-11ea-94e1-92a82d870833.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Schroedingers-Cat** [comment]
Not trying to derail here, but next to the labels I'm also unable to add phone numbers or email addresses by clicking on the plus sign. Any possible workaround for this?

**Comment by jobisoft** [comment]
The entire dialog is broken as its init sequence throws and exits early.
