### ISSUE TITLE
401 with tbsync and Radicale

### ISSUE THREAD

**Issue by JensTheCoder** [jobisoft/DAV-4-TbSync#226]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.12
Thunderbird version: 68.11.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
No error message in the reverse proxy's log.

## Actual behavior
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "PROPFIND /radicale/username/ HTTP/1.1" 401 713 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "PROPFIND /radicale/username/ HTTP/1.1" 207 737 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "PROPFIND /radicale/username/ HTTP/1.1" 207 1004 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "PROPFIND /radicale/username/ HTTP/1.1" 401 556 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "PROPFIND /radicale/username/ HTTP/1.1" 207 744 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "PROPFIND /radicale/username/ HTTP/1.1" 207 929 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:11 +0200] "REPORT /radicale/username/zzzetrzzter-qegrqgvvvvvv4rvq-qrvqq224rq4-q/ HTTP/1.1" 207 587 "-" "Thunderbird CalDAV/CardDAV Lightning/68.11.0"
111.222.333.444 - - [10/Aug/2020:13:23:12 +0200] "REPORT /radicale/username/abababab-cbcbcbcbcb-12345e-gghghghgg5444/ HTTP/1.1" 207 743 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Thunderbird/68.11.0 Lightning/68.11.0"

## Steps to reproduce
Thunderbird on ubuntu desktop 18.04 latest release
Radicale on ubuntu server 20.04 latest release
Reverse proxy with Apache2 on ubuntu server 18.04

Nonetheless, tbsync gets a list with all available resources. It syncs smoothly. The only complain because of the 401 in the reverse proxy's log file.

**Comment by jobisoft** [comment]
TbSync tries a few groups related request, which are implemented differently on different systems. I did not have time to properly pre-detect such things.
