### ISSUE TITLE
NS_ERROR_NET_TIMEOUT when try to create a new setup with gmx.net/web.de

### ISSUE THREAD

**Issue by boroli** [jobisoft/DAV-4-TbSync#227]
## Your environment

TbSync version: 2.15.5
DAV-4-TbSync version: 1.15.5
Thunderbird version: 78.1.1

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
A new sync is created in a freshly installed TB.

## Actual behavior
[Loaded provider] : dav::CalDAV & CardDAV (1.15.5)
[EventLog] : RFC6764 DNS request succeeded
SRV record @ _caldavs._tcp.web.de
{"prio":1,"weight":1,"host":"kalender-bs.web.de","port":443,"type":33,"nsclass":0,"ttl":30}
[EventLog] : RFC6764 DNS request succeeded
TXT record @ _caldavs._tcp.web.de
{"data":"path=/begenda/dav/users/","type":16,"nsclass":0,"ttl":37279}
[URL Request #1] : https://kalender-bs.web.de/begenda/dav/users/
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

[EventLog] : network::NS_ERROR_NET_TIMEOUT
URL:
https://kalender-bs.web.de/begenda/dav/users/ (PROPFIND)
[EventLog] : RFC6764 DNS request succeeded
SRV record @ _carddavs._tcp.web.de
{"prio":0,"weight":1,"host":"carddav.web.de","port":443,"type":33,"nsclass":0,"ttl":37280}
[URL Request #1] : https://carddav.web.de/.well-known/carddav
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

[EventLog] : network::NS_ERROR_NET_TIMEOUT
URL:
https://carddav.web.de/.well-known/carddav (PROPFIND)

## Steps to reproduce
Try to enable a new sync

**Comment by jobisoft** [comment]
Sorry. I cannot reproduce it. I just created a new gmx account using the gmx option of tbsync and it worked. Maybe try the beta:

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel
