### ISSUE TITLE
TbSync NOT compatible with Thunderbird 68.12

### ISSUE THREAD

**Issue by jacek-1** [jobisoft/DAV-4-TbSync#228]
Hi,
Any timeline when it will be ?
thank you

**Comment by jobisoft** [comment]
Cannot confirm:

![grafik](https://user-images.githubusercontent.com/5830621/92385920-1360b900-f113-11ea-8954-b8d0dbde977e.png)

**Comment by jacek-1** [comment]
that's weird, in my case it shows "Works with Thunderbird 78.0 - *" and I cannot install it even manually from .xpi file

**Comment by jobisoft** [comment]
You should of course install the version for TB68, not TB78 - iy our are using TB68.

**Comment by jacek-1** [comment]
my bad, with previous 2.12 version it works with TB68, somehow at first look version 78 seemed to me as older than 68 :-)

**Comment by jacek-1** [comment]
my bad, with previous 2.12 version it works with TB68, somehow at first look version 78 seemed to me as older than 68 :-)

**Comment by jobisoft** [comment]
👍
