### ISSUE TITLE
Fails to sync with Google contacts and calendars after TB 68>78.2.2 update

### ISSUE THREAD

**Issue by DavidBE-UK** [jobisoft/DAV-4-TbSync#229]
## Your environment

TbSync version: 2.15.5
DAV-4-TbSync version: 1.15.4
Thunderbird version: 78.2.2

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
... After updating today from TB 68 to 78.2.2 and then installling the latest TbSyns, EAS for TbSync and DAV for TbSync, both contacts and calendars from my outlook.com and gmail.com accounts would sync with TB as they had before the TB update.

## Actual behavior
... While outlook,com succesfully synced, the Google sync failed for each calendar and the contacts with the event log full of entries about javascript errors of too much recursion.

For each calendar and the contacts there is:

[JavaScript Error: "too much recursion"  {file: "resource:///modules/CalDavCalendar.jsm" line: 124}]'[JavaScript Error: "too much recursion"  {file: "resource:///modules/CalDavCalendar.jsm" line: 124}]' when calling method: [callCalendar::id]

Account: Google (DAV)
Resource: *******

where ******* is the name of one of the calendars or Contacts.

## Steps to reproduce
... After the TB update, then the TbSync etc updates, re-starting TB etc, attempting to sync the Google/gmail.com calendars and contacts. Havre tried disabling and re-enabling. No difference.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Try the beta:
https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version

After switching to beta, please remove your google account from the tbsync manager and set it up again.

**Comment by DavidBE-UK** [comment]
Thanks. All working now with the new betas.
