### ISSUE TITLE
Not all contacts are showing in Thunderbird Addressbook

### ISSUE THREAD

**Issue by herzogmedia** [jobisoft/DAV-4-TbSync#23]
### Your environment

TbSync version: 0.7.16.6
Thunderbird version: 60.2.1
sabre/dav provider version: 0.8.28

### Expected behavior
All the 615 contacts should show in the Thunderbird Addressbook.

### Current behavior
Although TBSync seems to recognize all the 600 contacts on an initial sync with the carddav-server, in the corresponding thunderbird addressbook only about 160 contacts are shown.

**Comment by jobisoft** [comment]
I would need a complete log of the initial sync. Activate debug logging, unsubscribe the address book in question, restart TB, re-subscribe the address book and sync and then send me the log per email.

**Comment by herzogmedia** [comment]
done, thanks for your help!

**Comment by jobisoft** [comment]
Have you received my email with the debug version? It would also be helping, if you could identify one of your contacts, that is missing, so I can check the log. If your answer contains private data, better reply via email.

**Comment by herzogmedia** [comment]
hm, didn't recieve anything so far. Nevertheless I'll send you some missing contact names via mail.

**Comment by jobisoft** [comment]
I found the reason for this bug! You do not need to perform the test above.

When requesting cards from the server I have to do this in two steps. First I ask for changed/new cards and get a list of IDs (href tag):

```
<d:response>
  <d:href>/remote.php/carddav/addressbooks/lherzog/kontakte/4ab474ad-c951-4bcb-a046-3ec0ccee4b08%2540oc.****.de.vcf</d:href>
  <d:propstat>
    <d:prop>
      <d:getetag>"5bdca6f7835f5986195b070869f96410"</d:getetag>
      <d:getcontenttype>text/x-vcard</d:getcontenttype>
    </d:prop>
    <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
</d:response>
```

Than I ask for those IDs:

```
<d:response>
  <d:href>/remote.php/carddav/addressbooks/lherzog/kontakte/4ab474ad-c951-4bcb-a046-3ec0ccee4b08@oc.****.de.vcf</d:href>
  <d:propstat>
    <d:prop>
      <d:getetag>"5bdca6f7835f5986195b070869f96410"</d:getetag>
      <card:address-data>BEGIN:VCARD&#xD;
VERSION:3.0&#xD;
...
END:VCARD&#xD;
</card:address-data>
    </d:prop>
    <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
</d:response>
```

As you can see, the original ID does not have an "@", but an "%2540". However the final card has an "@". This causes that card to be skipped, because for TbSync, it is an unknown card.

Now thinking how to fix this.

**Comment by jobisoft** [comment]
What version of owncloud is this? Is it the latest?

**Comment by herzogmedia** [comment]
no, its 8.1.5

**Comment by jobisoft** [comment]
Do you plan on upgrading?

**Comment by herzogmedia** [comment]
that doesn't work on my current webserver, i'd have to move. But I suppose it will be inevitable some time...

**Comment by jobisoft** [comment]
This is a very strange behaviour and it does not look correct (from the owncloud side). 

I remember, that my own "old" adressbook in owncloud had also an error with not all contacts showing up. Could you export your adressbook in outlook and import it again (as a second address book) and check, if that second (new) addressbook shows the same behaviour?

**Comment by herzogmedia** [comment]
ok, so it seems to be a owncloud version issue. I found out the following:

- if I add my contacts to a second addressbook, the same error occurs.
- if I add the contacts to a new version of nextcloud (which I just installed for testing on an uberspace) it works without an error
Well, I need to update my server then, I guess ;)

**Comment by jobisoft** [comment]
I give up on this. I had an idea how to fix this, but that just moved the issue towards messing up updates. I will for now stop investigating this. 

You could export your address book via your owncloud web interface and modify the UIDs in the exported file and remove all "@<server>" or "%2540<server>" strings by using search and replace. After importing that file into a new address book it should sync just fine.
