### ISSUE TITLE
CardDAV does not upload new contacts

### ISSUE THREAD

**Issue by ralfrupf1976** [jobisoft/DAV-4-TbSync#232]
## Your environment

TbSync version: Current
DAV-4-TbSync version:
Thunderbird version: 78.2.2

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
If I create a new contact in adressbook it should be uploaded to my nextcloud.

## Actual behavior
The contact is only stored local

## Steps to reproduce
Create a new contact, run sync, login to nextcloud - contact is missing...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Clicac** [comment]
Same problem here.
Using Baikal as caldav/carddav server, V 0.6.1

**Comment by Schroedingers-Cat** [comment]
Same problem with Nextcloud 18.0.9, TB 78.3.1 and TB Sync 1.19. Was working fine before the last TB update rendered existing extensions incompatible.

**Comment by Aqmos** [comment]
Same here with Radicale 3.0. Was working fine with TB68. After update to TB78, sync is only working one-way: 
From server to TB: o.k.
From TB to server: not o.k.
In the address-book, when I right-click on a card-dav-account --> properties I see the correct name of the respective address-book. After clicking "o.k." to close the dialog, I receive an error message saying that an "address-book with this name is already existing". I deleted all accounts, deinstalled TBSync and "Provider for...", deleted manually what was left in the TB-profile and installed everything new. --> The above problem remains identical

**Comment by Ian-Mil** [comment]
Same here with gmail contacts.  TbSync Account Manager says completed but new contacts do not appear in Google Contacts.  No error messages are shown.  Changes in Google contacts are correctly updated in Thunderbird.

**Comment by gerdlimbeck** [comment]
Same Problem here. TB 78.3.2 (64bit) + Provider für CalDAV & CardDAV 1.19 + TbSync 2.16
Is some one workling on this problem?

**Comment by gerdlimbeck** [comment]
Same problem here. TB 78.3.2 + TbSync 2.16 + Provider für CalDAV & CardDAV 1.19
Is someone working on this problem?

**Comment by Schroedingers-Cat** [comment]
@jobisoft is this a known issue? Is there any workaround to this?

**Comment by jobisoft** [comment]
WIP, no workaround, the thing is plain broken.

**Comment by Schroedingers-Cat** [comment]
In that case, would it be possible to redraw the current version from TB's addon list? It renders the addon's core functionality unusable but users won't realize that and trust that it works as before with the current version of TB. A clear "currently not compatible with the latest TB" will avoid this.

**Comment by jobisoft** [comment]
I did.

**Comment by Schroedingers-Cat** [comment]
It's still listed as compatible on the website, but maybe I'm having a cache issue or something like this: 
![grafik](https://user-images.githubusercontent.com/6382400/96235473-60457400-0f8a-11eb-8812-eccd3a57d38c.png)

**Comment by jobisoft** [comment]
The provider is not broken, tbsync is and that has been withdrawn.

**Comment by Schroedingers-Cat** [comment]
I see, makes sense then. Can we watch this issue for the current status? https://github.com/jobisoft/TbSync/issues/448

**Comment by jobisoft** [comment]
I will close and inform all of those dozen issues, once this is fixed.

**Comment by Ian-Mil** [comment]
Thanks.  I'm happy to help test the fixed version with Google contacts.

**Comment by jobisoft** [comment]
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.

**Comment by Ian-Mil** [comment]
Hi, I've just downloaded the beta [TbSync (2.18) and DAv for TbSync (1.20)] and that seems to have fixed the Google contact sync problem with my Thunderbird [78.3.2 (32-bit)] .  Contacts added, edited or deleted at either end are reflected at the other side after running Synchronise now.
Thanks

**Comment by jobisoft** [comment]
Please check for updates, you should get DAV 1.21. There was a boot order dependency, which crashed google support.

**Comment by Ian-Mil** [comment]
Updated DAV to 1.21 and re-tested.   Contacts added, edited or deleted at either end are reflected at the other side correctly.
Thanks again

**Comment by jobisoft** [comment]
Could you activate groups mode and play with syncing lists?

**Comment by jobisoft** [comment]
![grafik](https://user-images.githubusercontent.com/5830621/96264009-0792cd00-0fc4-11eb-995d-cee7962e1aad.png)

**Comment by Clicac** [comment]
Yai the new beta (1.21) works with Baikal: Contacts sync both ways!
BIG thanks!!
Would give a shot with groups, but I sync with iOS, where Groups are not supported...

**Comment by jobisoft** [comment]
>  Would give a shot with groups, but I sync with iOS, where Groups are not supported...
They are :-)

**Comment by Clicac** [comment]
> > Would give a shot with groups, but I sync with iOS, where Groups are not supported...
> 
> They are :-)

Oh, really? Did not realize... So, here are my results:

(1) Sync TB->Baikal -> iOS works: List added, list items added as well.
(2) Sync iOS -> Baikal -> TB not working. Changes in iOS (added a Phone# of a list item) not syncing in TB

Open Question: Cannot say, if changes in (2) hang between iOS and Baikal or between Baikal and TB since I'm testing with a test-profile.

Thanks all, and I have the feeling, that all will be working soon!
