### ISSUE TITLE
Random behavior of new event owner

### ISSUE THREAD

**Issue by dragoangel** [jobisoft/DAV-4-TbSync#233]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.12
Thunderbird version: 68.12.1

[+] Yes, I have installed the latest available beta version from https://tbsync.jobisoft.deand my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I create event and invite attenders in SOGo TbSynced calendar my email account which used for syncing must be owner of event, or this setting can be set via some option in UI somewhere. Event send to user and he see my email.

## Actual behavior
When I create event and invite attenders in SOGo TbSynced calendar I get on place of owner one of mine email aliases in SOGo but not mine email. Also I can't change\configure this anywhere. 
When actually I create event and send invite - users get envite with me as owner, correctly. So this only displaying issue that intimidate people and stop them from creating invites.
If I switch to Thunderbird "Home" Calendar then owner will be displayed correctly as my own Full Name <email>. This something that maybe can be forced or be customized by TbSync or DAV for TbSync.

## Steps to reproduce
1. Open TbSync settings.
2. Add new SOGo account with contacts and calendars. **Importand note**: this user has email aliases visible to SOGo.
3. Choose Personal calendar and contact book to sync.
4. Go to Lightning calendar and create new event in Personal SOGo calendar.
5. Invite attenders to it and you will see that your email (email of creator of event) isn't actually yours - it will be any of your alias or can be lucky your real email.

> To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
If you need logs for this case I can provide them, after you approve they needed, hope this ok.

**Comment by jobisoft** [comment]
There is a new version of the SOGo connector out. Maybe you try that.

**Comment by dragoangel** [comment]
But I like TbSync ^_^. SOGo connector isn't allow to have multiple accounts to sync, etc.

**Comment by jobisoft** [comment]
The issue is, I have started a new full time job as Thunderbird Add-On support engineer. So I basically work on lots of *other* add-ons, but cannot work on my own. For example, I helped to convert that SOGo Connector. Most of my free time is family time, now. I will see what I can do.

**Comment by dragoangel** [comment]
Ho, okay. In any case big thanks to you for great product :)

**Comment by dragoangel** [comment]
For me in SOGo Connector was also issue that it was too silent :) no way to debug, no way to see what going on in background. In that part tbsynch much better.
I like option in sogo connector to install predefined list of plugins, till first general update of thunderbird. Due to fact that thunderbird on each update break plugins it impossible to maintain this list for people who has different versions of thunderbird mostly so I stopped to use this  plugin a year ago.
