### ISSUE TITLE
Duplicate newly added entries

### ISSUE THREAD

**Issue by sphakka** [jobisoft/DAV-4-TbSync#235]
## Your environment

TbSync version: 2.16.2
DAV-4-TbSync version: 1.15.6
Thunderbird version: 78.3.2

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Add a new calendar entry: one entry is added.

## Actual behavior
Add a new calendar entry: two (apparently) identical entries are added. 

It looks like sometimes this happens starting from the second newly added entry to any calendar since TB (re)starting. That is, the first attempt may result correctly in one new entry added, but any subsequent one always produces duplicates.

## Steps to reproduce
1. (Re)start Thundebird
2. Select any calendar
3. Add a new entry: one entry correctly added
4. Add another entry: two copies of the same entry are added

**Comment by sphakka** [comment]
Ouch, I just realized this happens with EAS also!

**Comment by jobisoft** [comment]
can you test if it happens with caldav directly? Disable TbSync and add your caldav calender in light directly?

**Comment by sphakka** [comment]
TB's fault, indeed. Here's the upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1668478
