### ISSUE TITLE
Permit configuring CalDAV only accounts

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#236]
I setup an account for (as server) milter.aegee.org (or for user anonymous@milter.aegee.org with any password) in TB78.3/DAV-4-TbSync 1.21.  Thunderbird calls first `PROPFIND https://milter.aegee.org/.well-known/caldav`, for which it receives a 301 redirect, and `PROPFIND https://milter.aegee.org/.well-known/caldav`, for which it gets a 404 answer.  If I configure CardDAV, then the setup completes.

* Complete the automatic detection setup, when CalDAV is offered and CardDAV is not offered, or vice versa.

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.

**Comment by dilyanpalauzov** [comment]
What is the rationale for discontinuing the DAV provider?

**Comment by return42** [comment]
See https://github.com/jobisoft/DAV-4-TbSync/issues/317#issue-2217984254
