### ISSUE TITLE
Sorry for whatever Google users have said

### ISSUE THREAD

**Issue by J-Martz** [jobisoft/DAV-4-TbSync#241]
Hi,

I don't know anything about what troubles you've been having with Google users and I'm sorry they aren't appreciative of what you have developed.  However I am a also a Google user who just started to use your extension and it worked fine. Now I just went to another computer that I use TB on and I can't use you're extension because it no longer supports Gmail Accounts.    

This is about the only contact sync extension out there that works with the new TB and it's really disappointing that ordinary everyday users can't use your extension because of a few people that can't keep their mouth shut.

Can you please reconsider your position on this in order to allow those of us who want to use it and appreciate it can do so?

Thanks for considering my request.

**Comment by jobisoft** [comment]
Please check instructions given here on how to enable google support.
https://github.com/jobisoft/DAV-4-TbSync/issues/240

**Comment by J-Martz** [comment]
I see that, but I am not familiar with what you meant by flipping the Thunderbird property or where to find that.

**Comment by soistheman** [comment]
Go to Options --> General and scroll down all the way --> Config Editor... --> I accept the risk --> Type "extensions.dav4tbsync.googlesupport" in search --> Click the record to change "value" column to true.

**Comment by jobisoft** [comment]
Added that to the announcement.
