### ISSUE TITLE
Synch of read only address books

### ISSUE THREAD

**Issue by typhoon71** [jobisoft/DAV-4-TbSync#242]
First a word of thanks for your hard work, as this addon (along with TbSynch) is one of the only 2 working on newer Thunderbirds.

## Your environment
Windows 7/10
TbSync version: 2.11
DAV-4-TbSync: 1.12
Thunderbird version: 69

The issue happens when one deletes a contact on an addressbook which is read only server side and is not set as read only when configuring it in TbSync. TbSynch behaviour is better than CardBook, which I tested too.

## Expected behavior
- Try to delete a contact (or try to create a new contact) on an addressbook that is shared as read only.
- Get a message that the action is not possible.

## Actual behavior
- Try to delete a contact (or try to create a new contact) on an addressbook that is shared as read only.
- The contact is deleted (or created).
- At the next syching the contact reappears (or disappears)

Note that TbSynch behaviour is better than CardBook, which deletes the contact and doesn't recover when synching.

## Steps to reproduce
- Connect to a remote CarDAV addressbook that is set as read only by its owner (a read only share / read only user)
- Do not tick the "read only" flag while configuring it in TbSynch.
- Try to delete a contact (or try to create a new contact) on an addressbook that is shared as read only.

I suppose checking the "read only" flag while configuring the addressbook would take care of it, but I'd like to know if it's feasible to have TbSynch "understand" the addressbook is read only even without that check.

The issue is happening with a SoGo based addressbook: while their addon does not exibit this issue, they never update it for newer Thunderbird releases...

If the logs are really needed for this I'll post them later, since I'll have to remove sensitive data from them (GDPR thing).

Is it possible to "solve" this? Thanks.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
