### ISSUE TITLE
RSVP missing on ATTENDEE attribute in VCALENDAR

### ISSUE THREAD

**Issue by tobru** [jobisoft/DAV-4-TbSync#246]
## Your environment

TbSync version: 2.19
DAV-4-TbSync version: 1.24
Thunderbird version: 78.6.0 (64-bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

Inviting a participant in a calendar entry should send an invitation to the `ATTENDEE` field with the `RSVP=TRUE` attribute.

## Actual behavior

The RSVP attribute is missing:

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Zurich
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=3DYEARLY;BYMONTH=3D3;BYDAY=3D-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=3DYEARLY;BYMONTH=3D10;BYDAY=3D-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20201221T095802Z
LAST-MODIFIED:20201221T095838Z
DTSTAMP:20201221T095838Z
UID:a83a583e-a4b8-40d5-bb08-652fea568abd
SUMMARY:test
ATTENDEE;PARTSTAT=3DNEEDS-ACTION;ROLE=3DREQ-PARTICIPANT:mailto:support-=
test@demo.com
DTSTART;TZID=3DEurope/Zurich:20201221T110000
DTEND;TZID=3DEurope/Zurich:20201221T120000
TRANSP:OPAQUE
ORGANIZER;SENT-BY=3D"mailto:max.muster@demo.com";ROLE=3DREQ-PARTICIP=
ANT:mail
 to:tobias.brunner@vshn.ch
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
```

## Steps to reproduce

1. Create new calendar entry
2. Invite attendee by entering an e-mail address
3. Save the calendar entry
4. Invitation is sent to the invited attendee using the above posted vcalendar invitation - missing the RSVP attribute

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please file a bug in the Thunderbird / Lighting product on 
https://bugzilla.mozilla.org

My dav-provider is just doing resource discovery and uses the integrated dav sync capabilities.
