### ISSUE TITLE
creation of an event doesn't take into account the email defined in calendar properties for the organizer

### ISSUE THREAD

**Issue by Blop3474** [jobisoft/DAV-4-TbSync#249]
## Your environment

TbSync version: 2.19
DAV-4-TbSync version: 1.24
Thunderbird version: 78.6.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
In case you have more than1 account.
When I create an event, I'd like that the organizer email is defined by the email selected in the calendar properties.

## Actual behavior
When I create an event, even if I change the email parameter in the calendar properties, the email organizer remains the same. Therefore, I have to change manually each time the first attendee (who is the organizer). I can't define the default organizer for an event.

## Steps to reproduce
define an email A in the calendar properties than create an event, the organizer could email A. Change the email A by the email B in the calendar and than create a event ... the organizer remains email A. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Probably a bug in Thunderbird itself, as I only set up caldav calendars for you in a simplified fassion. But you can disable TbSync after the calenders have been set up and calendar sync will continue to work and you probably continue to see the error -> bug in Thunderbid.

Note: This is different for carddav, where TbSync itself is managing the sync, as Thunderbird has no official carddav support.

Please close this bug if my assumptions are correct.
