### ISSUE TITLE
DecSync compatilibty 

### ISSUE THREAD

**Issue by kocjs** [jobisoft/DAV-4-TbSync#252]
[DecSync](https://github.com/39aldo39/DecSync) does offer synchronization of calendars to Thunderbird via a Radicale plug-in. Synchronization can be done trough SyncThing. It also does synchronize [tasks](tasks.org) between android devices, however those do not sync to Thunderbird. 

Is it possible to to integrate this in DAV-4 TbSync. This would allow a fully offline decentralised setup.

**Comment by jobisoft** [comment]
TbSync and its dav provider do support VTODO. You actually do not need TbSync for that, as it only actually adds CardDAV support. For CalDAV it uses the built-in CalDAV support from Thunderbird and only helps you to discover the resources).

The only thing I can see here, TbSync might not be able to discover your DecSync resources, but you should still be able to add them manually to Thunderbird.

**Comment by kocjs** [comment]
I see, thank you.
