### ISSUE TITLE
Synchronization Issues and Apparent Resets

### ISSUE THREAD

**Issue by ganakee** [jobisoft/DAV-4-TbSync#254]
## Your environment

TbSync version: 2.12
DAV-4-TbSync version: 1.12
Thunderbird version: 68.10.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
1) Install CALDAV & CARD DAV.
2) Add CARDDAV calendar
3) Periodic sync setup. enable and synchronize.
4) Calendar should simply sync.

## Actual behavior
1) Install CALDAV & CARD DAV.
2) Add CARDDAV calendar
3) Specify Enable and Synchronize this account.
4) Odd Behaviours
a) The calendar appears to sync. The calendar pulls all older events and lists them as overdue. This repeats periodically. Using Dismiss All does not really work as a separate window opens for each asking whether to update the old event.
b) If you set a custom calendar colour, the colour changes back to default colour. This occurs every time you close Thunderbird and reopen.
as I followed this issue, (b) seems to give a clue regarding the overall behaaviour. The calendar seems to completely reset with each sync. At first I thought this was something that I was doing. But if I change the custom color, then wait a few minutes, the calendar color mysteriously resets the calendar to default. My synchronize schedule is 7 minutes.

## Steps to reproduce
1) Install CALDAV & CARD DAV.
2) Add CARDDAV calendar
3) Specify Enable and Synchronize this account.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
I enabled logging and click the View debug log button. Nothing happens. Not sure how to email this to you. (I don't want to attach it to this report.)

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
