### ISSUE TITLE
Thunderbird freeze sometimes after install and configure TbSync and DAV-4-TbSync

### ISSUE THREAD

**Issue by danjde** [jobisoft/DAV-4-TbSync#255]
## Your environment

> TbSync version: Version 2.19
> DAV-4-TbSync version: Version 1.24
> Thunderbird version: 78.x

> I have NOT installed the latest available beta version from 
> https://tbsync.jobisoft.de
> and my issue is not yet fixed, I can still reproduce it.

Hi Devs,
I've installed on Mac Book Sierra 10.12.6, TbSync and DAV-4-TbSync for sync contact and calendar from Nextcloud (19.x).
These synchronizations works fine for all, but sometimes Thunderbirds hangs (rotating wheel).
I've inserted user and password two time: 

1) into calendar Thunderbird, as video shown: https://server.3x1t.org/cloud/index.php/s/Mf962yoEjNsmSJB
2) then again I've setup DAV-4-TbSync/tbsync Carddav and Caldav using the same username/password couple and abslolute Nextcloud path, as picture below:

![Tbsync_contacts+calendar](https://user-images.githubusercontent.com/4129294/105071209-92340e00-5a84-11eb-89d5-3eb7e230bd97.png)

Could be the double setup the problem?

> To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I will do soon it, actually the computer is not mine and not in my availability.

Thanks!

**Comment by jobisoft** [comment]
TbSync should detect the existig calendar and not create a new one. Is this still an issue with Thunderbird 102?

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.
