### ISSUE TITLE
Contact Groups & ownCloud

### ISSUE THREAD

**Issue by stabledave** [jobisoft/DAV-4-TbSync#259]
## Your environment

TbSync version: 2.21
DAV-4-TbSync version: 1.24
Thunderbird version: 78.9.0 (32)
owncloud-Server 10.7

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Syncing contacts via owncloud contacts app 
contacts can have assigned group via contacts app (webinterface)
tb sync should sync those groups as contact lists with option checked as suggested by option label 

## Actual behavior
Group info is not synced, addon won't create a list.
However if you create a list in tb book >> list will sync as contact (seperate vcard)

## Steps to reproduce
create and sync contacts

I think the problems boils down to information management. List in Thunderbird syncs to below, so list vcard with member uuid:

> BEGIN:VCARD
> VERSION:3.0
> FN:**testGroupTB**
> N:testGroupTB;;;;
> X-ADDRESSBOOKSERVER-KIND:group
> UID:4529f96e-eae0-4cff-9a3e-d725b05442b2
> **X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:bfd3dc0b-c4ad-47ea-8642-1b73b5208ac2
> X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:7c0c5d46-9413-4f47-8e35-73a24850a679**
> END:VCARD

while owncloud stores group information in member vcard:

> BEGIN:VCARD
> VERSION:3.0
> N:;User;;;
> TEL;TYPE=VOICE,WORK:123456
> TEL;TYPE=HOME,VOICE:01234
> FN:User
> PRODID:-//dmfs.org//mimedir.vcard//EN
> REV:20210406T074742Z
> UID:9cf9638a-0ea1-41f9-9ac6-72c0ae74a6f0
> **CATEGORIES:testGroupOC**
> END:VCARD

I guess for lists to sync from oc > tb, addon has to create lists from CATEGORIES: subdata. Is this OC specific?

**Comment by jobisoft** [comment]
Will not be fixed before the transition to the new WebExtension
framework is done and we have switched to using the new addressBook API
(or even using the internal CardDAV support added in TB91).

**Comment by stabledave** [comment]
any idea if this is a known issue or oc problem? any idea if other vcard provider store information with 1 vcard per 1 list? 
Id like to invest energy in the fix

**Comment by jobisoft** [comment]
Issue in TbSync. The underlying Thunderbird methods handling lists have changed and I would need to update TbSync, but I do not want to invest time into something that is on death row. The list handling stuff is a mess and I actually have no idea what needs to change and I probably need way too much time to get behind it. 

You are of course free to investigate, I will accept a (very appreciated) fix.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists.
