### ISSUE TITLE
Problems with self-signed certificate

### ISSUE THREAD

**Issue by frpp9512** [jobisoft/DAV-4-TbSync#261]
## Your environment

TbSync version: 2.21
DAV-4-TbSync version: 1.24
Thunderbird version: 78.10.0 x86

## Expected behavior
If I have a self-signed certificate, I should add it to Thunderbird and that allows me to add an account with a service that use that certificate.

## Actual behavior
I have a Nextcloud server I'm using internally in a small business, it is installer with a self-signed certificate. I've already add the certificate to Thunderbird, but when I try to add the CalDAV account it throws the unknown ssl error.

## Steps to reproduce
1. Add the self-signed certificate to Thunderbird
2. Try to add the CalDAV account

**Comment by TommySchwartz** [comment]
I have the exact same problem.

TB 78.10.1
TbSync 2.21
DAV-4-TbSync: 1.24

[debug.log](https://github.com/jobisoft/DAV-4-TbSync/files/6443450/debug.log)

**Comment by jobisoft** [comment]
IIRC, you need to use a FQDN instead of an IP for https certs.
