### ISSUE TITLE
iCloud Reminders iOS 14.4.2 after "update"

### ISSUE THREAD

**Issue by clemenskrenn** [jobisoft/DAV-4-TbSync#262]
## Your environment

TbSync version: 2.21
DAV-4-TbSync version: 1.24
Thunderbird version: 78.10.1 (32 bit)

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Creating a Reminder on my iPhone syncs it to Thunderbird and vice versa.

## Actual behavior
When a Reminder is created on the iPhone Reminders app, it stays there and TB-Sync can't get it.
When a Reminder is created in Reminders of Thunderbird, it stays there but is not shown in the Reminders app.

## Steps to reproduce
- Add iCloud account with CalDAV CardDAV to TB-Sync
- Activate Sync "Erinnerungen" or "Reminders" 
- Create reminder in iPhone app, and created reminder in Thunderbird
- Both will be stored, but it's not synchronized

![Capture](https://user-images.githubusercontent.com/42521518/117572236-460fe680-b0d2-11eb-9d19-908e178c3578.JPG)

The issue came up, when I pressed the updated button in my Reminders app. Before i did that, there were two items, Tasks and Journal. After clicking the update button in iPhone Reminders App, The Tasks and Journal disappeared and there was only the "Erinnerungen" with the Exclamation Triangle at the end left. Afterwards the syncing didn't work anymore.

I think this "update" button is some kind of migration, https://support.apple.com/en-us/HT210220.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
the new reminders are decoupled from the reminders caldav calendar.
