### ISSUE TITLE
Cannot create new calendar based on google-account

### ISSUE THREAD

**Issue by rg-user** [jobisoft/DAV-4-TbSync#263]
## Your environment

TbSync version: 2.21
DAV-4-TbSync version: 1.24
Thunderbird version: 78.10.2 (64-Bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Want to create new calender based on google-account

## Actual behavior
Error: "Die Abfrage von "gmail.com" lieferte nicht die benötigten Informationen bzgl. der CalDAV und CardDAV Service-Endpunkte. Bitte geben Sie den Hostnamen ihres Servers an, um mit der automatischen Konfiguration fortzufahren."

Unbekannter Server Fehler (HTTP Fehler 500)
URL:
https://calendar.google.com/.well-known/caldav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "errors": [
      {
        "message": "Internal error encountered.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "INTERNAL"
  }
}

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/DAV-4-TbSync/issues/240

**Comment by rg-user** [comment]
Sorry, didn't know that google is no longer supported. 
But thks for the link; the experimental setup worked for me. 
Best
