### ISSUE TITLE
CalDav-GMX Europe Server is no longer supported

### ISSUE THREAD

**Issue by Kakadus** [jobisoft/DAV-4-TbSync#265]
## My environment

TbSync version: 2.19.1
DAV-4-TbSync version: 1.24.2
Thunderbird version: 78.11.0

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
After entering the correct credentials, you are logged in successfully.

## Actual behavior
status.service-provider-setup-failed

HTTP-Error 404
URL:
https://kalender-bs-ddos.gmx.net/begenda/dav/users/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
```
<!DOCTYPE html>
<html lang="de" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://www.w3.org/1999/xhtml">
<head>
    <title>GMX</title>
    <meta charset="UTF-8"/>
    <meta http-equiv="imagetoolbar" content="false"/>
...
```
(standard GMX error page)
## Steps to reproduce
1. Try to add a new GMX.net (Europe) account
2. Enter username and password (actually can be filled with random values)
3. Klick 'Next'

TbSync tries to access GMX's CalDav server under https://kalender-bs-ddos.gmx.net/begenda/dav/users/, which seems to be no longer supported. I suggest to switch to https://caldav.gmx.net instead.

**Comment by jobisoft** [comment]
Is auto detection working for gmx (the first entry in the list) ? For caldav and carddav?

**Comment by Kakadus** [comment]
No, neither for caldav nor carddav. 
With Caldav, the DNS-lookup is successful but still delivers the wrong adress:
```
SRV record @ _caldavs._tcp.gmx.de
{"prio":1,"weight":1,"host":"kalender-bs-ddos.gmx.net","port":443,"type":33,"nsclass":0,"ttl":86335}

TXT record @ _caldavs._tcp.gmx.de
{"data":"path=/begenda/dav/users/","type":16,"nsclass":0,"ttl":86336}

(And then the same 404 error is shown)
```


With CardDav, the DNS request fails 
`SRV record @ _carddavs._tcp.gmx.de`

Then a 404 error
```
URL:
https://gmx.de/.well-known/carddav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
<!DOCTYPE html>
<html xmlns:wicket="http://www.w3.org/1999/xhtml" style="--col-count:4;" data-content-login="">
  <head>
...
```

**Comment by Kakadus** [comment]
Oh, I'm using a german email, (ending with @gmx.de). This is the issue with the last DNS lookup concerning carddav. It succeeds when I set gmx.net as the server. 
Still, carddav is unavailable.

**Comment by Kakadus** [comment]
I just noticed that carddav works again using the same link as before. Seemingly, GMX changed their server structure. Whatsoever, it works again!

**Comment by Kakadus** [comment]
PS: Auto detection works as well 👍
