### ISSUE TITLE
TB syncs calendar down, not up; doesn't sync contacts at all.

### ISSUE THREAD

**Issue by paul1149** [jobisoft/DAV-4-TbSync#266]
I'm connected to the webmail at vivaldi.net, which uses RoundCube. The Provider for CalDAV and CardDav addon seems to have populated its fields well. TB will sync down events from the remote server, but will not sync up events created local to the server. Contacts are not synced at all.

Thanks for any help you can give.

## Your environment

TbSync version:   2.22
DAV-4-TbSync version:  (Provider for CalDAV???: 1.24)
Thunderbird version:   78.11.0, on Linux.

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.
-- No, have not done that.

## Expected behavior
...  sync cals and contacts in both direction

## Actual behavior
... cal syncs down to TB, but not up to server
... contacts do not sync at all

## Steps to reproduce
... Create test entries in local and remote cals and contacts
... perform manual sync via TbSync interface

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by neandr** [comment]
Just installed TB91.2.1, TbSync 3.0.1, Provider für CalDAV & CardDAV  2.0.2
and all works as expected. 
Tested with iOS 15.1: TBAB <--> iCloud Contacts and Lightning <--> fruux/iCloud events

**Comment by paul1149** [comment]
Thanks. Will test when I can install TB 91.
