### ISSUE TITLE
TbSync does not detect DAV-4-TbSync on TB 91.x

### ISSUE THREAD

**Issue by FelicitusNeko** [jobisoft/DAV-4-TbSync#267]
## Your environment

TbSync version: 2.22
DAV-4-TbSync version: 1.24
Thunderbird version: 91.0.1

## Expected behavior
The previously set-up DAV account will continue to sync after upgrading Thunderbird.

## Actual behavior
TbSync does not detect DAV-4-TbSync after upgrading Thunderbird. Existing accounts are disabled, and new accounts cannot be registered.

## Steps to reproduce
1. Set up a DAV account on Thunderbird 78.x
2. Upgrade to Thunderbird 91.0.1

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
[debug.log](https://github.com/jobisoft/DAV-4-TbSync/files/7016641/debug.log)

**Comment by jobisoft** [comment]
You need DAV 2.0.2
https://addons.thunderbird.net/addon/dav-4-tbsync/versions/?page=1#version-2.0.2

and TbSync 3.0.1
https://addons.thunderbird.net/addon/tbsync/versions/?page=1#version-3.0.1

Google as part of DAV is no longer supported, use
https://addons.thunderbird.net/de/thunderbird/addon/google-4-tbsync/versions/?page=1#version-0.2.1
