### ISSUE TITLE
Birthday reminders cannot be closed

### ISSUE THREAD

**Issue by Weasy666** [jobisoft/DAV-4-TbSync#270]
## Your environment

TbSync version: 3.0.1
DAV-4-TbSync version: 2.0.2
Thunderbird version: 91.1.0 (64-Bit)

## Expected behavior
Clicking the `close`-button of a reminder entry actually closes/remoses that reminder entry.

## Actual behavior
Clicking the `close`-button does nothing. The reminder still remains, even between Thunderbird starts.

## Steps to reproduce
I don't know if it can be reproduced easily, but i know at least one other person with the same problem.
The calendar in question is the birthday calendar of my contacts of a Nextcloud 22 instance. And the problem began to occure
after updating Thunderbird from 78 to 91 last week.

I created a log file and took a look at it, the only thing of note/out of the ordinary were this few entries
```log
** Mon Sep 13 2021 09:16:13 GMT+0200 (Mitteleurop�ische Sommerzeit) **
[Loaded provider] : dav::CalDAV & CardDAV (2.0.2)

** Mon Sep 13 2021 09:16:13 GMT+0200 (Mitteleurop�ische Sommerzeit) **
[EventLog] : The IANA timezone <America/Nuuk> cannot be mapped to any Exchange timezone.

** Mon Sep 13 2021 09:16:13 GMT+0200 (Mitteleurop�ische Sommerzeit) **
[EventLog] : The IANA timezone <Antarctica/Troll> cannot be mapped to any Exchange timezone.
```

**Comment by stevenrbrandt** [comment]
I frequently have reminders that cannot be dismissed. I have to delete the event to make the reminder stop happening.

**Comment by jobisoft** [comment]
That is probably not an TbSync issue. For the calendar part for caldav, I just set up the calendars and let lightning/TB manage them.

**Comment by Weasy666** [comment]
Yeah, looks like a bug in the calendar, a few repords on bugzilla [1693266](https://bugzilla.mozilla.org/show_bug.cgi?id=1693266), [1728803](https://bugzilla.mozilla.org/show_bug.cgi?id=1728803).
So i will close this issue.
