### ISSUE TITLE
status.service-provider-setup-failed

### ISSUE THREAD

**Issue by oliviercailloux** [jobisoft/DAV-4-TbSync#271]
## Environment

TbSync version: [2.19-1](https://packages.debian.org/bullseye/webext-tbsync)
DAV-4-TbSync version: [1.23-1](https://packages.debian.org/bullseye/webext-dav4tbsync)
Thunderbird version: [78.12.0-1](https://packages.debian.org/bullseye/thunderbird)

## Expected behavior
Sync starts

## Actual behavior
Fails to start with `status.service-provider-setup-failed`

## Steps to reproduce
Install TBSync, try to add Fruux account, enter any username & password, click next, observe the message that appears in the bottom part of the window: “status.service-provider-setup-failed”. TBSync won’t go further.

Debug log (maximal verbosity level) is simply:
```
** Fri Sep 24 2021 18:19:18 GMT+0200 (CEST) **
[URL Request #1] : https://dav.fruux.com

** Fri Sep 24 2021 18:19:18 GMT+0200 (CEST) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
```
 Two more such entries appear each time I try. Nothing else.

Reading #202, I tried to install [libc6-dev](https://packages.debian.org/bullseye/libc6-dev) ([containing `libresolv.so`](https://packages.debian.org/bullseye/amd64/libc6-dev/filelist)), rebooted, but the problem persists.

I realize that it may be a packaging issue. Perhaps you could at least provide a stack trace in the debug log, or something similar that would indicate what fails, so that the user has a chance to see which library is missing?

Thanks for any help.

**Comment by oliviercailloux** [comment]
BTW I have no idea how the poster of #202 obtained the error message shown there (which is much more useful than the only one I could get). Any idea?

**Comment by jobisoft** [comment]
Is this still an issue? Sorry for not getting back faster.
