### ISSUE TITLE
After upgrading the Reminders app in iOS 13 as suggested by Apple my iCloud task lists are not listed any more

### ISSUE THREAD

**Issue by reteP-riS** [jobisoft/DAV-4-TbSync#272]
## Your environment

TbSync version: 2.22
DAV-4-TbSync version: 1.24
Thunderbird version: 78.14.0 (32-Bit)

## Expected behavior
Under TBsync Account Management > Account Configuration > Synchronization Status (or whatever the correct english wording might be) all my task lists should be listed.

## Actual behavior
After upgrading the Reminders app in iOS 13 as suggested by Apple my iCloud task lists are not listed any more and consequently they are no longer being synchronized. In Thunderbird the Task tab shows all task lists as "disconnected; deleted on server" and activation fails. This seems to be related to what Apple describes in https://support.apple.com/HT210220

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Apple is evil. 

By "suggesting" to upgrade your tasks, they moved them from the CalDAV server to a proprietary apple server. Your tasks are no longer accessible by CalDAV. Not by TbSync or any other CalDAV client. The iOS app is of course is able to do that, because it knows how to access the proprietary server.

That is called vendor lock. You got fooled.

**Comment by reteP-riS** [comment]
I had avoided this upgrade for quite a while because I suspected "something", but in a moment of amnesia I pressed that damned button...

For the record: they not only tricked me into this vendor lock, but they rendered my old iPad almost unusable because the Apple task lists no longer work with iOS 12 and versions older than that. And by the way, they are kind of smart - or should I say devious - with those things because you can't even restore the old task lists from a backup.

Anyway, thanks for replying so quickly!
