### ISSUE TITLE
Contact photos are not imported from icloud

### ISSUE THREAD

**Issue by 5crambler** [jobisoft/DAV-4-TbSync#276]
## Your environment

TbSync version: 3.01
DAV-4-TbSync version: 2.0.2
Thunderbird version: 91.5.1 (64 bit)
Windows 10 x64

## Expected behavior
icloud contacts should import pictures/photos

## Actual behavior
icloud import fails to include pictures/photos

## Steps to reproduce
import iCloud contacts

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
Sorry, but I don't want to share all my private contacts here. How else can this issue get resolved? Apparently it is a common problem amongst all iCloud users...
![Screenshot 2022-01-27 TbSync icloud photos](https://user-images.githubusercontent.com/83308760/153107395-f418913a-14a7-4229-bf68-97b2727254f4.png)

**Comment by jobisoft** [comment]
I work on issues when I find time. You are free to submit fixes.

**Comment by 5crambler** [comment]
I'm user of this SW, not the developer!
Very disappointing, I have to admit...

**Comment by jobisoft** [comment]
I am the developer, but this is a hobby and I am not getting paid for this, so I can only work on this in my free time, which is only little. This is open source, so everybody can help.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists.
