### ISSUE TITLE
Please tag Version 2.x

### ISSUE THREAD

**Issue by Mechtilde** [jobisoft/DAV-4-TbSync#278]
## Your environment

TbSync version:
DAV-4-TbSync version:
Thunderbird version:

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Done.
