### ISSUE TITLE
Propfind request results in 405 Error

### ISSUE THREAD

**Issue by eplinux** [jobisoft/DAV-4-TbSync#280]
## Your environment

TbSync version: 3.0.2
DAV-4-TbSync version: 2.0.2
Thunderbird version: 91.0.0

## Expected behavior
Syncing with Nextcloud

## Actual behavior
Failing to sync:
"Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
<title>405 Method Not Allowed</title>
</head>
<body>
<h1>Method Not Allowed</h1>
<p>The requested method PROPFIND is not allowed for this URL.</p>
</body>
</html>

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Thunderbird itself supports CardDAV address books by now and I have not put much time in my obsolete add-on.

When TB 102 is released in one or two weeks, its address book even supports vCards natively:
![grafik](https://user-images.githubusercontent.com/5830621/175385860-a829098e-7e65-46d5-b563-8f27ce92cccf.png)

Give Beta 102 a try: https://www.thunderbird.net
Download link on bottom right.

**Comment by richard-dg** [comment]
Great. I missed that part. Thanks for the info. :-) So, for me everything's solved.
