### ISSUE TITLE
Feat: add a checkbow to select all caldav and carddav in one time

### ISSUE THREAD

**Issue by PhilippeAccorsi** [jobisoft/DAV-4-TbSync#281]
## Your environment

TbSync version: 3.0.2
DAV-4-TbSync version: 2.0.2
Thunderbird version: 91.9.1

## Expected behavior

Have a check box on top of column to check/uncheck all checkbox quickly.

## Actual behavior

We use this tool to connect all [tracim](https://github.com/tracim/tracim) agenda in thunderbird. But when we have many agenda and address book, we need to check all line manually (this is very long when we have more than 10 agenda)

## Steps to reproduce

Use https://demo.tracim.fr and connect agenda in thunderbird (just need to use default account. Information available directly [here](https://www.algoo.fr/fr/tracim/demo) )

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.
