### ISSUE TITLE
CalDAV/VJOURNAL support for notes

### ISSUE THREAD

**Issue by combrs** [jobisoft/DAV-4-TbSync#285]
## Your environment
Thunderbird 91/Ubuntu 22.04

REQUEST FOR FEATURE/ENHANCEMENT
Group of andoid developers in cooperation with Nextcloud developers create app for android 
https://www.reddit.com/r/fossdroid/comments/tu4kdi/dev_first_foss_app_to_synchronize_journals_notes/
[jtx Board](https://jtx.techbee.at/) (GPLv3) is the first and only app on Android that can track Journals and Notes via the open protocol VJOURNAL.

But this lack of support in other clients, like web or desktop clients:
https://github.com/nextcloud/tasks/issues/1955
https://www.reddit.com/r/fossdroid/comments/tu4kdi/comment/ic38qox/?utm_source=share&utm_medium=web2x&context=3

Are you interested or know how to support it in Thunderbird?
Maybe with https://github.com/jobisoft/DAV-4-TbSync/issues/282 simultaneously?

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.
