### ISSUE TITLE
Merges unrelated contacts (quite major issue)

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/DAV-4-TbSync#30]
_From @poVoq on September 18, 2018 12:7_

## Your environment

TbSync version: Dev version updated 30.August
Thunderbird version: 60.0 (Windows10)

[ x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When right clicking on contact in mail interface and selecting "edit contact" and then changing the Addressbook from a local to a CardDAV one it should copy the contact and delete it in the local one.

## Actual behavior
The contact is deleted in the local one, but merged with an existing contact in the CardDAV Calendar (Some field get overwritten others ramain). It is not clear to me if it happens at random or based on some hidden numeric ID.

## Steps to reproduce
See above.

_Copied from original issue: jobisoft/TbSync#123_

**Comment by mMuck** [comment]
I saw this behavior over several years now with SoGo Connector and the local "collected addresses" AB when I changed the AB from the local to the remote one. So this might be related to a greater context and not to TbSync itself.
But, correct: Very critical. I'm glad I searched the entry afterwards and realized the overwritten fields/merged fields. No new entry was applied to the remote AB. I did no checks. Perhaps it's the same behavior with two local ABs and this is - as you mentioned - a problem with the underlying ID.
I'm not in that TB dev stuff - could you please pass this on to the TB team and open an issue there? Thanks!

**Comment by jobisoft** [comment]
I will start investigating this mid December and will get back to you.

**Comment by jobisoft** [comment]
With TB 60.5 every contact now gets a UID. Maybe that fixes the problem? Can you check?

Does this also happens, when you drag‘n‘drop a contact from one address book to another?

**Comment by poVoq** [comment]
I noticed that after upgrading I had a lot more of these mixed contacts, but I guess that was just the transition?

**Comment by jobisoft** [comment]
If you disable and re-enable TbSync accounts (without syncing), all local modification are thrown away and you start with a fresh copy of your Contacts. Can you observe the behavior with TB 60.5.

And just to be sure, please switch to beta of TbSync before re-enabling your accounts:
https://tbsync.jobisoft.de

**Comment by jobisoft** [comment]
Are we talking about this dialog:
![image](https://user-images.githubusercontent.com/5830621/52782646-dffd9b80-304f-11e9-8db3-c87ebed36ef1.png)

And not about dialogs from the actuall adressbook?

**Comment by poVoq** [comment]
Yeah, but by now things have gotten so confusing that I probably have to purge my entire address book and start new. Not a big deal, but I can't say for sure what is causing the issues and how to replicate as I have a lot of old "mixed" contacts by now. Not a bit deal though :)

**Comment by jobisoft** [comment]
That „switch address book function“ is a core TB function. TbSync only acts upon new or modified cards after they have been added/modified. If you observe merging of cards by using that switcher, it happens before TbSync sees them.

With new UID added to all cards starting with TB 60.4, this could be resolved? 

I think this issue is unrelated toy TbSync.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
