### ISSUE TITLE
"CELL tag for mobile on iCloud contacts

### ISSUE THREAD

**Issue by macmpi** [jobisoft/DAV-4-TbSync#304]
## Your environment

TbSync version: 4.1
DAV-4-TbSync version: 4.1
Thunderbird version: 102.3.0

## Expected behavior
iCloud contact mobile category name unchanged

## Actual behavior
After sync mobile category is replaced by "CELL on synced contacts

This is new with recent updates. In pre 4.x with earlier TB, phone number categories were not affected.
Thanks for all the hard & rush work to maintain plugins with recent TB updates!

**Comment by jobisoft** [comment]
I do nog have own sync code in place anymore (you can disable TbSync after everything was setup). So any sync issue is an issue with Thunderbirds native sync code.

But... the correct type def for mobile phone numbers is "cell".

**Comment by macmpi** [comment]
Ok, thanks for prompt reply.
Dunno why it is all sudden shown capitalized & truncated on iPhone...
Will try to find where to report on TB side then.
