### ISSUE TITLE
Mozilla Thunderbird 102 will not connect to CalDav and CardDav Resources.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [jobisoft/DAV-4-TbSync#305]
## Your environment

TbSync version:
DAV-4-TbSync version:
Thunderbird version:
The version I have of Thunderbird is:
Name        : MozillaThunderbird
Version     : 102.2.2
Release     : 150200.8.82.1
Architecture: x86_64
Install Date: Tue 20 Sep 2022 07:41:03 AM EDT
Group       : Productivity/Networking/Email/Clients
Size        : 241733671
License     : MPL-2.0
Signature   : RSA/SHA256, Mon 12 Sep 2022 07:27:51 AM EDT, Key ID 70af9e8139db7c82
Source RPM  : MozillaThunderbird-102.2.2-150200.8.82.1.src.rpm
Build Date  : Mon 12 Sep 2022 07:14:16 AM EDT
Build Host  : goat04
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : https://www.thunderbird.net/
Summary     : An integrated email, news feeds, chat, and newsgroups client

## Actual behavior
...Mozilla Thunderbird 102 will not connect to CalDav and Card Dav Resources. I use eGroupware to connect to manage Address book, Calendars and Task resources. Upon updating to 102, The TbSync was disabled and when I tried using a beta from github for connecting Thunderbird 102 to TbSync, it seemingly succeeded but no Contacts were Synced.

I thought that maybe it had purged my eGroupware contacts database. This turned out not to be the case. I then tried using Thunderbird's native method, this failed too.

I use the eGroupware-docker package. I have removed the plugin to attempt to use Thunderbird's CardDav and CalDav Sources. The same thing happens. Thunderbird acts as if its going to connect, hangs there as if it is processing, and after a while gives up.

TbSync is listed as incompatible with Thunderbird 102. (the version on the Thunderbird Addon Page says that), but you can side load a beta XPI from github produced by the author. It doesn't work either. It downloads Zero contacts.

I can confirm it works with Evolution - it also works if I roll back to Mozilla Thunderbird 90.15 or whatever.

I've recently found out that I can add new entries to the address book, but not retrieve any. My CardDav Resource is a Dockerized eGroupware instance.

A

## Steps to reproduce
...I can confirm it works with Evolution - it also works if I roll back to Mozilla Thunderbird 90.15 or whatever.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Zombie-Ryushu** [comment]
carddav.sync: Sync with server failed. [CardDAVDirectory.jsm:594:11](resource:///modules/CardDAVDirectory.jsm)
    syncWithServer resource:///modules/CardDAVDirectory.jsm:594
NS_ERROR_FAILURE: Authorization failure [CardDAVUtils.jsm:209](resource:///modules/CardDAVUtils.jsm)
NS_ERROR_FAILURE: This login already exists. [LoginHelper.jsm:1762](resource://gre/modules/LoginHelper.jsm)
    createLoginAlreadyExistsError resource://gre/modules/LoginHelper.jsm:1762
    addLogin resource://gre/modules/LoginManager.jsm:323
    saveAuth resource:///modules/CardDAVUtils.jsm:678
    create resource:///modules/CardDAVUtils.jsm:564
    <anonymous> chrome://messenger/content/addressbook/abCardDAVDialog.js:226
    _fireButtonEvent chrome://global/content/elements/dialog.js:495
    _doButtonCommand chrome://global/content/elements/dialog.js:474
    _handleButtonCommand chrome://global/content/elements/dialog.js:468
    _handleButtonCommand self-hosted:1121
[Exception... "This login already exists."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/LoginHelper.jsm :: createLoginAlreadyExistsError :: line 1762"  data: yes] [LoginHelper.jsm:1762:23](resource://gre/modules/LoginHelper.jsm)
    createLoginAlreadyExistsError resource://gre/modules/LoginHelper.jsm:1762
    addLogin resource://gre/modules/LoginManager.jsm:323
    saveAuth resource:///modules/CardDAVUtils.jsm:678
    create resource:///modules/CardDAVUtils.jsm:564
    <anonymous> chrome://messenger/content/addressbook/abCardDAVDialog.js:226
    _fireButtonEvent chrome://global/content/elements/dialog.js:495
    _doButtonCommand chrome://global/content/elements/dialog.js:474
    _handleButtonCommand chrome://global/content/elements/dialog.js:468
    _handleButtonCommand self-hosted:1121
[Exception... "Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.extractScheme]"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: jar:file:///home/masterz/.thunderbird/r7e0jp33.default/extensions/owl@beonex.com.xpi!/webapi/webaccount/uiOverlay.js :: overlayListener :: line 190"  data: no]

**Comment by jobisoft** [comment]
https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync
