### ISSUE TITLE
Status 405 error when trying to use cardDAV with nextcloud

### ISSUE THREAD

**Issue by herzogmedia** [jobisoft/DAV-4-TbSync#306]
## Your environment

TbSync version: 4.3
DAV-4-TbSync version: 4.3
Thunderbird version: 102.3.3

## Expected behavior
When adding a new DAV-Server with automatic discovery, both cardDAV and calDAV should work as expected.

## Actual behavior
TBSync stops syncing with error "status.405". Error message in event protocol:
```
URL:
https://[ServerName]/remote.php/dav/addressbooks/groups/test/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
```
Using only CalDAV works flawlessly. 

## Steps to reproduce
- Add a new account for caldav and carddav
- fill out all necessary fields

Debug log will be sent to you asap.
Thanks in advance!

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.
