### ISSUE TITLE
Error preventing syncing calendars from Nextcloud 24

### ISSUE THREAD

**Issue by powerriegel** [jobisoft/DAV-4-TbSync#309]
## Your environment

TbSync version: 4-3
DAV-4-TbSync version:4.3
Thunderbird version: 102.4.2 (ubuntu 22.04)
Nextcloud version 24.0.6

## Expected behavior
Sync to Nextcloud calendar should work

## Actual behavior
Sync fails, see attached error message
![Bildschirmfoto vom 2022-11-15 08-57-18](https://user-images.githubusercontent.com/11870663/201862712-bd0120b4-d197-4234-8c08-8f6c8ceada47.png)

## Steps to reproduce
Add calendar (automatic)
detection works
select one calendar
click sync

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

There is also an 404 error which **seems to be ignored**

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: groups in 'addressbooks'</s:message>
</d:error>

**Comment by TommyOe1** [comment]
try to switch off "offline support" under option of your account. with icloud it worked

**Comment by powerriegel** [comment]
Issue solved! Thank you so much! But the error message could really be more concise.

**Comment by powerriegel** [comment]
Closed
