### ISSUE TITLE
sync is deleting birthdays from my online addressbook

### ISSUE THREAD

**Issue by brad2014** [jobisoft/DAV-4-TbSync#31]
The bug I'm seeing is that sync is deleting birthdays from my online addressbook.  I'll spell it out here for the record.  Probably related to issue #10 .

## My setup:
- Nextcloud 14.0.3 using sabre/dav 3.2.2
- Thunderbird 60.3.0 (hot off the press)
- TBSync 0.7.18 
- Sabre/dav provider 0.8.29.

## To reproduce
- Sync download to TB a contact containing a RFC6350 birthday (e.g. one created on Nextcloud)
- On the TB addressbook contact edit form, edit any other field in that contact (say display name)
- Sync upload the updated contact from TB to Nextcloud

## Expected behavior
- The birthday would be visible in the edit form, 
- On upload, it would be unchanged on the server.

## Actual behavior
- the birthday field is deleted on the client (as soon as I save my unrelated edit)
- the birthday field is deleted on the server (as soon as I sync upload the locally edited contact)
- I am sad.

## More notes

Contacts created via the Nextcloud web app contain valid [RFC6350](https://tools.ietf.org/html/rfc6350#page-30) birthday dates:  
```
BDAY:19711015
```

After downloading such a contact to TB, the birthday appears in the Contact Pane as 19711015.

![image](https://user-images.githubusercontent.com/6502462/48464687-3202fc80-e795-11e8-9554-6bd17fcecd4e.png)

However, on the data entry form, the birthday is blank, and if I modify any field and save (e.g. the display name of the contact), the birthday field in the Contact Pane disappears.

![image](https://user-images.githubusercontent.com/6502462/48465769-c7ec5680-e798-11e8-926d-e72acdd3f093.png)

If I reenter the birthday into the same contact via the data entry form, it appears in the contact pane in words (this makes me think TB actually understands the date):

![image](https://user-images.githubusercontent.com/6502462/48464859-d7b66b80-e795-11e8-9a4d-2a8afcdff064.png)

And when that is sync'ed to the server, the server receives the vcard in obsolete [RFC2426](https://tools.ietf.org/html/rfc2426#page-11) format:

BDAY:1971-10-15

Nextcloud/sabre is correctly updating its birthday calendar given the obsolete BDAY format (with hyphens),  so the only breakdown in the process seems to be at the point DAV-4-TbSync takes the vcard BDAY in RFC6350 format and stuffs it into the TB addressbook card.

But I think it would be saintly to convert the Thunderbird birthdays to RFC6350 YYMMDD format before shipping to the CalDAV server.

**Comment by brad2014** [comment]
I have a fix I'm using locally.  I'll send a PR to you, which you are welcome to, if you like it.

**Comment by jobisoft** [comment]
Pulled. I will keep this open, until a new version including this fix has been released.

**Comment by jobisoft** [comment]
v0.9 is out
