### ISSUE TITLE
iCloud Events Disappear

### ISSUE THREAD

**Issue by ShortPutt** [jobisoft/DAV-4-TbSync#310]
## Your environment
Windows 10 Pro
TbSync version: 4.3
DAV-4-TbSync version: 4.3
Thunderbird version: 102.6.0

## Expected behavior
Calendar events sync between Thunderbird Calendar and iCloud.

## Actual behavior
Calendar events disappear from the Thunderbird Calendar. This has been happening for a while now. When they disappear from the Thunderbird Calendar they can still be seen from Windows iCloud - so they are still on the iCloud calendar.

## Steps to reproduce
I can't reproduce an event disappearing, but when it does happen I've found the following

If I update the calendar event on Windows iCloud, it will usually reappear on Thunderbird. Usually, but not always. 

If i delete the iCloud account from tbSync and re-add it, the missing calendar items reappear on the Thunderbird Calendar. This works consistently. However, if I then stop and restart Thunderbird, some events go missing again - and not necessarily the same events that were missing the first time. This is also happening consistently now.

I have an old Thunderbird on a different computer - v91.13.1, tbSync v3..02, CalDAV v 2.02 and I get similar behavior with this iCloud account - but different events go missing.

I will send logs if you think they will help. Let me know.

**Comment by jobisoft** [comment]
I would like to point you all to this document:
https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync

TbSync uses native CalDAV/CardDAV sync and it only exists because users requested to keep it due to its extended discovery methods.

There should be no difference between setting up the resources manually in Thunderbird. Please re-open this issue, if this is not the case after all.

**Comment by ShortPutt** [comment]
This should  be re-opened. It happens w/ both TbSync and w native Thunderbird CardDAV.

It happens about once a week. I use TbSync because its easier to fix it - I simply unsync the resync the calendar and all the events reappear back on the calendar.

Its a huge pain because I've missed meetings when I didn't realize events have gone missing.
I can't believe no one else is having this issue.
