### ISSUE TITLE
Compatibility with Thunderbird 115

### ISSUE THREAD

**Issue by MarcMichalsky** [jobisoft/DAV-4-TbSync#314]
## Your environment

TbSync version: [4.4-beta](https://github.com/jobisoft/TbSync/issues/669#issuecomment-1636415716)
DAV-4-TbSync version: 4.4 
Thunderbird version: 115.1.1

Could you release a version compatible with Thunderbird 115?
Thank you, I appreciate your work very much and have sent you a small donation.

**Comment by jobisoft** [comment]
A compatible version has been submitted to ATN. ETA: a few days.
