### ISSUE TITLE
China iCloud DAV provider

### ISSUE THREAD

**Issue by mlefkon** [jobisoft/DAV-4-TbSync#316]
## Your environment
Ubuntu 22.04 

TbSync version: 4.8
DAV-4-TbSync version: 4.7
Thunderbird version: 115.8.1 (64-bit)

## Expected behavior
Sync to iCloud with an AppleID registered in China

## Actual behavior
Host not found  (I forget the exact error)

## Steps to reproduce
I was able to fix the problem by editing /home/myusername/.thunderbird/2x0rw5u3.default-release/TbSync/accounts68.json
and change all 'icloud.com' --> 'icloud.com.cn'
Maybe there needs to be another iCloud DAV provider specific to China to make this easier for users.
Or, at least, make the Card/CalDAV server addresses under the 'Account Settings' tab editable. (right now they are disabled for me)

**Comment by jobisoft** [comment]
Since I am going to sunset the DAV provider, this will not be worked on anymore.
