### ISSUE TITLE
Shared Calendars 

### ISSUE THREAD

**Issue by dagistan-tuncbilek** [jobisoft/DAV-4-TbSync#319]
## Your environment

Thunderbird version: 115.13.0 

Thank you for this library, really. I was using this for years for my and my collages shared calendars.

As i see, with the latest version of Thunderbird, i can't use this library. I read you email and you said that, Thunderbird natively supports iclud calendars. But actually, i could not manage to add shared calendars.

I added my own calendar with my specific url. But with "https://caldav.icloud.com" don't work and can't find any calendar. With this library everything was good. I researched but could not achieve to see shared calendars.

I wonder, miss i something? Please advice how can i integrate caldav to Thunderbird natively.

Thanks a lot, bets regards.

**Comment by jobisoft** [comment]
In TB 115, you have to use my dav provider. In TB 128, icloud works natively and my dav provider has been sunset.

**Comment by dagistan-tuncbilek** [comment]
Yes you are right. After upgrading to TB 128, all works as expected. Thanks a lot. 

NOT: This library is not compatible with TB 115.13.0
