### ISSUE TITLE
Feature request: when syncing, support missing year in birthday

### ISSUE THREAD

**Issue by brad2014** [jobisoft/DAV-4-TbSync#33]
Thunderbird allows me to specify a birthday with year missing, as does Apple Contacts, using a vcard3 extension.  Discussed also in #31 .

Allow sync such that birthdays with missing year are properly uploaded and downloaded, for clients that support the apple extension.  Other clients should not be affected.

**Comment by jobisoft** [comment]
Pulled. Keeping this open until release.

**Comment by jobisoft** [comment]
I have pre-released the next version. It does not only contain your fixes, but also a major rewrite of the network code. Would you give it a try?

You need 0.8.30 of the DAV provider:
https://github.com/jobisoft/DAV-4-TbSync/releases/download/v0.8/DAV-4-TbSync-0.8.30-BETA.xpi

And 0.7.19 of TbSync:
https://github.com/jobisoft/TbSync/releases/download/v0.7.19/TbSync-0.7.19.xpi

Any feedback is helpful.

**Comment by brad2014** [comment]
@jobisoft Not sure where I should ask questions... I notice new code in 0.8.30-BETA sets aAccountType for new addressbooks to TBSYNC:EAS.  Are you labeling DAV addressbooks that way intentionally?  Should it be TBSYNC:DAV?

I'll run with the new revs over the weekend.

**Comment by jobisoft** [comment]
Whoops, where?



Am 16.11.18 um 22:41 schrieb brad2014

**Comment by brad2014** [comment]
content/dav.js#L288

**Comment by jobisoft** [comment]
This is content/dav al line 288
https://github.com/jobisoft/DAV-4-TbSync/blob/master/content/dav.js#L288

I do not see any EAS reference...

**Comment by brad2014** [comment]
The 0.8.30-BETA download you linked to contains code for dav.addAddressBook() that I don't see in the master branch.  I don't see a 0.8.30-BETA tag, so I'm not sure where the code came from.

**Comment by brad2014** [comment]
correction: dav.createAddressBook(...)

**Comment by brad2014** [comment]
I'm seeing this in the download:

```
    /** 
     * Is called if TbSync needs to create a new thunderbird address book associated with an account of this provider.
     *   
     * @param newname       [in] name of the new address book
     * @param account       [in] id of the account this address book belongs to
     * @param folderID      [in] id of the folder this address book belongs to (sync target)
     *   
     * return the id of the newAddressBook
     */  
    createAddressBook: function (newname, account, folderID) {
        //This example implementation is using the standard address book, but you may use another one 
        let abManager = Components.classes["@mozilla.org/abmanager;1"].getService(Components.interfaces.nsIAbManager);

        if (tbSync.cardbook == true) {
            let accountID = cardbookUtils.getUUID();
    
            cardbookRepository.addAccountToRepository(
                    /* aAccountId */ accountID,
                    /* aAccountName */ newname, 
                    /* aAccountType */ "TBSYNC:EAS", 
                    /* aAccountUrl */ "", 
                    /* aAccountUser */ "", 
                    /* aColor */ "#ff0000", 
                    /* aEnabled */ true, 
                    /* aExpanded */ true, 
                    /* aVCard */ ["3.0"], 
                    /* aReadOnly */ false, 
                    /* aUrnuuid */ false,
                    /* aDBcached */ true, 
                    /* aAutoSyncEnabled */ false, 
                    /* aAutoSyncInterval */ 0,  
                    /* aPrefInsertion */ true    
            );  
            cardbookUtils.formatStringForOutput("addressbookCreated", [newname]);
            wdw_cardbooklog.addActivity("addressbookCreated", [newname], "addItem");
            cardbookUtils.notifyObservers("cardbook.ABAddedDirect", "accountid:" + accountID);
        }   

        return abManager.newAddressBook(newname, "", 2);
    },
```

**Comment by jobisoft** [comment]
Ah damn, I have some cardbook test code in my LOCAL branch, which is not committed. But when building the XPI, I forgot to remove that. Thanks for finding that. Will update the XPI

**Comment by jobisoft** [comment]
XPI has been updated (and the cardbook branch is online). 
FYI: You can always contact me via email: john.bieling@gmx.de

**Comment by jobisoft** [comment]
v0.9 is out
