### ISSUE TITLE
Sync status "Service nicht erreichbar"

### ISSUE THREAD

**Issue by ttjaden** [jobisoft/DAV-4-TbSync#36]
## Your environment

TbSync version: 0.7.20
DAV-4-TbSync version: 0.10
Thunderbird version: 60.2.1

[x ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Connection to my nextcloud instance should be possible. A few days ago, all was fine.

## Actual behavior
 "Sync status: Service nicht erreichbar"

## Steps to reproduce
I recognized that the calendar entries, which I did in Thunderbird, did not show up online in my nextcloud. A few days ago, this still worked. So I deleted the Account in Tbsync an wanted to set it up again. While trying this, I get the error "Sync status: Service nicht erreichbar"

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
network.cookie.same-site.enabled = false
