### ISSUE TITLE
Contributing to the wiki

### ISSUE THREAD

**Issue by monperrus** [jobisoft/DAV-4-TbSync#37]
I'd like to contribute to https://github.com/jobisoft/DAV-4-TbSync/wiki/Compatibility-list but the edit button seems deactivated. Could you allow modification?

**Comment by jobisoft** [comment]
Closing due to no feedback to collaboration invite.

**Comment by monperrus** [comment]
you're going too fast for me :)

I want to suggest the addition of a supported service:
provider "orange.fr"
server: cardav.orange.fr
comment: orange.fr offers emails to its phone subscribers as well as free email to everybody.

**Comment by jobisoft** [comment]
ok, i did not want to have a pending collaboration request longer than 48h.

what is the caldav url of orange? Or is both being served via cardav.orange.fr?

**Comment by monperrus** [comment]
I'm not using caldav but I see that caldav.orange.fr is resolved.
