### ISSUE TITLE
GMX carddav is not working 

### ISSUE THREAD

**Issue by monperrus** [jobisoft/DAV-4-TbSync#38]
I cannot get it working with carddav.gmx.net (or carddav.gmx.com). It keeps asking me for the password.

**Comment by jobisoft** [comment]
please use the latest beta:
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

and just use "gmx.net" as url (trust me)

**Comment by jobisoft** [comment]
Does it work?

**Comment by jobisoft** [comment]
The "trust me" is no longer valid :-) It looks like gmx.net and gmx.com do not share the same user database.

If you are able to login into the .net webinterface (https://www.gmx.net), than my fix in the latest beta works for you and the "gmx.net" URL will get your calendars and contacts.

If you are a gmx.com user, I currently do not know the URLs.

**Comment by jobisoft** [comment]
I fixed it in the latest beta and i have confirmation that it works for gmx.com users as well. So get the latest beta:
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

And create a new account in TbSync and use just "gmx.net" or "gmx.com" as Server Address.

**Comment by jobisoft** [comment]
@monperrus Can you provide feedback?

**Comment by monperrus** [comment]
Just tested. It works! Thanks a lot, I'm closing the issue.

**Comment by jobisoft** [comment]
I do not know your current situation, but if your beta version updated itself, GMX support is probably broken again - because I rewrote that part.

If it is still working for you, it will break soon, when the current beta lands on addons.thunderbird.net.

I suggest to update to the latest beta anyway:
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

Remove your GMX account from Tbsync and set it up anew. You will find, that there is now a dedicated GMX profile which you can select.

**Comment by monperrus** [comment]
Thanks for the notice, I will udpate.

**Comment by Reiner030** [comment]
also helped me - would be nice if this beta version would be published on TB Plugin pages, too ;)

(btw. 1st install try failed but I found luckily on https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel the hint to use the Installer https://tbsync.jobisoft.de/TbSyncBetaInstaller.xpi to also use all "must have" beta plugins... )

**Comment by jobisoft** [comment]
I know. I am working hard to get it ready for release. As you may have noticed, it has a new UI and that req. lots of changes.

**Comment by Reiner030** [comment]
ok, thx ;)

Wasn't sure how much is changing and it looks fine so far I just tested but I have only one small Office365 and one GMX calendar included...
Main problem last 1-2 month is that old URL wasn't working anymore right with updates - neither ```https://kalender.gmx.net/begenda/dav/<email>/calendar``` nor ```https://caldav.gmx.net/```
