### ISSUE TITLE
Nextcloud has error 503

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/DAV-4-TbSync#41]
There is an issue between Nextcloud and Thunderbird, which affects TbSync and Lightning. TbSync will report "Error 503" and Lightning will not load any calendar.

## Solution:

Open Thunderbird advanced config and set
**network.cookie.same-site.enabled = false**

**Comment by mbiebl** [comment]
Sounds like https://github.com/nextcloud/server/issues/10134

**Comment by jobisoft** [comment]
Correct, solution:

Open Thunderbird advanced config and set
network.cookie.same-site.enabled = false
