### ISSUE TITLE
Sync status "Service nicht erreichbar" / "service not available"

### ISSUE THREAD

**Issue by blu-IT** [jobisoft/DAV-4-TbSync#44]
## Your environment

TbSync version: 0.7.22
DAV-4-TbSync version: 0.10
Thunderbird version: 60.3.2

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
My contacts are synced with nexctcloud.

## Actual behavior
Get the message Sync status "service not available"

## Steps to reproduce
I use the setting "Use secure connection via https:// "and this seems to prevent a connection. When I uncheck the box and use http:// instead the sync works. I **don't** use a self-signed certificate for my nextcloud installation.

Regards

**Comment by jobisoft** [comment]
I would need a debug log of such a failed attempt. You can activate debug log at the help tab in the TbSync account manager.

**Comment by blu-IT** [comment]
OK, thanks! Submitted via email...

**Comment by jobisoft** [comment]
Could you also check, if this is related to https://github.com/jobisoft/DAV-4-TbSync/issues/41 ?

**Comment by blu-IT** [comment]
Ok, changed the value as reported in https://github.com/jobisoft/DAV-4-TbSync/issues/41 and it works now! Thanks!
