### ISSUE TITLE
SOGo - Syncing fails with NS_ERROR_MALFORMED_URI

### ISSUE THREAD

**Issue by charvp** [jobisoft/DAV-4-TbSync#45]
## Your environment

TbSync version: 0.7.22
DAV-4-TbSync version: 0.10
Thunderbird version: 60.3.1

[x] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Syncing succeeds

## Actual behavior
Sync status reports: `Javascript error: Component returned failure code 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]`
On a fresh Thunderbird start, events are actually synced. Deleting events also works. New contacts are not synced.

## Steps to reproduce
Both adding a new account and trying to sync a (previously working) account returns the same error. This is SOGo in an (updated) [mailcow-dockerized](https://github.com/mailcow/mailcow-dockerized) setup.

**Comment by jobisoft** [comment]
The redirect management has been rewritten and it looks like I do not prepend the FQDN if I get a relative URL to redirect to (as in your case)

I will fix that. Until then, use the redirected URL directly: 

Your server URL + /SOGo/dav/

Best regards,
John
