### ISSUE TITLE
Chat field not 100% correct in Nextcloud

### ISSUE THREAD

**Issue by mase76** [jobisoft/DAV-4-TbSync#54]
Hi!
I like your TB plugin, instead of sogo connector, the field names are mostly correct now.
A field which is not correct ist the chat field. When I fill the Jabber field in TB, it is shown
as xmpp://<my-id> in Nextcloud without a chat type.

**Comment by jobisoft** [comment]
Can you point me to an RFC, where Jabber support in vCard 3 is defined? 

Thanks,
John

**Comment by mase76** [comment]
I don't know, if Jabber or other Chats are defined in vCard 3. I only see, that Nextcloud and TB are
handling it different. If you don't have access to a Nextcloud server, I could create a test account on
mine for you.

**Comment by jobisoft** [comment]
Jabber is XMPP, so I do not know what you expect. Can you send a screenshot, of how you expect it to look like, or how it looked like with sogo?

**Comment by mase76** [comment]
Both, your Addon and Sogo are doing it identical with the XMPP field. I fill the Jabber field in TB, and sync it with my Nextcloud. In NC the field title is empty, what NC does not allow when editing in the webif. The chat address I see in NC is xmpp:<myaddress>. Maybe chat addresses are no vcard standard, so all these clients are handling it different.
What I expect is this:
-Filling the chat field for Jabber in TB with the xmpp address.
-Sync it to Nextcloud.
-See the field type XMPP in NC with the address only, without xmpp:
-The same the other way.

This issue can also be Nextcloud related. If so, I will file an issue there. I suggest to give you a NC test account, so you can try by yourself. The behaviour is hard to describe.

**Comment by jobisoft** [comment]
I will have a look. I already have access to a nextcloud Server.

**Comment by jobisoft** [comment]
You should file a bug report with NextCloud. This is how t looks with OwnCloud:

![image](https://user-images.githubusercontent.com/5830621/50532275-7a913200-0b17-11e9-859d-08f077f00b67.png)

And this is what I setup in TB:

![image](https://user-images.githubusercontent.com/5830621/50532287-c04dfa80-0b17-11e9-861e-1f287ee99d2f.png)

As you can see, it identifies the Jabber field correctly.
