### ISSUE TITLE
Cannot Add Gmail Account - Add A Specific Entry For Gmail?

### ISSUE THREAD

**Issue by pauby** [jobisoft/DAV-4-TbSync#56]
## Your environment

TbSync version: 1.0.19 (Beta)
Thunderbird version: 60.4.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I add a 'Discovery Service' and I add Gmail server URL (https://www.googleapis.com/) and get the contacts list.

## Actual behavior
I get a 404 not found.

## Steps to reproduce
Add an Account -> Discovery Service -> Server Url: https://www.googleapis.com/ -> username: email address -> password: <app password I created and has been tested as working>

Unfortunately I can't find any other cpntact syncing addons that work with this version of Thunderbird so I can't even verify it's this addon that's failing.

Note that I got the server URL at https://developers.google.com/contacts/carddav/

Error log:

```
URL:
https://www.googleapis.com/.well-known/caldav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
Not Found
```

As an aside for this I've noticed there are several pre-configured server types setup (Yahoo etc.). Could one be added for Gmail / Google?

**Comment by chwba** [comment]
This is still work in progress or should it work now?

**Comment by jobisoft** [comment]
Not yet implemented, I have not yet mastered the art of oath2.

**Comment by bshensky** [comment]
I tried using a Google-generated app password from
https://myaccount.google.com/apppasswords

I get authenticated, but then all attempts to try to get to
https://www.googleapis.com/carddav/v1/principals/[MY_GMAIL_EMAIL]/lists/default
https://www.googleapis.com/carddav/v1/principals/[MY_GMAIL_EMAIL]/lists
https://www.googleapis.com/carddav/v1/principals/[MY_GMAIL_EMAIL]
https://www.googleapis.com/carddav/v1/principals
https://www.googleapis.com/carddav/v1
https://www.googleapis.com/carddav
https://www.googleapis.com
all yield the same message:

"Could not find any calendars or address books on the server"

I turned on debugging and got the the following in the debug.log:


** Thu May 09 2019 11:59:54 GMT-0400 (EDT) **
[Check4Lightning] : Done

** Thu May 09 2019 11:59:54 GMT-0400 (EDT) **
[TbSync init] : Done

** Thu May 09 2019 11:59:56 GMT-0400 (EDT) **
[calendarObserver::onLoad] : <[MY_EMAIL_ADDRESS]> was loaded.

I feel like we are all getting close here.  How can I help?

**Comment by jobisoft** [comment]
I am currently busy with getting ready for TB68. I did not work on the google stuff yet. I will get to this, after TB68 has landend.

**Comment by jobisoft** [comment]
**Tada:** The latest beta has google support! You now can now setup the sync of your google contacts and your google calendars from one single UI!

You can get the beta here: https://tbsync.jobisoft.de

Feedback is appreciated!

![grafik](https://user-images.githubusercontent.com/5830621/69188445-d80de300-0b1c-11ea-8723-811d0dd5b0b3.png)

**Comment by DavidBE-UK** [comment]
Thanks very much for this. Where do you like the feedback - here in this issue, or somewhere else?

**Comment by jobisoft** [comment]
This issue would be the best place for feedback.

**Comment by DavidBE-UK** [comment]
Right. First, thanks again for this. Second, two issues.

1 I was totally focused on the address book, as the calendar had been covered by another extension. The address book part appears to be working fine except for one small thing. After I added the Google account in TbSync it created and synced the new address book in TB with my Google Contacts, much better (as I hoped) than gContactSync which I've now disabled hopefully for good. But while I was looking through checking, I noticed that for one contact I'd originally entered two email addresses, one work and one home, but left both addresses marked as 'other'. In the Google Contacts web app in my web browser I've now set the one email address to 'Home' and the other to 'Work'. This change synced immediately in the Contacts app on my (Android) phone. But it is NOT syncing with the TbSync address book in Thunderbird. I've clicked to sync several times, and the first time it said there had been a change that needed syncing (but not the further times), but the two email addresses are staying as type 'Other', even though in the Edit Contact window I see there is a dropdown menu by each to set Home, Work or Other. Not a big deal, but still appears to be some kind of glitch.

2 I hadn't thought about the calendar side as the Provider For Google Calendar extension was working fine. However, as TBSync offered the Google calendar syncing facility too., I thought it made sense to simplify things and just have TBSync doing the calendar syncing along with the address book. But for some reason TBSync is not showing all the calendars from my Google account to sync that Provider does. Specifically, in the Google Calendar web app I see 7 calendars (not counting the connected Outlook one), of which 4 are my own read/write ones - the actual gmail account personal one, plus Contacts (e.g. birthdays marked in Google Contacts), Reminders and Tasks - and 3 are read only Google special calendars I subscribed to - Holidays in United Kingdom, Christian Holidays, and Phases of the Moon. Now, in TB the Provider for Google Calendar extension offers me 6: of my personal read/write ones I get my personal  gmail account one and Contacts, NOT Reminders or Tasks, but one called 'My List', which I think is actually Reminders or Tasks or both: and of the 3 read only subscribed ones I get all 3 - Holidays in United Kingdom, Christian Holidays, and Phases of the Moon. But TBSync is only offering me FOUR calendars: my personal Gmail one and Contacts, but NOT either the Reminders and Tasks or the My List, and Holidays in United Kingdom and Christian Holidays but NOT Phases of the Moon. Now, I do note that the 'Location' given for the Provider For Google Calendar extension calendars starts googleapi:// whereas with TBSync it is https://, so I presume they are using different methods. But I can't see why particularly the Phases of the Moon subscribed calendar would be missing with TBSync when the two 'holidays' subscribed calendars are present.

Hm. Just noticed one thing looking through the settings in the Google Calendar web app. The two subscribed read only Google calendars that _are_ showing up in TBSync have Calender IDs - which are also part of their public URLs - ending @group.v.calendar.google.com. But the Phases of the Moon one that is NOT showing up in TBSync has a Calendar ID - also in its URL - ending @group.calendar.google.com. No .v. Could that be relevant?

**Comment by jobisoft** [comment]
I will ahve a look at the contact issue later. For the calendar issue, check this out:
https://calendar.google.com/calendar/syncselect

There you can select which of your calendars are enabled for CalDAV Sync.

**Comment by DavidBE-UK** [comment]
Thanks - that's fixed that calendar. But why is that page not linked from the Google calendar settings? (A question for Google, not you!)

**Comment by DavidBE-UK** [comment]
After the last update I got a few minutes ago, all the Google calendars have become greyed out in the TB Calendar list, unticked and won't let me turn them back on. They are still turned on to sync and status OK in TBSync.

**Comment by jobisoft** [comment]
yeah, I changed how the calendars are managed. Remove them all, and let tbsync create them anew.

**Comment by jobisoft** [comment]
I think I fixed the address book issue as well. After you updated your addons, I propose to remove all google addressbooks and calendars from Thunderbird, remove your google account from TbSync, restart Thunderbird and setup your google account anew. I did change some fundamental things.

**Comment by DavidBE-UK** [comment]
Yes, that's worked (after including the removing the address book and calendars before deleting the Google account from TbSync, restarting and re-creating the Google account - a little before your post I had tried deleting the account, restarting and re-creating but without explicitly removing the address book and calendars, and that didn't work).

Great - everything seems to be working, so Thunderbird finally can sync to both gmail.com and outlook.com accounts through a consistent interface. Great job. I hope the word gets round the Thunderbird community. I'll certainly put positive reviews for the extensions when these versions come out of beta onto ATN.

I presume you'll be able to do whatever is required for Google to remove the 'Security issue ... developer's information hasn't been verified by Google' security issue flagged by Google in users' accounts after granting access during account creation?

**Comment by jobisoft** [comment]
You will not believe what I have to do to get fully approved: I need to make a video of how it is used and what i use the permissions for and send that video in. crazy. But yes, before this can be shipped to ATN I need to get approval from google.

**Comment by DavidBE-UK** [comment]
Sorry to hear it's so much extra work for you - and it seems rather hypocritical of Google given how every week I see another story about how yet another university or security company has picked a random sample of a few hundred apps in the Google Play Store, analysed them, and found dozens that are basically malware, asking for Android permissions they don't need and then stealing data (and sometimes even photos of the user). You'd think Google could spend the time and resources on cleaning up their own app and extension stores for Android and Chrome rather than making life difficult for freeware and open source software developers for non-Google software. Given the degree of market share dominance they already have in the PC and Android browser market with Google Chrome (I use Firefox) and in the PC and Android email market with the Gmail webmail and app (I use Thunderbird and BlueMail respectively - I don't use webmail, whether Google's, Microsoft's or my main ISP's) it also seems very petty - even spiteful.

Which makes me all the more grateful that you are prepared to do this for the Thunderbird community, as I do think being able to sync with both gmail.com and outlook.com calendars and especially address books in a simple and consistent way is something Thunderbird really needs to be able to do to be considered a serious email client contender.

I just hope the Thunderbird main program devs aren't going to pull another major change anytime soon that will require all the most important extensions - like yours - to have to be rewritten again. I've only been using Thunderbird for about a year and a half, and we've already had two major main program changes that broke most of the most important (to me, anyway) extensions, and the second (with the change to TB 68), especially so soon after the previous one, appears to have caused a number of the more important TB extension developers to just give up in disgust.

Anyway, I'll just thank you again, and stop bothering you now (unless I find a bug ....)

**Comment by jobisoft** [comment]
It has been uploaded to ATN and is now part of the official stable version. I am still in the process of getting verification from google, so you might see a "this app is not verified" message. I hope to get rid of that within 4 weeks.

**Comment by shoqvalue** [comment]
Jobisoft, gContactSync was your only rival in thunderbird, and it seems to be dead. No updates in a year, no forum activity in months.  Thus, a lot of people are going to be looknig for a way to sync their tbird and gmail accounts. I am a bit lost trying to understand how to set up your app with gmail. Were the options above only in the beta? I am using the mozilla store version.  There is no option fo gmail anyway. I installed active sync, just to be sure it wasn't needed.  I enter my email and password and get this errror.
![2020-07-29_17h52_22](https://user-images.githubusercontent.com/10272750/88857466-52225b80-d1c4-11ea-8cf7-947aea0a1e7b.png)

How can I get this working? I will help get the word out that there's an alternative to gContactsSync

TIA
