### ISSUE TITLE
Shared calendars not visible

### ISSUE THREAD

**Issue by sim0nx** [jobisoft/DAV-4-TbSync#57]
## Your environment

TbSync version:  0.7.22
DAV-4-TbSync version: 0.10
Thunderbird version:  60.3.0
CalDAV server: Davical

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Every shared calendar I have access to show be listed and subscribable

## Actual behavior
Only my principal's calendars are listed

## Steps to reproduce
- Create two users/principals and give each user access to the other's calendar.
- Add the account for one of the users in TbSync.
- The shared calendar of the other user should be visible. (But it is not).

I suppose you do not list all calendars on the server a user has access to, but only the calendars owner by the user directly.

Could you please have a look ?

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Related to this?
https://github.com/jobisoft/DAV-4-TbSync/issues/4

What server?

Can I have a test account with shared resources?

**Comment by sim0nx** [comment]
I don't think this is related to #4. In my case I have multiple users who each have specific access to other user's calendars. Adding those calendars directly with their specific URL works. There is also a possibility to enumerate them (don't recall how this works via caldav) -> this is what I am missing here.

Server is davical and I have provided you with test accounts via  a private e-mail.

**Comment by jobisoft** [comment]
Hm, this is the response I get from the server:
```
[RESPONSE] : 207 : <?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:C1="urn:ietf:params:xml:ns:carddav" xmlns:C2="http://calendarserver.org/ns/">
 <response>
  <href>/cal/caldav.php/test1/</href>
  <propstat>
   <prop>
    <resourcetype>
     <collection/>
     <principal/>
    </resourcetype>
    <displayname>test1</displayname>
   </prop>
   <status>HTTP/1.1 200 OK</status>
  </propstat>
 </response>
 <response>
  <href>/cal/caldav.php/test1/calendar/</href>
  <propstat>
   <prop>
    <resourcetype>
     <collection/>
     <C:calendar/>
    </resourcetype>
    <displayname>test1 calendar</displayname>
   </prop>
   <status>HTTP/1.1 200 OK</status>
  </propstat>
 </response>
 <response>
  <href>/cal/caldav.php/test1/addresses/</href>
  <propstat>
   <prop>
    <resourcetype>
     <collection/>
     <C1:addressbook/>
    </resourcetype>
    <displayname>test1 addressbook</displayname>
   </prop>
   <status>HTTP/1.1 200 OK</status>
  </propstat>
 </response>
 <response>
  <href>/cal/caldav.php/test1/calendar-proxy-read/</href>
  <propstat>
   <prop>
    <resourcetype>
     <collection/>
     <C2:calendar-proxy-read/>
    </resourcetype>
    <displayname>/test1/calendar-proxy-read/</displayname>
   </prop>
   <status>HTTP/1.1 200 OK</status>
  </propstat>
 </response>
 <response>
  <href>/cal/caldav.php/test1/calendar-proxy-write/</href>
  <propstat>
   <prop>
    <resourcetype>
     <collection/>
     <C2:calendar-proxy-write/>
    </resourcetype>
    <displayname>/test1/calendar-proxy-write/</displayname>
   </prop>
   <status>HTTP/1.1 200 OK</status>
  </propstat>
 </response>
</multistatus>
```

The only calendar resource I get is the test calendar. Can you find out, what query DavDroid is using, to get a lit of the shared calendars? You could increase the log verbosity of your server to get any incomming query.

**Comment by sim0nx** [comment]
The first query it does is this:

`PROPFIND /caldav.php/test_user/ HTTP/1.1" 207 677 - <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><CAL:calendar-home-set /><n0:calendar-proxy-read-for xmlns:n0="http://calendarserver.org/ns/" /><n1:calendar-proxy-write-for xmlns:n1="http://calendarserver.org/ns/" /><group-membership /></prop></propfind>`

The next queries are already related to other user's calendars.

Then at the end it does this one again on the principal's, "test_user" URL.

`PROPFIND /caldav.php/test_user/ HTTP/1.1" 207 14331 - <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><current-user-privilege-set /><displayname /><CARD:addressbook-description /><CARD:supported-address-data /><CAL:calendar-description /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:supported-calendar-component-set /><n1:source xmlns:n1="http://calendarserver.org/ns/" /></prop></propfind>`

Thus I think the first query should give the expected results.

**Comment by jobisoft** [comment]
Thanks! That is something I can work with:

```
[RESPONSE] : 207 : <?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:A="http://calendarserver.org/ns/">
 <response>
  <href>/cal/caldav.php/test1/</href>
  <propstat>
   <prop>
    <C:calendar-home-set>
     <href>/cal/caldav.php/test1/</href>
    </C:calendar-home-set>
    <A:calendar-proxy-read-for>
     <href>/cal/caldav.php/test2/</href>
    </A:calendar-proxy-read-for>
   </prop>
   <status>HTTP/1.1 200 OK</status>
  </propstat>
 </response>
</multistatus>
```

I will need a few days, can you keep my test accounts running?

**Comment by sim0nx** [comment]
Great!

Yes of course, just let me know when you no longer need them.

Thank you

**Comment by jobisoft** [comment]
Since I am at it, could you also add shared adressbooks? So I can check and impl both?

**Comment by jobisoft** [comment]
Can you please also unshare the calendar1 for user 2? So that only calendar2 is shared for user 1?

**Comment by jobisoft** [comment]
Note to myself:
https://forums.bitfire.at/topic/359/syncs-only-own-collections-as-opposed-to-all-calendars-one-is-allowed-to-see/31

https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-sharing.txt

**Comment by jobisoft** [comment]
https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-proxy.txt

**Comment by sim0nx** [comment]
> Since I am at it, could you also add shared adressbooks? So I can check and impl both?

That already works the same ... addressbook is at ".../addresses"

**Comment by sim0nx** [comment]
> Can you please also unshare the calendar1 for user 2? So that only calendar2 is shared for user 1?

done

**Comment by jobisoft** [comment]
Is davdroid able to see the shared address books? Any chance you could provide the corresponding requests again?

**Comment by sim0nx** [comment]
> Is davdroid able to see the shared address books? Any chance you could provide the corresponding requests again?

Yes it is. Here is the request it does:

`PROPFIND /caldav.php/test_user/ HTTP/1.1" 207 509 - <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><CARD:addressbook-home-set /><group-membership /></prop></propfind>`

**Comment by sim0nx** [comment]
Yes it does. addressbook is at ".../addresses"

Same ACLs as for calendars apply.

**Comment by jobisoft** [comment]
Can you create a thrid user who also shares a calendar to user 1? I need to see how more than one group membership looks like.

**Comment by sim0nx** [comment]
> Can you create a third user who also shares a calendar to user 1? I need to see how more than one group membership looks like.

Sure -> test3
It also shares an addressbook with the same name as the others.

**Comment by jobisoft** [comment]
I need your help once more.  This query:
https://github.com/jobisoft/DAV-4-TbSync/issues/57#issuecomment-452209603

returns a list of proxy principals, the current user1 is part of, for example
/cal/caldav.php/test3/calendar-proxy-read/

What query is he sending, to actually get the calendars/adressbooks part of that proxy? It should be the next query.

**Comment by jobisoft** [comment]
Got it, looking good:

![image](https://user-images.githubusercontent.com/5830621/50829438-cf694f80-1344-11e9-94ea-701e516fc2dc.png)

Now I need to add ACL support, which will also fix #13

**Comment by sim0nx** [comment]
Ah thas looks awesome! Thank you!
Looking forward to a release / beta :-D

**Comment by jobisoft** [comment]
i need you to create a nested group membership :-) 
Remove all sharings and set up the following:

Share cal+card of test3 to test2
Share cal+card of test2 to test1

what is davdroid showing for user1

**Comment by jobisoft** [comment]
thanks, you server is reporting a direct group membership of test3 in test1, so either he is flattening the hierarchy, so I do not have to dive throu the principals, or the acl is still set.

Can you confirm that you did not set a direct membership between 1 and 3?

**Comment by sim0nx** [comment]
> thanks, you server is reporting a direct group membership of test3 in test1, so either he is flattening the hierarchy, so I do not have to dive throu the principals, or the acl is still set.
> 
> Can you confirm that you did not set a direct membership between 1 and 3?

My mistake...there was still an ACL for 1 in 3.

Can you retry please?

**Comment by jobisoft** [comment]
Ah, ok. The current alpha does not dive into the principals and this is the result:

![image](https://user-images.githubusercontent.com/5830621/50845361-f0de3180-136c-11e9-8fb6-12d2c57570a4.png)

So I have to dive. What is DavDoid displaying now?

**Comment by sim0nx** [comment]
> Ah, ok. The current alpha does not dive into the principals and this is the result:
> 
> ![image](https://user-images.githubusercontent.com/5830621/50845361-f0de3180-136c-11e9-8fb6-12d2c57570a4.png)
> 
> So I have to dive. What is DavDoid displaying now?

I can clearly see that davdroid checks test2, but it doesn't show anything from user test3. So either there is missing something in davdroid, or this is not supposed to be working (or davical doesn't support it, I would doubt that but am not sure).
-> result is the same as you get, to be clear.

**Comment by sim0nx** [comment]
> That is interesting. I activated diving and obtained the proxy for test 3 and can querry its resources:
> 
> ...

nice!

> However, when I actually want to query `/cal/caldav.php/test3/`, I get this:
> 
> ```
> [ErrorLog] : 403
> ...
> ```
> Is that a bug in your server? We can stop here and I do not integrate diving, even though the specs tell me to. If you can fix this on your side, there is one last thing we need to test after that: group-membership loop detection. Than we are through with this.

Is there anything in the specs how this case should be handled? Should this actually work ?
Strictly considering ACLs, it makes sense that as test1 has no direct permission on test3, this fails. One could assume transitivity in this case but I guess the currently experienced behavior is another way of doing things.
At least I can live with that :-D


What exactly do you want me to configure for group-membership loop detection?

**Comment by jobisoft** [comment]
The spec say, that if test1 is a proxy for test2 and test2 is a proxy for test3, than test1 should be able to access resources from test3 (double vacation replacement).

And this works with your server up to the point where I want to actually read a resource of test3. Its URL is anounced to test1, however, test1 does not have read permissions on test3.

I just wanted to "get it done once and for all" but it is totally fine with me to disable diving for now.

If this had worked, I would have asked you to add test3 as a proxy for test2 which would create a loop, since when checking test3 I would find test2 (again) but if I would follow it I would end up in a loop (1 -> 2 -> 3 -> 2 -> 3 ...). I have a loop detection in place but wanted to test that of course.

I think I am pretty much done with the UI. Now I need to actualls obey the ACL settings.

![image](https://user-images.githubusercontent.com/5830621/50865443-0b80cc80-13a6-11e9-9816-7cb3239f0935.png)

**Comment by sim0nx** [comment]
Ok I see. I guess that with Davical I would still have to grant you permission on the requested ressource in order for it to work.
But I am fine with your current implementation that covers my use-case fully.

Thanks again.

Do you still need the caldav access or can I remove it ?

If you need it in the future for testing, drop me a line and I can set it up again in any case...

**Comment by jobisoft** [comment]
Released in current beta, please test and tell me what you think.
[tbsync.jobisoft.de](tbsync.jobisoft.de)

**Comment by sim0nx** [comment]
Hmm when I install the beta installer it only switches tbsync to beta channel. Manually installing the DAV component works, but tools->addon-preferences->tbsync does nothing.

Not sure what I am doing wrong.

I tried restarting TB which did not help.

**Comment by jobisoft** [comment]
Hm, I have heard now multiple times, that the beta installer is not working :-(

Remove all Tbsync modules (Core, DAV, EAS) and reinstall all 3 from the beta subfolder. Does it work?

**Comment by jobisoft** [comment]
Are you on TB60?

**Comment by sim0nx** [comment]
I tried to remove them manually, restart, add the beta xpi's.... didn't work.

Yes I am on TB60.0.3

**Comment by jobisoft** [comment]
That is a real show stopper for  the next release. I need to learn what is going on. Are you able to start TbSync via the global menu?

![image](https://user-images.githubusercontent.com/5830621/51065166-c659d600-1603-11e9-9bd8-7e55358c4b1d.png)

Or by clicking on the TbSync Status info in the lower right corner?

![image](https://user-images.githubusercontent.com/5830621/51065200-ee493980-1603-11e9-88dd-f4856ee9bf5f.png)

**Comment by jobisoft** [comment]
What is your status? Would you like to schedule a teamviewer session, so we could work on this together?

**Comment by sim0nx** [comment]
I confirm that with the latest XPI versions it is working correctly for me in TB 60.4.0 ! :-)

**Comment by jobisoft** [comment]
Hooray!
