### ISSUE TITLE
NS_ERROR_MALFORMED_URI

### ISSUE THREAD

**Issue by jgato** [jobisoft/DAV-4-TbSync#60]
## Thunderbird 60.4.0

it was working until a few days ago. Now when I try to synchronize calendars (using caldav) I get the error NS_ERROR_MALFORMED_URI.
I am using Davmail to provide the caldav integration. It was working reasonable ok, but now...

TbSync version: 0.7.22
DAV-4-TbSync version: 0.10
Thunderbird version: 60.4

[X ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please try the beta.
https://tbsync.jobisoft.de

If the installer is not installing 3 modules with [beta release channel] in its names, you must install them manually from the /beta subfolder. Above URL has instructions.

**Comment by jgato** [comment]
Well, it worked with the beta!! 

Thanks :D
