### ISSUE TITLE
Some accepted events are shown in "light" colour

### ISSUE THREAD

**Issue by jgato** [jobisoft/DAV-4-TbSync#70]
Some accepted events are shown in "light" colour in the calendar, as if they were pending. I does not always happens, but I dont know the difference between when it happens ok.

## Your enviroment

TbSync version: beta 1.0.32
DAV-4-TbSync version: 0.10.44
Thunderbird version: 60.4.0

[ X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Can I have a screenshoot?
 
But CalDAV sync is handled by Lightning, I am not involved. I just do the calendar discovery and add them to Lightning.

**Comment by jgato** [comment]
For example:

**Comment by jgato** [comment]
More tests sorry:

1 - If I accept the event from the email it seems is working ok
2 - If I accept the event from the calendar it happens this extrange situation...

**Comment by jobisoft** [comment]
Can you please check, if they are both in the same calendar? I assume the different color comes simply from the different colors of two different calendars.

**Comment by jgato** [comment]
both in the same calendar. When I receive the invitaiton is in this light colour, when you accept it turns to the real colour of the calendar.

**Comment by jobisoft** [comment]
I think this is a lightning issue. I cannot do anything about that.

**Comment by jgato** [comment]
Sorry I dont think this is an issue with lightning, because it does not happens with other calendars apart from CalDav. I will ask also in TBSync repository.

Thanks

**Comment by jobisoft** [comment]
Let us get to the bottom of this. Please open the calendar options of the calendar in question and write down all the settings, maybe make a screenshoot, so you do not forget something. Also copy the location URL to some textfile:

![image](https://user-images.githubusercontent.com/5830621/52046756-c6d0f700-2547-11e9-9258-dcbc319db02d.png)

Then remove tbsync from your system and set up the calendar in Lightning directly with the URL you just saved. Also make sure to have all the settigs as before.

Observe.

**Comment by jgato** [comment]
you mean to remove the tbsync addon?

**Comment by jgato** [comment]
Could it be related to this?

![image](https://user-images.githubusercontent.com/3435696/52049239-91c7a300-254d-11e9-966d-6f0af6d958b9.png)

I have this error anytime I try to change the status from the event's window. I have realized... I try to change the status, and I click in a new one.. the windows is inmediatly closed. I thought this could be ok, but now I am start thinking that closes too sudenly, it could be a crash. it should allows you to change the status and then you save/close the window.

**Comment by jobisoft** [comment]
One thing after the other. Please
- make a screenshoot for yourself of the Lightning settings of the calendar in Question
- copy the Location URL of that calendar to some Textfile
- disable all your accounts in TbSync
- remove/uninstall all TbSync releated addons, like TbSync, Provider for CalDAV and CardDAV etc.
- Setup your calendar manually in Lightning using all the settings from the screenshoot

Observe.

**Comment by jgato** [comment]
Ok, I have tried but.... the new calendar does not synch at all. Without TbSync I cannot connect the server. My url is just a localhost url:

http://localhost:1026/users/email/calendar/

because I am using caldav protocol through Davmai.

So repeating your steps, now I see an empty calendar :(

**Comment by jgato** [comment]
you are right... now I am confused what I tried this combination, instead of just directly using Davmail (something that I was doing some years ago). Sorry, it is not an issue in your addong, it seems related to davmail directly.

thanks for the help

**Comment by jobisoft** [comment]
no prop. Removing TbSync was the only option to show you, that it is not my fault. DavMail users are not the primary target group for TbSync. More like OwnCloud and Nextcloud users.

TbSync does 3 Things:
 - resource discovery (Show avail adress books and calendars on a Server)
 - actually sync contacts using CardDAV protocoll
 - adding found calendars to Lightning and let Lightning sync using the CalDAV protocoll.

I did not re-implement CalDAV sync but use the one part of Lightning. The "gain" for you is that you do not have to look up that URL but let TbSync do that for you. If you have address books on your DavMail Server, that TbSync will sync those for you.

**Comment by jgato** [comment]
Maybe I could test your addon, in order to see if it is better or not compared to davmail. But, I need to support double factor login (with PKI authorization). This is a new feature incorporated in davmail, and the reason I was calling davmail from your addon. Of course, no sense, my fault.
