### ISSUE TITLE
Missed language translate variable

### ISSUE THREAD

**Issue by sinya13** [jobisoft/DAV-4-TbSync#72]
![dav-err-transl](https://user-images.githubusercontent.com/4994987/52276061-3db02a80-2962-11e9-9485-68252641014c.jpg)

Analogically in EAS-for-TbSync:

![eas-err-transl](https://user-images.githubusercontent.com/4994987/52276731-017dc980-2964-11e9-8dd6-34eddf86372c.jpg)

**Comment by sinya13** [comment]
Yes, it works. Earlier, I already showed it to you. Ubuntu system 16.04. But the XFCE shell. The XFCE is likely to have a display defect - since it is greatly simplified on the graphics. And in the same KDE or Gnome - this is all drawn richer and more correctly.

**Comment by jobisoft** [comment]
But if you look at this document, XFCE is able to Display tabs.
https://pclosmag.com/download.php?f=XfceTipsTricksSE.pdf

It Looks like XFCE has a huge Distribution. Is there anything we can do?

**Comment by sinya13** [comment]
I heard the Chinese love XFCE. Not a bad shell, no waste. We need some other similar tabbed element ... But if it is not in the Thunderbird library ... What you can do here ...

**Comment by jobisoft** [comment]
new beta is out. if you are on stable, you have to reinstall beta:
https://tbsync.jobisoft.de

**Comment by sinya13** [comment]
I think Mozilla is responsible for writing XUL windows. But they will say - XUL is outdated, we are gradually destroying it. Write on HTML5 or whatever they have there now ... XFCE will spread its arms and say - take our other element. I think except for how to put single buttons in a row here - everything else is useless! But it works and so! Or maybe you need to slip a contrasting background - if there is a background option.

Beta-version set, thank you.

**Comment by jobisoft** [comment]
Would you post this issue here:
https://forum.xfce.org/
?

As I am not a xfce user, I will not be able to ask any follow up questions. If you post, do not talk about TbSync but about Thunderbird in general and use the Thunderbird Settings Dialog as the issue:


![](https://discourse-paas-production-content.s3.dualstack.us-east-1.amazonaws.com/original/3X/6/6/667c4d6099591e80fdded3c81028f536ac9075b3.jpeg)

Maybe there is a solution...

**Comment by sinya13** [comment]
I have the same settings as in the picture. View menu does not interfere with work. What inscriptions are pressed - enough to remember. I am very done now from programming. I can hardly explain XFCE what I want from them, but they will understand. Yes, and they will send me back to Mozilla and XUL.

**Comment by sinya13** [comment]
![sample1](https://user-images.githubusercontent.com/4994987/52327216-61c04a00-29fc-11e9-921f-762d08e60749.jpg)
In the same Thunderbird important Enigmail addition has the same defects. Changing the theme of Thunderbird - does not affect in any way. It sits in either the XFCE color scheme or somewhere else. But not decorations XFCE valuable! Quite the contrary!

**Comment by sinya13** [comment]
Quite a simple solution - to paint the menu labels in blue! Blue labels are always perceived as being pressed! And do not fight uselessly with a bunch of software communities! Can you color the menu tabs in blue?
