### ISSUE TITLE
Contacts do not get deleted in Thunderbird

### ISSUE THREAD

**Issue by ploebb** [jobisoft/DAV-4-TbSync#73]
## Your environment

TbSync version: 1.3
DAV-4-TbSync version: 0.11
Thunderbird version: 60.5.0
Nextcloud version: 13.? & 15.0.2 tested

[x] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When a contact is deleted in Nextcloud on the webinterface, it should get deleted in the Thunderbird adressbook after the next sync.

## Actual behavior
Contact still exists in Thunderbird after sync. After manually deleting in TB and resyncing with TbSync, Nextcloud responds with an error 404 "Card not found".

## Steps to reproduce

1. Add Nextcloud with Carddav-Account (direct DAV-Link or .well-known does not matter)
2. Check addressbook to sync
3. Create test-contact either in Thunderbird or Nextcloud
4. Sync with TbSync (manually)
5. Contact is on both sides
6. Delete contact in Nextcloud (Webinterface -> three-dots-menu -> delete)
7. Sync with TbSync (manually)
8. Contact does not get removed in Thunderbird

I sent you the debug-log via email. You can also get a temporary Nextcloud-account for testing.

**Comment by jobisoft** [comment]
Confirmed. Someone thought sending a "teapot" on delete is a good idea:

```
[RESPONSE] : 207 : <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:response>
  <d:status>HTTP/1.1 404 Not Found</d:status>
  <d:href>/remote.php/dav/addressbooks/users/john.bieling/contacts/e733598c-160d-467f-bff6-bf5114929d6a.vcf</d:href>
  <d:propstat>
   <d:prop/>
   <d:status>HTTP/1.1 418 I'm a teapot</d:status>
  </d:propstat>
 </d:response>
 <d:sync-token>http://sabre.io/ns/sync/6</d:sync-token>
</d:multistatus>
```

Will look at that, I probably read the wrong status.

**Comment by jobisoft** [comment]
I just released a new beta, which should fix that.
1. Disable all your TbSync Accounts
2. Follow https://tbsync.jobisoft.de
3. Re-Enable all your accounts

Feedback is appreciated.

**Comment by ploebb** [comment]
Awesome! With the new beta it's working as expeted. Thank you for taking the time and fixing this so quickly!
