### ISSUE TITLE
Missing variable for language translate

### ISSUE THREAD

**Issue by sinya13** [jobisoft/DAV-4-TbSync#74]
Hello John

Unfortunately, after the updates, this has not been fixed. The variable for translating this word is also not seen in the locale files. For languages with non-Latin roots - it may have a problem, such as Chinese or Japanese hieroglyphs do not fit here.

![dav-err-transl](https://user-images.githubusercontent.com/4994987/52548729-57c58f00-2de0-11e9-881c-8c65d5fee198.jpg)

**Comment by jobisoft** [comment]
The name is delivered by your server. It is the name of the folder. I only use a localized fallback name, if none is provided by your server

**Comment by sinya13** [comment]
Ok
