### ISSUE TITLE
iCloud credentials are not retrieved from the password manager.

### ISSUE THREAD

**Issue by jfdahl** [jobisoft/DAV-4-TbSync#78]
## Your environment

TbSync version:                   1.7 (4/4/2019)
DAV-4-TbSync version:       0.15 (4/4/2019)
Thunderbird version:           60.6.1 (64-bit)
Operating system version:  MacOS High Sierra

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Once the caldav and carddav accounts are created and authenticated, the credentials should be saved to the password manager so that I do not get prompted for credentials every time the data is synchronized.

## Actual behavior
I keep getting prompted to enter my iCloud credentials for the calendar synchronization. When I check the password manager, I see that the credentials are stored correctly, but they are not being accessed.

## Steps to reproduce
1. Install TbSync and DAV-4-TbSync.
2. Configure an iCloud account using a username and application password.
    - Make sure to check the box to allow the password manager to save the credentials.
3. Allow the data to synchronize.
4. Wait for the synchronization timer to expire for the next sync interation.
5. Observe the prompt for credentials.

## Other pertinent details
1. iCloud account is two-factor-authentication enabled.
2. An application password has been created for this use case.
3. The iCloud credentials are saved in the Thunderbird password manager.
4. The Thunderbird password manager is protected by a master password.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jfdahl** [comment]
After exploring a few different configurations, it seems that TbSync _may_ not allow the same application password to be used in multiple locations. I have two different computers (MacOS High Sierra and Xubuntu Linux) connecting and since I created a separate application password for one of the systems, I have not observed the issue. The CalDAV client I was using before trying TbSync did not have this issue. I would say the priority of fixing this is low, but a note in the setup instructions may be helpful.

**Comment by jobisoft** [comment]
I am trying to reproduce your isse. I stumble across

> Make sure to check the box to allow the password manager to save the credentials.

The TbSync Password Prompt does not have such a checkbox (it always stores the password in the password manager):

![image](https://user-images.githubusercontent.com/5830621/55634723-55b7f500-57bf-11e9-8b17-f97833a24051.png)

If you get the standard lightning password prompt, than lightning is having an issue.
1. Have you setup two different iCloud accounts on the same Thunderbird instance in parallel?
2. Can you manually remove all iCloud calendars from Lightning (which should also unsubscribe them in TbSync Manager) and subscribe them anew via the TbSync Manager? Does that help?

In general: I do not know the rules for application passwords, but I have not yet encountered, that you need extra passwords for different/parallel installations of the same app. I will check on that.

**Comment by jobisoft** [comment]
This could also help:
- disable your icloud account in tbsync
- check that there is no leftover icloud calander in lightning (remove if any)
- remove all entries from the password manager of your icloud account
- re-enable your icloud account in tbsync

There is indeed an issue with the way lightning pulls passwords from the password manager, if there are multiple entries.. I have send in a patch and hope it gets accepted soon.

**Comment by jfdahl** [comment]
I haven't tried to reproduce the issue again since finding the work-around. If I get a chance next week, I'll give it a try. I appreciate your responsiveness, but as I said, this is a low-priority since I did find a work-around.

**Comment by jobisoft** [comment]
Oh, you have edited your original response. I have not catched that.

**Comment by jfdahl** [comment]
I'm sorry to hear that you have chosen to simply close this issue, but I have more information for you anyway. The issue is that your plugin is trying to synchronize before the master password has unlocked the keychain so the saved account credentials are not available and the plugin prompts the user. I would suggest having a check for access to the keychain and a wait cycle to give the user a chance to enter the master password before continuing.

**Comment by jobisoft** [comment]
I looked solved, as there was no response from you within12 days. 

Answering the following questions would help me to understand the issue:

Could check, how the password prompt looks like, so I know which internal system is requesting the password? Does it look like what I posted in https://github.com/jobisoft/DAV-4-TbSync/issues/78#issuecomment-480297700 ?

What happens if you disable TbSync, and Restart TB? Do you get the same prompt?

**Comment by jfdahl** [comment]
The screenshot attached shows that it is a Thunderbird prompt, although the credentials are stored correctly in the settings. The issue does not happen when I disable TBSync and I would expect this to be the case since there are no other caldav accounts configured except through TBSync.
![CalDav error](https://user-images.githubusercontent.com/5903575/56856735-5529fe80-6926-11e9-857b-e89a94f0724f.png)

**Comment by jobisoft** [comment]
Ok, this is strange. Could you switch to beta, just to make sure, it is also not fixed there?
https://tbsync.jobisoft.de

After switching to beta, disable your iCloud account in TbSync and re-enable it. If it still happens I need a debug report (can be created under help in the tbsync manager).

The strange thing is, I do not see that behaviour here. Thanks for your help.

**Comment by jfdahl** [comment]
I've removed the ATN versions and installed the beta versions. I'll let you know how it goes.
Thanks,
John

**Comment by jfdahl** [comment]
Just a quick update.... the beta has been working well for the past week. I have not had any occurrences of this issue. So far, so good!

**Comment by jobisoft** [comment]
That is good news. Thanks.

**Comment by jfdahl** [comment]
Over a month into the beta and still no issues.
