### ISSUE TITLE
Contacts with more than two mail addresses are not supportet

### ISSUE THREAD

**Issue by Rumbelstilzchen** [jobisoft/DAV-4-TbSync#79]
## Your environment

TbSync version: 1.7
DAV-4-TbSync version: 0.15
Thunderbird version: 60.6.1

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I should be able to send an email to any of the addresses provided within the contact by choosing them in the dropdown-list during autocomplete.

## Actual behavior
All additional addresses (except the primary one) get merged to one string
![02_dropdown](https://user-images.githubusercontent.com/8233580/55655840-89ae0d00-57f5-11e9-8cf0-119bb2f9c862.png)

## Steps to reproduce
Create an user with more than two email addresses.
![01_remote_user](https://user-images.githubusercontent.com/8233580/55655901-b7935180-57f5-11e9-9d51-b2023cbb90b6.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I am currently working on that :-)
You are one of the first users to actually use my new multiple addresses UI. I still need to update the autocomplete mechanism. Hopefully next week or so.

**Comment by Rumbelstilzchen** [comment]
Hi, great to know.
just switched from "Inverse Sogo" to "CardBook" to your software. I like it much. Especially the address UI looks good! :-D
Don't know whether it helps, with Sogo Connector the autocomplete worked well. I could choose any of those addresses independently. (Although it was not possible to edit the extra addresses..). Don't know whether having a look at their code is possible/helps.

**Comment by jobisoft** [comment]
The SOGoConnector is replacing the standard autocomplete mechanism and changes the behavior for all address books, not just CardDAV. It do not like that, since it interferes with other extensions (and removes any other special autocomplete feature). I proposed a general support for the feature we need:

https://bugzilla.mozilla.org/show_bug.cgi?id=1542479

Lets see how this evolves.

**Comment by jobisoft** [comment]
That approach got declined. I need to think of something else …

**Comment by jobisoft** [comment]
My new approach has been accepted for TB68 and TB67. Waiting for approval for TB60:
https://bugzilla.mozilla.org/show_bug.cgi?id=1546425

**Comment by jobisoft** [comment]
I finally fixed this.

Current development has switched to Thunderbird 68 (Beta). I think I fixed this issue in the latest beta of TbSync for TB68.

Details about the beta release channel(s):
https://tbsync.jobisoft.de

Closing this to have it out of the way. You can still post.
