### ISSUE TITLE
Implement silent ignore sync-token.

### ISSUE THREAD

**Issue by plague-doctor** [jobisoft/DAV-4-TbSync#80]
## Your environment

TbSync version: 1.7
DAV-4-TbSync version: 0.15
Thunderbird version: 60.6.1

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Do not throw the sync-token errors.

## Actual behavior
TbSync throws error when syncing:

```
Request:
<d:sync-collection xmlns:d="DAV:"><d:sync-token>http://radicale.org/ns/sync/2e138cc284a8<...>202b24016bd</d:sync-token><d:sync-level>1</d:sync-level><d:prop><d:getetag/></d:prop></d:sync-collection>

Response:
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:">
<valid-sync-token />
</error>
```

## Steps to reproduce
Use EteSync with DAV-proxy.

**Comment by jobisoft** [comment]
Can I have a test account on such a server? Credentials via email. Thanks!

**Comment by jobisoft** [comment]
I fixed this in the beta release channel(s) of TbSync. More information can be found here:
https://tbsync.jobisoft.de

I would like to ask you to switch to Thunderbird 68 (Beta) and test the preview of TbSync for TB68.

The stable (official) version from addons.thunderbird.net will be updated within a couple of days.

Closing this to have it out of the way. If you run into issues, just reopen it. You can post even if it is closed.
