### ISSUE TITLE
2 Accounts, same server: insert a date fails

### ISSUE THREAD

**Issue by kuerbis42** [jobisoft/DAV-4-TbSync#81]
## Your environment

TbSync version:  1.7
DAV-4-TbSync version: 0.15
Thunderbird version: 60.6.1 (32-bit)
Server: Baïkal 0.4.6

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Insert/change a date (into a specific calendar) should show the date and saves it in TB and sync it to the server

## Actual behavior
if there are 2 (or maybe more) accounts activ within TbSync, it is not possible to edit or insert a new date to one of the calendars.
**Maybe here special: 1 server to different accounts** with each with 1 calendar (for testing), but it also happen with 2 account and serveral calendars/account (and 1 server)

## Steps to reproduce
add a second TbSync/Sabre account, activate it: issue happens, deactivate/delete, restart TB: all works fine (normaly the last added calendar still works)

Debug: (with 2 active accounts)
Account: Demo
folders[unhandledFolders[t][i]] is undefined

dav.sync.folderList<@chrome://dav4tbsync/content/sync.js:266:17
TaskImpl_run@resource://gre/modules/Task.jsm:326:42

**Note:** I know, that within the old TbSync, it wasn't possible to see the calendars of the second account (the issue there (never reported from me): If you add a 2. account, you only see the calendars from the 1. account. (Version: unkown, last Version within TB 52.x

TIA,
Kuerbis42

**Comment by jobisoft** [comment]
I fixed that issue for CardDAV, but for CalDAV it needs to be fixed in Lightning. I have send in a proposal to fix this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1544596

Until this is fixed in Lightning, you may use a workaround:
https://github.com/jobisoft/DAV-4-TbSync/wiki/Adding-multiple-accounts-from-the-same-Server

But this is of course not very secure, as your password will show up in the logs.

**Comment by jobisoft** [comment]
> Note: I know, that within the old TbSync, it wasn't possible to see the calendars of the second account (the issue there (never reported from me): If you add a 2. account, you only see the calendars from the 1. account. (Version: unkown, last Version within TB 52.x

Correct, the CalDAV discovery done by TbSync has also been fixed using the new container approach, that is why you can see them now. But Lightning still Needs to be fixed...

**Comment by kuerbis42** [comment]
@jobisoft: thx for the fast answer. I'll copy the lightning-issue here, so we can close this.


**### Currently lightning does not allow to set up two or more calendars from the same CalDAV server authenticated with different users.** This is caused by the following two issues:

    1. The password lookup method uses the host part of the URI and picks the first matching username/password entry from the password manager. It is not possible to actually specify the desired user. This can be fixed by adding the username as a property to the calendar.

   2. If issue 1 is fixed, lightning runs into a caching issue of the underlying network library, which is also just using the host part of the URI to access cookie and password caches. This can be fixed by using containers
