### ISSUE TITLE
Can't see free-busy information of my attendees

### ISSUE THREAD

**Issue by wit12345** [jobisoft/DAV-4-TbSync#82]
## Your environment

TbSync version: 0.15
DAV-4-TbSync version:
Thunderbird version: 60.6.1 

Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I'm make a new appointment I want to see the free-busy information of my attendees .

## Actual behavior
When I'm make a new appointment I can't see the free-busy information of my attendees 

## Steps to reproduce
Go to calendar, create a new event and add the attendees.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by wit12345** [comment]
wrong place, sorry :(

**Comment by jobisoft** [comment]
What happend?
