### ISSUE TITLE
iCloud contact photos sync

### ISSUE THREAD

**Issue by bmscmoreira** [jobisoft/DAV-4-TbSync#86]
## Your environment

TbSync version: TbSync [Beta Release Channel] 1.7.3
Thunderbird version: 60.6.1 64-bit (macOS 10.14.3) 

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
when updating a contact photo in TB, changes would be synced to iCloud contacts account, and vice-versa

## Actual behavior
when updating a contact photo in TB, changes are not synced to iCloud contacts account, and vice-versa

## Steps to reproduce
edit a contact in TB or in iCloud contacts app and initiate a sync.

Note: this is a minor issue IMHO, but nonetheless I wanted to report it. Thank you.

**Comment by jobisoft** [comment]
I think I fixed this in the latest beta:
https://tbsync.jobisoft.de

Could you give it a try?

After you switched to beta, you have to disable and re-enable your account in tbsync, to activate the new feature.

**Comment by bmscmoreira** [comment]
I’m sorry, I’m currently not using Thunderbird as I reverted back to using Mail on macOS, and stopped using an email client on windows...

**Comment by jobisoft** [comment]
Released as stable.
