### ISSUE TITLE
Can't see free-busy information of my attendees with EAS sync

### ISSUE THREAD

**Issue by wit12345** [jobisoft/DAV-4-TbSync#87]
## Your environment

TbSync version: 0.15
DAV-4-TbSync version: 0.12
Thunderbird version: 60.6.1

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

At this point I've the EAS configured on my server and I can sync everything with that.

## Expected behavior

- When I'm make a new appointment I want to see the free-busy information of my attendees
- Contacts doesn't appear duplicated

## Actual behavior

When I'm make a new appointment I can't see the free-busy information of my attendees and when I search for the contacts they appear two times.

## Steps to reproduce

Go to calendar, create a new event and add the attendees. I don't see the free-busy.

**Comment by jobisoft** [comment]
Out of my reach. CalDAV is handled by Lightning and if Lightning is not able to retrieve the free busy info (but should be able to do so), check this help page:

https://wiki.mozilla.org/Calendar:QA_CalDAV_Support#Diagnosis_hints
