### ISSUE TITLE
Differences in CardDAV encoding/decoding of phone number characteristics; TbSync vs. Nextcloud formatting

### ISSUE THREAD

**Issue by mMuck** [jobisoft/DAV-4-TbSync#89]
## Your environment
TbSync version: 1.7
DAV-4-TbSync version: 0.15
Thunderbird version: 60.7.0

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
1. TB phone number "mobile work" should be mapped to "mobile work" in Nextcloud (current stable version)
2. TB phone number "mobile private" should be mapped to "mobile private" in NC

## Actual behavior
In NC this entries like described show 1. "mobile" ("work" missing) and 2. "work" ("mobile" missing)
I downloaded the VCF in Nextcloud:
1. Written from TbSync: `TEL;TYPE=HOME;TYPE=CELL:...`
I changed it in Nextcloud to the correct entry.
CardDAV:`TEL;TYPE="HOME,CELL":...`
After the next sync TB shows no characteristics of the numbers in both examples 1. and 2. (they are not lost, but obviously could not be interpreted from TbSync).
2. Same problems on both sides.

As I understood this, TbSync writes this single appended `TYPE=HOME;TYPE=CELL` syntax. Nextcloud saves this and syncs correctly to other TbSync clients but Nextcloud itself expects the joined `TYPE="HOME,CELL"` format, can't decode the TbSync written thing and writes in the joined format.

Which one is right? Standard? Both?
If both are correct syntax, TbSync must interpret the NC syntax and NC the TbSync syntax.
Quick solution: Change you format to the NC format if you detect a NC instance. (In addition to correctly decode the NC format.
If not both are correct, who should correct it?

## Steps to reproduce
- Add dummy entries with different settings out of numbers tagged with "work", "mobile work", "private", "mobile private", ...
- Sync
- Compare Nextcloud web interface (contacts app) to VCF/Database

Thanks!! Great sync adapter.

**Comment by jobisoft** [comment]
I think I did that in beta, can you check?

Disconnect your account, update to beta, reconnect your account

https://tbsync.jobisoft.de

**Comment by mMuck** [comment]
Ups. Sorry,
Did I miss something? I checked the given URL (https://github.com/jobisoft/TbSync/releases) in the issue draft for a beta... Will the TbSync.xpi from https://tbsync.jobisoft.de/beta do the trick? Or DAV-4-TbSync? Or both?
Found no issue for this, is there one? (If not: You can file one by yourself to let anyone know the known issue.)
I will check the beta.

But is this the full solution? Where is the problem with the CardDAV standard? Who's right? :wink:

**Comment by jobisoft** [comment]
No need to be sorry. :-) I think that „bug“ was filed just via E-Mail, not as an issue. I do not remember, it was a lengthy process and at the end I switched. Both styles are correct, as far as I know.

If you want to switch to beta, you must switch TbSync itself and all provider you are using.

**Comment by conoroneill** [comment]
FYI, this was part of this previous issue:
https://github.com/jobisoft/DAV-4-TbSync/issues/49

**Comment by jobisoft** [comment]
@mMuck : Can I close this?

**Comment by dilyanpalauzov** [comment]
Both formats are valid:

[vCard MIME Directory Profile 3.3.1 TEL Type Definition](https://tools.ietf.org/html/rfc2426#section-3.3.1) says:

> These type parameter values can be specified as a parameter list (i.e., "TYPE=work;TYPE=voice") or as a value list (i.e., "TYPE=work,voice").
