### ISSUE TITLE
HTTP authentication not working, if server sends two or more WWW-Authenticate headers

### ISSUE THREAD

**Issue by jbash** [jobisoft/DAV-4-TbSync#9]
I'm not sure if this is supposed to work, but I would have thought it would.

I'm trying to use this extension to talk to Radicale embedded in Apache, with Basic authentication handled by the Apache server. The setup works with several other clients.

As soon as I try to make the first connection to the server, I get into an authentication loop, with dialogs asking me to "Please enter the password for user jbash" (I've also tried 'jbash@MY.REALM'; either should work on the server side).

Even after the password is entered, the Thunderbird network traffic trace doesn't show any authentication information in the request headers. The response headers always have 'WWW-Authenticate: Negotiate' and 'WWW-Authenticate: Basic realm="Contact and Calendar data"'. 

My best guess, based on basically zero knowledge of what's going on, is that that's because of this code:

```javascript
    //do not include credentials, so we do not end up in a session, see https://github.com/owncloud/core/issues/27093
    options.credentials = "omit";
```
... which in my copy is at lines 181-182 of tools.js .

The Basic authentication is backed by mod_auth_kerb, so I can't (easily) have Radicale do some other form of authentication. In fact I'd much rather everything were doing DAV over HTTP with GSSAPI rather than sending passwords over HTTP to begin with. I assume that there are other people who at least want to use Basic even if they don't want GSSAPI.

Thanks for writing the code, by the way...

Details
-------

### Stack trace

An example stack trace for one of the network transactions is:

| Name                    | Line                                                |
| ----------------------- | --------------------------------------------------- |
| dav.tools.sendRequest<  | chrome://dav4tbsync/content/tools.js:226:34         |
| TaskImpl_run            | resource://gre/modules/Task.jsm:326:42              |
| TaskImpl                | resource://gre/modules/Task.jsm:275:3               |
| asyncFunction           | resource://gre/modules/Task.jsm:247:14              |
| dav.sync.folderList<    | chrome://dav4tbsync/content/sync.js:81:38           |
| TaskImpl_run            | resource://gre/modules/Task.jsm:326:42              |
| TaskImpl                | resource://gre/modules/Task.jsm:275:3               |
| asyncFunction           | resource://gre/modules/Task.jsm:247:14              |
| dav.start<              | chrome://dav4tbsync/content/dav.js:332:27           |
| TaskImpl_run            | resource://gre/modules/Task.jsm:326:42              |
| TaskImpl                | resource://gre/modules/Task.jsm:275:3               |
| asyncFunction           | resource://gre/modules/Task.jsm:247:14              |
| syncAccount             | chrome://tbsync/content/tbsync.jsm:601:13           |
| observe/<               | chrome://tbsync/content/manager/accountSettings.js:66:196 |
| doOK                    | chrome://tbsync/content/manager/password.js:36:30   |
| anonymous               | chrome://global/content/bindings/dialog.xml%20line%20407%20%3E%20Function:3:8 |
| _fireButtonEvent        | chrome://global/content/bindings/dialog.xml:408:28  |
| _doButtonCommand        | chrome://global/content/bindings/dialog.xml:376:28  |
| _hitEnter               | chrome://global/content/bindings/dialog.xml:428:13  |
| onxblkeypress           | chrome://global/content/bindings/dialog.xml:436:1   |

### Headers

Request headers:

```
Host: organizer.kdjf.net
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.0 Lightning/6.2
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
depth: 0
prefer: return-minimal
content-type: application/xml; charset=utf-8
origin: null
Content-Length: 85
Connection: keep-alive
Cache-Control: max-age=0
```

Response headers:

```
HTTP/1.1 401 Unauthorized
Date: Wed, 12 Sep 2018 18:52:36 GMT
Server: Apache/2.4.34 (Fedora) OpenSSL/1.1.0h-fips mod_auth_kerb/5.4 mod_wsgi/4.5.20 Python/3.6
WWW-Authenticate: Negotiate
WWW-Authenticate: Basic realm="Contact and Calendar data"
Content-Length: 381
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

### Versions

+ sabre/dav provider 0.8.14
+ TbSync 0.7.15
+ Lightning 6.2
+ Thunberbird 60 (from Fedora: thunderbird-60.0-1.fc28.x86_64)
+ Radicale 2.1.8 (from Fedora: radicale-2.1.8-5.fc28.noarch)

**Comment by jobisoft** [comment]
May I have a test account on your server? Basic and Digest auth should work and have been tested.

**Comment by jobisoft** [comment]
The line "options.credentials = "omit";" is for rejecting/not sending any cookies.

But: I have never seen a DOUBLE WWW-Authenticate header and the code takes the first one and has no idea what to do with "negotiate". Is that according to an RFC?

**Comment by jobisoft** [comment]
It is allowed, did not know that.

[DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/2376688/DAV-4-TbSync.zip)

Can you try this and lookup the debug log and post the line with "Found WWW-Authenticate"

**Comment by jobisoft** [comment]
No, I mean the TbSync debug log
https://github.com/jobisoft/TbSync/wiki/Found-a-bug%3F

**Comment by jbash** [comment]
OK, sorry. Here's the whole log from trying to connect and typing the password once or twice. I don't see "Found" in there anywhere.
[debug.log](https://github.com/jobisoft/DAV-4-TbSync/files/2376956/debug.log)

**Comment by jobisoft** [comment]
1) Could you send me (via email) the accounts.json file from the tbsync directory insider your thunderbird profile, or post here the two fields authMethod and authOptions

2) The line we are looking for in the log is only added if you start from scratch, delete(!) the account and set it up again and try to sync

Thanks for your help!

**Comment by jobisoft** [comment]
Ok, no more info is needed, I was able to reproduce this by manipulating a testserver to send the second WWW-Auth header.

Bad news: You hit a bug in the fetch API I use to communicate with your server: If more than one WWW-Auth header is present, I am not getting ANY of them in my code. That will take a while to be fixed, because it is outside the scope of my AddOn.

Sorry. I update here any progress i make on this.

**Comment by jobisoft** [comment]
Can the mozilla dev use your server as a test case for this bug?

They do not need access, they will send unauthenticated requests to trigger the WWW-Authenticate header in the answer.

**Comment by jbash** [comment]
I don't see why they shouldn't use it. It's reachable from the Net. They'll have to accept the cert. organizer.kdjf.net
I will refrain for a while from trying to get it to stop sending two headers. :-)
Thanks.

**Comment by jobisoft** [comment]
Lets see how this goes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1491010

**Comment by jobisoft** [comment]
Could you try this one?

[DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/2381086/DAV-4-TbSync.zip)

Instead of using the fetch API, I now use XMLHttpRequest for the auth request. I have to check a few other things, but if this works, I might switch to XMLHttpRequest for all request and dump fetch.

**Comment by jobisoft** [comment]
Just to have it all in here, that is the open question:
https://groups.google.com/forum/#!topic/mozilla.dev.platform/P9pAv4q1HJE

**Comment by jbash** [comment]
OK, that one logs in without any problem.

**Comment by jobisoft** [comment]
I am currently evaluating how to proceed. The patch for this issue will probably not land in the main version, so stick to this special version for now and do not update. There are currently too many open questions around this topic and I need to get my head free..

**Comment by jobisoft** [comment]
Hi, 

this took much longer than expected. I rewrote the network code, no longer using the faulty API. I tested it against all my test servers and it worked. Would you give it a try?

You need 0.8.30 of the DAV provider:
https://github.com/jobisoft/DAV-4-TbSync/releases/download/v0.8/DAV-4-TbSync-0.8.30-BETA.xpi

And 0.7.19 of TbSync:
https://github.com/jobisoft/TbSync/releases/download/v0.7.19/TbSync-0.7.19.xpi

Any feedback is helpful.

**Comment by jobisoft** [comment]
The beta of the DAV provider has moved (and improved):
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

**Comment by jobisoft** [comment]
v0.9 is out
