### ISSUE TITLE
Nextcloud has error 503 (service not available)

### ISSUE THREAD

**Issue by jeromelebleu** [jobisoft/DAV-4-TbSync#91]
There is an issue between Nextcloud and Thunderbird, which affects TbSync and Lightning. TbSync reports "Error 503" (service not available) when I try to add a new account in TbSync. Note that I already configured calendars in Lightning for that account.

Unfortunately, `network.cookie.same-site.enabled` has been removed from last Thunderbird version - see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1551821) - and the proposed fix in #41 can not apply anymore.

Thanks in advance!

**Comment by jobisoft** [comment]
Are you subscribed to multiple users/accounts on the same server?

**Comment by jeromelebleu** [comment]
I have updated the description to describe a bit more my issue. To sum up, I have this issue when I try to add my account in TbSync. Note that I already configured calendars in Lightning for that account without TbSync. I would like to use TbSync for contacts in this case.

**Comment by jobisoft** [comment]
For contacts I fixed the root cause of this issue in the latest beta:

https://tbsync.jobisoft.de

For lightning I have a patch send in, but it is sort of hanging there. Maybe you could make some noise in the bug.

https://bugzilla.mozilla.org/show_bug.cgi?id=1544596

**Comment by jeromelebleu** [comment]
Glad to know that you already know about it and you already send a patch to Thunderbird, thanks for all your work! I am closing this issue so as it is related to Thunderbird, I imagine you would agree with that.

**Comment by jobisoft** [comment]
If you have the time, I REALLY suggest to drop a comment in bug 1544596, so that the lightning maintainer sees the need for accepting my patch. I am working on that patch (in total) for about a year now ...
