### ISSUE TITLE
More unnecessary updating of contacts; caused by image encoding

### ISSUE THREAD

**Issue by conoroneill** [jobisoft/DAV-4-TbSync#92]
## Your environment

TbSync version:
DAV-4-TbSync version:
Thunderbird version:

[Y] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I use a contact's address to send an email, but I don't modify the contact details itself, the TbSync process should not send a new copy from Thunderbird to the server.

## Actual behavior
In some circumstances, when I 'touch' a contact (by using it), but don't modify it, the TbSync process sends a new copy from Thunderbird to the server.
Note that this is closely related to an issue I reported previously:
https://github.com/jobisoft/DAV-4-TbSync/issues/49

## Steps to reproduce
I have discovered that:
If a contact is created within Thunderbird's address book,
and I have previously added a photo to that contact,
and I then send an email _to_ that contact but don't make any other changes,
and I then synchronise with the Kolab server
the TbSync process thinks that the contact's details have changed, and it sends a 'new' version to the Kolab server, but which is in fact identical to the previous version.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I have looked through the logs, and I have determined that the TbSync process thinks that the contact has changed because of the format of the photo.

The 'currentCard' VCARD includes an entry like this:
PHOTO;ENCODING=B;TYPE=JPEG:/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwME
...

The 'newCard' VCARD includes an entry like this:
PHOTO;ENCODING=b;TYPE=JPEG:/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwME
...

Note that the former says "ENCODING=B" but the latter says "ENCODING=b"
There appears to be no other change.

I will attach the debug log.

**Comment by conoroneill** [comment]
[debug2.log](https://github.com/jobisoft/DAV-4-TbSync/files/3238540/debug2.log)

**Comment by jobisoft** [comment]
ah, so I have to default to lowercase or uppercase for some non-userdata-fields too. I will do that. But even if the fix is simple, I do not know, when I can get to it, because currently I am rewriting TbSync for TB68 and that is taking all my time. 

This is not "critical" for you, as it is just anyoing, but not bad in any other way right?

**Comment by conoroneill** [comment]
Thanks for your effort.
Yes, this is not critical. Just slightly annoying.

**Comment by jobisoft** [comment]
I believe this is fixed now in the latest beta:
https://tbsync.jobisoft.de

Could you verify?

**Comment by conoroneill** [comment]
John,

Unfortunately this issue doesn't seem to be fixed.
I have two test accounts, one with a small PNG as the photo, and a second one with a small JPEG (which seems to have got a lot larger within the address book entries).
I will attach two debug logs; the first for the PNG test, the second from the JPEG test.

**Comment by conoroneill** [comment]
[debug10.log](https://github.com/jobisoft/DAV-4-TbSync/files/4208448/debug10.log)

[debug11.log](https://github.com/jobisoft/DAV-4-TbSync/files/4208449/debug11.log)

![ExamplePNG](https://user-images.githubusercontent.com/5719136/74587762-7e6b6680-4fee-11ea-8f7d-df7c55e2a711.png)

![JPEG_example_JPG_RIP_001](https://user-images.githubusercontent.com/5719136/74587763-81feed80-4fee-11ea-8679-a13505d0e41d.jpg)

**Comment by jobisoft** [comment]
Have these photos been part of the address book already or did you add them recently? Did you sync your addressbook fresh with the beta or have those contacts been added to Thunderbird by the stable version?

Whatever the current situation is, can you disable your account in TbSync and re-enable it, so it gets downloaded with the beta and then test again, if it gets identified as "modified" if you use the contact?

**Comment by conoroneill** [comment]
These had all been created within Thunderbird using the previous (stable) version.
I'll test again as you suggest with a clean account and the beta.

**Comment by conoroneill** [comment]
I now have a 'clean' account, fully re-created by re-syncing using the TbSync Beta.
Now I'm getting different results for different contacts. Some are working fine, others still have the problem.

This one always pushes a new version upstream.
[debug21_bad.log](https://github.com/jobisoft/DAV-4-TbSync/files/4208741/debug21_bad.log)

This one seems to be happy, and is not pushing a new version upstream.
[debug22_good.log](https://github.com/jobisoft/DAV-4-TbSync/files/4208742/debug22_good.log)

Both have photos attached.

**Comment by jobisoft** [comment]
Thanks. I see that the type definition changes from png to jpeg. That is something I have worked on in beta as well. It still needs some work.

**Comment by jobisoft** [comment]
I truly believe this is fixed now. Please update your beta addons via the gear menu in the Thunderbird Add-On Manager and start fresh (disable and re-enable your account). 

Thanks for your help.

**Comment by conoroneill** [comment]
Thank you. This does appear to be fixed now; I will leave my settings as they are for a few days to see if any of my other contacts are being affected.

**Comment by jobisoft** [comment]
Released as stable.
