### ISSUE TITLE
Fields don't fit into borders of the "Edit Contact" dialog in localized Thunderbird

### ISSUE THREAD

**Issue by skynick11** [jobisoft/DAV-4-TbSync#93]
## Your environment

TbSync version: beta 1.7.6
DAV-4-TbSync version: 0.15.13
Thunderbird version: 60.7.2
OS: Windows 7, Windows 10

[x ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Fields don't fit into borders of the "Edit Contact" dialog in some localizations of Thunderbird, the dialog isn't resizable. In the released version of TbSync they don't fit in both horizontal (in all tabs) and  vertical (in some tabs) borders, in the beta the horizontal fitness is good (marked by green rectangles), but the vertical fitness in "Contact" and "Other" tabs is a bit wrong (marked by red rectangles).
Note: I don't sure about the EAS connector, but I currently have some problems with it and so can't check the same dialogs.

Contact:
![Contact-1](https://user-images.githubusercontent.com/37669204/60165181-92681b00-9807-11e9-81e1-ef4042e22811.png)

Other:
![Other-1](https://user-images.githubusercontent.com/37669204/60164250-e540d300-9805-11e9-94d2-a19185c1615a.png)

**Comment by jobisoft** [comment]
Current development has switched to Thunderbird 68 (Beta). I think I fixed this issue in the latest beta of TbSync for TB68.

Details about the beta release channel(s):
https://tbsync.jobisoft.de

Closing this to have it out of the way. You can still post.
