### ISSUE TITLE
iCloud dav servers are not found

### ISSUE THREAD

**Issue by jfdahl** [jobisoft/DAV-4-TbSync#95]
## Your environment

TbSync version: 1.7.6
DAV-4-TbSync version: 0.15.13
Thunderbird version: 60.7.2 (64-bit)

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Calendar content was synching just fine

## Actual behavior
I started getting errors that the caldav.icloud.com server could not be found. After removing and attempting to add my account, I was getting a 501 error:

URL:
https://icloud.com/.well-known/carddav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
<HTML>
<HEAD>
<TITLE>Unsupported Request</TITLE>
</HEAD>
<BODY>
<H1>Unsupported Request</H1>
PROPFIND to http&#58;&#47;&#47;www&#46;icloud&#46;com&#47;&#46;well&#45;known&#47;carddav not supported.<P>
Reference&#32;&#35;8&#46;6cadf17&#46;1562948427&#46;f52b8dd
</BODY>
</HTML>

## Steps to reproduce
I tried removing all accounts and settings, then re-configuring from scratch. The configuration would not complete because the server was not found.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Apple server is currently broken. See https://github.com/jobisoft/TbSync/issues/264
