### ISSUE TITLE
Tbync doesn't work stable with iCloud (CalDAV and CardDAV)

### ISSUE THREAD

**Issue by mayrhofer-netzmuehle** [jobisoft/DAV-4-TbSync#96]
## Your environment

TbSync version: 1.7
DAV-4-TbSync version: 0.15
Thunderbird version: 60.8

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
synchronization works stable until configuration and not just for some hours. 

## Actual behavior
After starting Thunderbird the log shows me that i can't find the CalDAV server

## Steps to reproduce
- installing TbSync
- adding an icloud account
- restart your computer and thunderbird after a few days
- trying to synchronize your data

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
FYI:
https://github.com/jobisoft/TbSync/issues/264#issuecomment-510870746

Please watch the other issue for progress.
